import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

const componentPath = resolve(dirname(fileURLToPath(import.meta.url)), '../OpsDashboardHeader.vue')
const componentSource = readFileSync(componentPath, 'utf8')
const visualRepairCssPath = resolve(dirname(fileURLToPath(import.meta.url)), '../../../../../styles/targeted-visual-repair.css')
const visualRepairCss = readFileSync(visualRepairCssPath, 'utf8')

describe('OpsDashboardHeader title icon', () => {
  it('does not render a decorative logo before the title', () => {
    const headingMatch = componentSource.match(/<h1[\s\S]*?<\/h1>/)

    expect(headingMatch).not.toBeNull()
    expect(headingMatch?.[0]).not.toContain('<svg')
    expect(headingMatch?.[0]).not.toContain('<Icon')
    expect(componentSource).not.toContain('M9 19v-6a2 2 0 00-2-2H5')
  })

  it('keeps the health score background ring on the same semantic color', () => {
    const healthRingMatch = componentSource.match(/<svg[\s\S]*?ops-health-score-ring[\s\S]*?<\/svg>/)

    expect(healthRingMatch).not.toBeNull()
    expect(healthRingMatch?.[0]).toContain('ops-health-score-ring')
    expect(healthRingMatch?.[0]).toContain(':style="healthScoreRingStyle"')
    expect(healthRingMatch?.[0]).toContain('class="ops-health-score-track"')
    expect(healthRingMatch?.[0]).toContain('ops-health-score-progress')
    expect(healthRingMatch?.[0]).toContain(':stroke="healthScoreColor"')
    expect(healthRingMatch?.[0].match(/:style="\{ stroke: healthScoreColor \}"/g)).toHaveLength(2)
    expect(healthRingMatch?.[0]).toContain('opacity="0.22"')
    expect(componentSource).toContain('const healthScoreRingStyle = computed(() => ({')
    expect(componentSource).toContain("'--ops-health-score-color': healthScoreColor.value")
    expect(componentSource).toContain(':style="healthScoreRingStyle"')
    expect(componentSource).toContain('if (isSystemIdle.value) return colors.neutral')
    expect(componentSource).toContain('if (score == null) return colors.neutral')
    expect(componentSource).toContain('const healthScoreStyle = computed(() => ({')
    expect(componentSource).toContain('color: healthScoreColor.value')
    expect(componentSource).toContain(':style="healthScoreStyle"')
    expect(componentSource).toContain('ops-health-score-value font-black')
    expect(componentSource).toContain('ops-health-score-state mt-1 text-xs font-bold')
    expect(componentSource).not.toContain('const healthScoreClass = computed')
    expect(componentSource).not.toContain("return '#9ca3af'")
    expect(componentSource).not.toContain('class="text-gray-200 dark:text-dark-700"')
    expect(componentSource).not.toContain("return 'text-emerald-600'")
    expect(componentSource).not.toContain("return 'text-amber-600'")
    expect(componentSource).not.toContain("return 'text-red-500'")
  })

  it('keeps the ops toolbar framed and prevents the health diagnosis popover from affecting static layout', () => {
    const toolbarMatch = componentSource.match(/<div class="ops-monitor-toolbar[\s\S]*?>/)
    const popoverMatch = componentSource.match(/<div\s+aria-hidden="true"\s+class="ops-diagnosis-popover[\s\S]*?>/)

    expect(toolbarMatch).not.toBeNull()
    expect(toolbarMatch?.[0]).toContain('items-center')
    expect(toolbarMatch?.[0]).not.toContain('border-b')
    expect(toolbarMatch?.[0]).not.toContain('pb-4')

    expect(componentSource).toContain('class="ops-monitor-toolbar-controls ml-auto"')
    expect(componentSource).toContain('class="ops-toolbar-labeled-select"')
    expect(componentSource).toContain('class="ops-toolbar-select-label">来源</span>')
    expect(componentSource).toContain('class="ops-toolbar-select-label">分组</span>')
    expect(componentSource).toContain('aria-label="来源"')
    expect(componentSource).toContain('aria-label="分组"')
    expect(componentSource).toContain('aria-label="时间范围"')
    expect(componentSource).toContain('class="ops-toolbar-select"')
    expect(componentSource).not.toContain('class="ops-toolbar-icon-button"')
    expect(componentSource).toContain('class="ops-toolbar-primary-button anthropic-refresh-action-button"')
    expect(componentSource).toContain('class="ops-toolbar-text-button"')
    expect(componentSource).toContain('ops-realtime-window-group flex flex-wrap gap-1')
    expect(componentSource).not.toContain('ops-monitor-toolbar-controls flex flex-wrap items-center gap-3')
    expect(componentSource).not.toContain('mx-1 hidden h-4 w-[1px]')
    expect(componentSource).not.toContain('ops-toolbar-icon-button flex h-8 w-8')
    expect(componentSource).not.toContain('ops-toolbar-text-button flex h-8')
    expect(componentSource).not.toContain('class="ops-toolbar-icon-button anthropic-refresh-action-button"')

    expect(componentSource).not.toContain('ops-health-score-card group')
    expect(componentSource).toContain('class="ops-health-score-progress"')
    expect(componentSource).not.toContain('ops-health-score-progress transition-all')
    expect(componentSource).not.toContain('group-hover:pointer-events-auto')
    expect(componentSource).not.toContain('group-hover:opacity-100')
    expect(popoverMatch).not.toBeNull()
    expect(popoverMatch?.[0]).toContain('hidden')
    expect(popoverMatch?.[0]).toContain('pointer-events-none')
  })

  it('does not render the realtime decorative pulse line under the metrics', () => {
    const realtimePanelMatch = componentSource.match(/<!-- 2\) Realtime Traffic -->[\s\S]*?<!-- Right: 6 cards/)

    expect(realtimePanelMatch).not.toBeNull()
    expect(realtimePanelMatch?.[0]).not.toContain('Animated Pulse Line')
    expect(realtimePanelMatch?.[0]).not.toContain('viewBox="0 0 280 32"')
    expect(realtimePanelMatch?.[0]).not.toContain(':stroke="getOpsChartColors().throughput"')
    expect(realtimePanelMatch?.[0]).not.toContain('<animate')
  })

  it('keeps the ops toolbar and refresh controls on the Anthropic action contract', () => {
    expect(visualRepairCss).toContain('#app .app-layout-content .ops-dashboard-atelier .ops-monitor-toolbar {')
    expect(visualRepairCss).toContain('background: var(--anthropic-page) !important;')
    expect(visualRepairCss).toContain('button.anthropic-refresh-action-button')
    expect(visualRepairCss).toContain('button.dashboard-filter-refresh')
    expect(visualRepairCss).toContain('button[data-testid*="refresh"]:not([data-testid*="auto-refresh"]):not([data-testid*="refresh-token"])')
    expect(visualRepairCss).toContain('button[data-testid*="-button-load"]:not([data-testid*="download"])')
    expect(visualRepairCss).toContain('button[data-testid*="-button-fetch"]:not([data-testid*="download"])')
    expect(visualRepairCss).toContain('--anthropic-clay-interactive: #c96442;')
    expect(visualRepairCss).toContain('--button-bg: transparent;')
    expect(visualRepairCss).toContain('--button-fg: var(--anthropic-muted);')
    expect(visualRepairCss).toContain('--button-border: var(--anthropic-border-subtle);')
    expect(visualRepairCss).toContain('background: var(--button-bg) !important;')
    expect(visualRepairCss).toContain('color: var(--button-fg) !important;')
    expect(visualRepairCss).toContain('box-shadow: 0 0 0 var(--button-spacer, 0) var(--button-bg), 0 0 0 var(--button-border-width, 1px) var(--button-border) !important;')
    expect(visualRepairCss).toContain('box-shadow: 0 0 0 var(--button-spacer-hover, 1px) var(--button-bg), 0 0 0 var(--button-border-width-hover, 2px) var(--button-border-hover) !important;')
    expect(visualRepairCss).toContain('.ops-realtime-panel > .mb-3')
    expect(visualRepairCss).toContain('padding-inline-end: 0.75rem !important;')
    expect(visualRepairCss).toContain('.ops-realtime-window-group')
    expect(visualRepairCss).toContain('padding-inline-end: 1rem !important;')
    expect(visualRepairCss).not.toContain('padding-inline-end: 0.25rem !important;')
    expect(visualRepairCss).toContain('.ops-metric-card button[data-testid*="open-details"]')
    expect(visualRepairCss).toContain('color: var(--anthropic-fg) !important;')
    expect(visualRepairCss).toContain('.ops-toolbar-primary-button')
    expect(visualRepairCss).toContain('.ops-toolbar-primary-button.anthropic-refresh-action-button')
    expect(visualRepairCss).toContain('.ops-toolbar-labeled-select')
    expect(visualRepairCss).toContain('.ops-toolbar-select-label')
    expect(visualRepairCss).toContain('.ops-monitor-toolbar-controls :where(.select-trigger:focus, .select-trigger-open):not(:focus-visible)')
    expect(visualRepairCss).toContain('outline: 0 !important;')
    expect(visualRepairCss).toContain('.dashboard-filter-refresh.btn.btn-tertiary.btn-tiny.dashboard-paper-control.anthropic-refresh-action-button:not(:disabled)')
    expect(visualRepairCss).not.toContain('.ops-toolbar-icon-button.anthropic-refresh-action-button')
  })
})
