// Code generated by ent, DO NOT EDIT.

package codexaccountmetadata

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEQ(FieldUpdatedAt, v))
}

// AuthName applies equality check predicate on the "auth_name" field. It's identical to AuthNameEQ.
func AuthName(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEQ(FieldAuthName, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEQ(FieldGroupID, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEQ(FieldDisplayName, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEQ(FieldNote, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldLTE(FieldUpdatedAt, v))
}

// AuthNameEQ applies the EQ predicate on the "auth_name" field.
func AuthNameEQ(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEQ(FieldAuthName, v))
}

// AuthNameNEQ applies the NEQ predicate on the "auth_name" field.
func AuthNameNEQ(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldNEQ(FieldAuthName, v))
}

// AuthNameIn applies the In predicate on the "auth_name" field.
func AuthNameIn(vs ...string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldIn(FieldAuthName, vs...))
}

// AuthNameNotIn applies the NotIn predicate on the "auth_name" field.
func AuthNameNotIn(vs ...string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldNotIn(FieldAuthName, vs...))
}

// AuthNameGT applies the GT predicate on the "auth_name" field.
func AuthNameGT(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldGT(FieldAuthName, v))
}

// AuthNameGTE applies the GTE predicate on the "auth_name" field.
func AuthNameGTE(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldGTE(FieldAuthName, v))
}

// AuthNameLT applies the LT predicate on the "auth_name" field.
func AuthNameLT(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldLT(FieldAuthName, v))
}

// AuthNameLTE applies the LTE predicate on the "auth_name" field.
func AuthNameLTE(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldLTE(FieldAuthName, v))
}

// AuthNameContains applies the Contains predicate on the "auth_name" field.
func AuthNameContains(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldContains(FieldAuthName, v))
}

// AuthNameHasPrefix applies the HasPrefix predicate on the "auth_name" field.
func AuthNameHasPrefix(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldHasPrefix(FieldAuthName, v))
}

// AuthNameHasSuffix applies the HasSuffix predicate on the "auth_name" field.
func AuthNameHasSuffix(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldHasSuffix(FieldAuthName, v))
}

// AuthNameEqualFold applies the EqualFold predicate on the "auth_name" field.
func AuthNameEqualFold(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEqualFold(FieldAuthName, v))
}

// AuthNameContainsFold applies the ContainsFold predicate on the "auth_name" field.
func AuthNameContainsFold(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldContainsFold(FieldAuthName, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldNotNull(FieldGroupID))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldContainsFold(FieldDisplayName, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldContainsFold(FieldNote, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.FieldLTE(FieldSortOrder, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.CodexGroup) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CodexAccountMetadata) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CodexAccountMetadata) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CodexAccountMetadata) predicate.CodexAccountMetadata {
	return predicate.CodexAccountMetadata(sql.NotPredicates(p))
}
