import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { describe, expect, it } from 'vitest'

const styleSource = readFileSync(resolve(__dirname, '../style.css'), 'utf8')
const appHeaderSource = readFileSync(resolve(__dirname, '../components/layout/AppHeader.vue'), 'utf8')
const appSidebarSource = readFileSync(resolve(__dirname, '../components/layout/AppSidebar.vue'), 'utf8')
const localeSwitcherSource = readFileSync(resolve(__dirname, '../components/common/LocaleSwitcher.vue'), 'utf8')
const selectSource = readFileSync(resolve(__dirname, '../components/common/Select.vue'), 'utf8')
const dashboardSource = readFileSync(resolve(__dirname, '../views/admin/DashboardView.vue'), 'utf8')
const usersSource = readFileSync(resolve(__dirname, '../views/admin/UsersView.vue'), 'utf8')
const tablePageLayoutSource = readFileSync(resolve(__dirname, '../components/layout/TablePageLayout.vue'), 'utf8')
const accountsSource = readFileSync(resolve(__dirname, '../views/admin/AccountsView.vue'), 'utf8')
const groupsSource = readFileSync(resolve(__dirname, '../views/admin/GroupsView.vue'), 'utf8')
const channelsSource = readFileSync(resolve(__dirname, '../views/admin/ChannelsView.vue'), 'utf8')
const proxiesSource = readFileSync(resolve(__dirname, '../views/admin/ProxiesView.vue'), 'utf8')
const accountTableActionsSource = readFileSync(resolve(__dirname, '../components/admin/account/AccountTableActions.vue'), 'utf8')
const accountTableFiltersSource = readFileSync(resolve(__dirname, '../components/admin/account/AccountTableFilters.vue'), 'utf8')
const monitorFiltersBarSource = readFileSync(resolve(__dirname, '../components/admin/monitor/MonitorFiltersBar.vue'), 'utf8')
const adminUsageFiltersSource = readFileSync(resolve(__dirname, '../components/admin/usage/UsageFilters.vue'), 'utf8')
const adminUsageStatsCardsSource = readFileSync(resolve(__dirname, '../components/admin/usage/UsageStatsCards.vue'), 'utf8')
const adminUsageSource = readFileSync(resolve(__dirname, '../views/admin/UsageView.vue'), 'utf8')
const announcementsSource = readFileSync(resolve(__dirname, '../views/admin/AnnouncementsView.vue'), 'utf8')
const redeemSource = readFileSync(resolve(__dirname, '../views/admin/RedeemView.vue'), 'utf8')
const promoCodesSource = readFileSync(resolve(__dirname, '../views/admin/PromoCodesView.vue'), 'utf8')
const userUsageSource = readFileSync(resolve(__dirname, '../views/user/UsageView.vue'), 'utf8')
const userKeysSource = readFileSync(resolve(__dirname, '../views/user/KeysView.vue'), 'utf8')
const keyUsageSource = readFileSync(resolve(__dirname, '../views/KeyUsageView.vue'), 'utf8')
const homeSource = readFileSync(resolve(__dirname, '../views/HomeView.vue'), 'utf8')
const endpointPopoverSource = readFileSync(resolve(__dirname, '../components/keys/EndpointPopover.vue'), 'utf8')
const platformIconSource = readFileSync(resolve(__dirname, '../components/common/PlatformIcon.vue'), 'utf8')
const usageProgressBarSource = readFileSync(resolve(__dirname, '../components/account/UsageProgressBar.vue'), 'utf8')
const settingsSource = readFileSync(resolve(__dirname, '../views/admin/SettingsView.vue'), 'utf8')
const opsDashboardSource = readFileSync(resolve(__dirname, '../views/admin/ops/OpsDashboard.vue'), 'utf8')
const opsDashboardHeaderSource = readFileSync(resolve(__dirname, '../views/admin/ops/components/OpsDashboardHeader.vue'), 'utf8')
const opsConcurrencySource = readFileSync(resolve(__dirname, '../views/admin/ops/components/OpsConcurrencyCard.vue'), 'utf8')
const opsSwitchSource = readFileSync(resolve(__dirname, '../views/admin/ops/components/OpsSwitchRateTrendChart.vue'), 'utf8')
const opsThroughputSource = readFileSync(resolve(__dirname, '../views/admin/ops/components/OpsThroughputTrendChart.vue'), 'utf8')
const opsLatencySource = readFileSync(resolve(__dirname, '../views/admin/ops/components/OpsLatencyChart.vue'), 'utf8')
const opsErrorDistributionSource = readFileSync(resolve(__dirname, '../views/admin/ops/components/OpsErrorDistributionChart.vue'), 'utf8')
const opsErrorTrendSource = readFileSync(resolve(__dirname, '../views/admin/ops/components/OpsErrorTrendChart.vue'), 'utf8')
const opsAlertEventsSource = readFileSync(resolve(__dirname, '../views/admin/ops/components/OpsAlertEventsCard.vue'), 'utf8')
const opsSystemLogSource = readFileSync(resolve(__dirname, '../views/admin/ops/components/OpsSystemLogTable.vue'), 'utf8')
const codexThemeSource = readFileSync(resolve(__dirname, '../styles/codex-theme.css'), 'utf8')
const globalPricingSource = readFileSync(resolve(__dirname, '../views/user/GlobalPricingView.vue'), 'utf8')
const indexHtmlSource = readFileSync(resolve(__dirname, '../../index.html'), 'utf8')
const materialSystemBlock = styleSource.slice(
  styleSource.indexOf('Atelier component material system'),
  styleSource.length
)

describe('console atelier palette restyle', () => {
  it('keeps the app shell on the two Downloads reference colors without introducing glass effects', () => {
    expect(styleSource).toContain('--atelier-canvas: var(--atelier-paper);')
    expect(styleSource).toContain('--atelier-material-1: var(--atelier-paper-2);')
    expect(styleSource).toContain('--atelier-material-2: var(--atelier-paper-2);')
    expect(styleSource).toContain('--atelier-console-grid-line: rgba(23, 21, 18, 0.035);')
    expect(styleSource).toContain('--atelier-console-grid-line-soft: rgba(23, 21, 18, 0.025);')
    expect(styleSource).toContain('--atelier-console-grid-size: 32px 32px;')
    expect(styleSource).toContain('--atelier-butter: #c79a3a;')
    expect(styleSource).toContain('--atelier-butter-soft: #c79a3a;')
    expect(styleSource).toContain('--sans: "Inter Tight", "HarmonyOS Sans SC", "HarmonyOS Sans"')
    expect(styleSource).toContain('--serif: "Inter Tight", "HarmonyOS Sans SC", "HarmonyOS Sans"')
    expect(styleSource).toContain('--mono: "Sarasa Mono SC", "Sarasa Fixed SC", "Sarasa Term SC"')
    expect(indexHtmlSource).toContain('family=Inter+Tight:wght@400;500;600')
    expect(indexHtmlSource).toContain('family=IBM+Plex+Mono:wght@400;500')
    expect(styleSource).toContain('#app,')
    expect(styleSource).toContain('.date-picker-dropdown-portal {')
    expect(styleSource).toContain('radial-gradient(circle at 12% 18%, rgba(0, 47, 167, 0.06), transparent 28rem)')
    expect(styleSource).toContain('radial-gradient(circle at 84% 9%, rgba(199, 154, 58, 0.07), transparent 24rem)')
    expect(styleSource).toContain('linear-gradient(90deg, var(--atelier-console-grid-line) 1px, transparent 1px)')
    expect(styleSource).toContain('background-size: auto, auto, var(--atelier-console-grid-size), var(--atelier-console-grid-size), auto;')
    expect(styleSource).not.toContain('card-glass')
    expect(styleSource).not.toContain('glass-card')
    expect(styleSource).not.toContain('liquid')
    expect(materialSystemBlock).not.toContain(':where(.card, .paper-card, .paper-surface, .stat-card, .summary-tile, .admin-material-surface, .codex-panel, .codex-account-card):nth-of-type')
  })

  it('uses uniform paper-2 modules and dotted rules while preserving existing component class hooks', () => {
    expect(appHeaderSource).toContain('class="app-header-atelier paper-surface sticky')
    expect(appHeaderSource).toContain('height: 4rem;')
    expect(appHeaderSource).toContain('data-testid="header-context-strip"')
    expect(appHeaderSource).toContain('app-header-meta-line')
    expect(appHeaderSource).toContain('app-header-route-meta')
    expect(appHeaderSource).toContain('max-w-[44vw]')
    expect(appHeaderSource).toContain('headerRouteLabel')
    expect(appHeaderSource).not.toContain('headerBalanceSummary')
    expect(materialSystemBlock).toContain('.app-header-atelier .balance-chip-buzz')
    expect(materialSystemBlock).toContain('background: transparent !important;')
    expect(materialSystemBlock).toContain('background: var(--atelier-butter) !important;')
    expect(localeSwitcherSource).toContain('currentLocale?.code.toUpperCase()')
    expect(localeSwitcherSource).not.toContain('currentLocale?.flag')
    expect(localeSwitcherSource).not.toContain('locale.flag')
    expect(appSidebarSource).toContain('class="sidebar-link')
    expect(appSidebarSource).toContain('box-shadow: none;')
    expect(appSidebarSource).toContain('filter: none;')
    expect(dashboardSource).toContain('admin-dashboard-atelier')
    expect(dashboardSource).toContain('card dashboard-filter-card')
    expect(dashboardSource).toContain('grid grid-cols-2 gap-4 lg:grid-cols-4')
    expect(dashboardSource).not.toContain('dashboard-page-head')
    expect(dashboardSource).not.toContain('dashboard-kpi-grid')
    expect(dashboardSource).not.toContain('dashboard-perf-band')
    expect(dashboardSource).not.toContain('dashboard-chart-grid')
    expect(dashboardSource).not.toContain('dashboard-kpi-card')
    expect(dashboardSource).toContain('--dashboard-module-rule: var(--atelier-console-rule);')
    expect(dashboardSource).toContain('--dashboard-control-surface: var(--atelier-paper-2);')
    expect(dashboardSource).toContain('dashboard-filter-range flex items-center gap-2')
    expect(dashboardSource).toContain('dashboard-filter-granularity ml-auto flex items-center gap-2')
    expect(dashboardSource).toContain('.admin-dashboard-atelier :deep(.dashboard-filter-card > div > .dashboard-filter-range)')
    expect(dashboardSource).toContain('.admin-dashboard-atelier :deep(.dashboard-filter-card > div > .dashboard-filter-range)::after')
    expect(dashboardSource).toContain('.admin-dashboard-atelier :deep(.dashboard-filter-card .dashboard-filter-refresh)::after')
    expect(dashboardSource).toContain('.admin-dashboard-atelier :deep(.dashboard-filter-card:hover > div > .dashboard-filter-range > span)')
    expect(dashboardSource).toContain('.admin-dashboard-atelier :deep(.dashboard-filter-card > div > .flex:not(.dashboard-filter-range))')
    expect(dashboardSource).toContain('.admin-dashboard-atelier :deep(.dashboard-filter-card:hover)')
    expect(styleSource).toContain('#app .app-layout-content .admin-dashboard-atelier .dashboard-filter-card:hover .dashboard-filter-range :where(span, svg)')
    expect(styleSource).toContain('#app .app-layout-content .admin-dashboard-atelier .dashboard-filter-card:hover .dashboard-filter-refresh')
    expect(dashboardSource).toContain('background: var(--atelier-butter) !important;')
    expect(dashboardSource).toContain('background: var(--atelier-ink) !important;')
    expect(dashboardSource).toContain('color: var(--atelier-paper) !important;')
    expect(dashboardSource).toContain('handleDashboardFilterPointerDown')
    expect(dashboardSource).toContain('dashboard-filter-menu-open')
    expect(dashboardSource).not.toContain('dashboard-chart-card')
    expect(styleSource).toContain('body.dashboard-filter-menu-open :where(.date-picker-dropdown-portal, .select-dropdown-portal)')
    expect(dashboardSource).toContain('.admin-dashboard-atelier :deep(.card)::before')
    expect(dashboardSource).toContain('.admin-dashboard-atelier > .grid > .card::after')
    expect(opsDashboardHeaderSource.match(/ops-metric-card/g)?.length).toBe(6)
    expect(opsDashboardHeaderSource.match(/ops-system-card/g)?.length).toBe(6)
    expect(globalPricingSource).toContain('summary-tile admin-material-surface')
    expect(globalPricingSource).toContain('table-wrapper admin-material-surface')
    expect(codexThemeSource).toContain('.codex-panel')
    expect(codexThemeSource).toContain('.codex-account-card')

    expect(materialSystemBlock).toContain('--atelier-card-surface: var(--atelier-paper-2);')
    expect(materialSystemBlock).toContain('background: var(--atelier-card-surface, var(--atelier-paper-2)) !important;')
    expect(materialSystemBlock).toContain('.app-layout-content :where(.ops-metric-card, .ops-system-card)')
    expect(materialSystemBlock).toContain('background: var(--atelier-paper-2) !important;')
    expect(materialSystemBlock).toContain('transform: translate3d(0, -2px, 0);')
    expect(materialSystemBlock).toContain('background: var(--atelier-butter) !important;')
    expect(materialSystemBlock).not.toContain('--atelier-card-rail')
    expect(materialSystemBlock).toContain('background: var(--atelier-console-rule);')
    expect(styleSource).toContain('--atelier-console-rule: repeating-linear-gradient(to right, var(--atelier-line-strong), var(--atelier-line-strong) 2px, transparent 2px, transparent 8px);')
    expect(materialSystemBlock).toContain('.ops-monitor-toolbar)::before')
    expect(materialSystemBlock).toContain('.admin-dashboard-atelier :where(.card, .paper-card')
    expect(materialSystemBlock).toContain('.user-usage-atelier :where(.card, .paper-card')
  })

  it('adapts the ops monitoring page to the dashboard module style without moving existing modules', () => {
    expect(opsDashboardSource).toContain('ops-dashboard-atelier space-y-6 pb-12')
    expect(opsDashboardSource).toContain('<OpsDashboardHeader')
    expect(opsDashboardSource).toContain('<OpsConcurrencyCard')
    expect(opsDashboardSource).toContain('<OpsSwitchRateTrendChart')
    expect(opsDashboardSource).toContain('<OpsThroughputTrendChart')
    expect(opsDashboardSource).toContain('<OpsLatencyChart')
    expect(opsDashboardSource).toContain('<OpsErrorDistributionChart')
    expect(opsDashboardSource).toContain('<OpsErrorTrendChart')
    expect(opsDashboardSource).toContain('<OpsAlertEventsCard')
    expect(opsDashboardSource).toContain('<OpsSystemLogTable')
    expect(opsDashboardSource).toContain('grid grid-cols-1 gap-6 lg:grid-cols-4')
    expect(opsDashboardSource).toContain('grid grid-cols-1 gap-6 md:grid-cols-3')

    expect(opsDashboardHeaderSource).toContain('ops-monitor-header')
    expect(opsDashboardHeaderSource).toContain('ops-monitor-toolbar')
    expect(opsDashboardHeaderSource).toContain('ops-monitor-toolbar-meta')
    expect(opsDashboardHeaderSource).toContain('ops-monitor-toolbar-controls')
    expect(opsDashboardHeaderSource).toContain('portal-class="ops-toolbar-select-menu"')
    expect(opsDashboardHeaderSource).toContain('ops-toolbar-icon-button')
    expect(opsDashboardHeaderSource).toContain('ops-toolbar-text-button')
    expect(opsDashboardHeaderSource).toContain('ops-live-panel')
    expect(opsDashboardHeaderSource).toContain('ops-live-grid')
    expect(opsDashboardHeaderSource).toContain('ops-health-score-card')
    expect(opsDashboardHeaderSource).toContain('ops-realtime-panel')
    expect(opsDashboardHeaderSource).toContain('ops-resource-band')
    expect(opsConcurrencySource).toContain('ops-monitor-panel ops-concurrency-card')
    expect(opsSwitchSource).toContain('ops-monitor-panel ops-chart-card ops-switch-card')
    expect(opsThroughputSource).toContain('ops-monitor-panel ops-chart-card ops-throughput-card')
    expect(opsLatencySource).toContain('ops-monitor-panel ops-chart-card ops-latency-card')
    expect(opsErrorDistributionSource).toContain('ops-monitor-panel ops-chart-card ops-error-distribution-card')
    expect(opsErrorTrendSource).toContain('ops-monitor-panel ops-chart-card ops-error-trend-card')
    expect(opsAlertEventsSource).toContain('ops-monitor-panel ops-alert-card')
    expect(opsSystemLogSource).toContain('ops-monitor-panel ops-log-card')

    expect(styleSource).toContain('.ops-dashboard-atelier')
    expect(styleSource).toContain('--ops-panel-surface: var(--atelier-paper);')
    expect(styleSource).toContain('--ops-card-surface: var(--atelier-paper-2);')
    expect(styleSource).toContain('--ops-card-edge: var(--atelier-line);')
    expect(styleSource).toContain('--ops-card-shadow: 0 10px 24px -22px var(--ops-module-shadow);')
    expect(styleSource).toContain('--atelier-card-surface: var(--ops-card-surface);')
    expect(styleSource).toContain('--atelier-material-2: var(--ops-card-surface);')
    expect(styleSource).toContain('--atelier-material-edge: var(--ops-card-edge);')
    expect(styleSource).toContain('--atelier-material-shadow: var(--ops-card-shadow);')
    expect(styleSource).toContain('border: 1px solid var(--ops-card-edge) !important;')
    expect(styleSource).toContain('border-bottom: 1px dotted var(--ops-line-strong) !important;')
    expect(styleSource).toContain('font-family: var(--atelier-font-mono)')
    expect(styleSource).toContain('font-family: var(--atelier-font-mono)')
    expect(styleSource).toContain('font-style: normal;')
    expect(styleSource).toContain('font-weight: 600 !important;')
    expect(styleSource).toContain('background: var(--ops-rule);')
    expect(styleSource).toContain('background: var(--atelier-butter) !important;')
    expect(styleSource).toContain('.app-layout-content .ops-dashboard-atelier .ops-realtime-panel button.bg-primary-500')
    expect(styleSource).toContain('background: var(--atelier-blue) !important;')
    expect(styleSource).toContain('color: var(--atelier-white) !important;')
    expect(styleSource).toContain('.ops-dashboard-atelier :where(.ops-health-score-card, .ops-realtime-panel)')
    expect(styleSource).toContain('border: 0 !important;')
    expect(styleSource).toContain('box-shadow: none !important;')
    expect(styleSource).toContain('.ops-diagnosis-popover')
    expect(styleSource).toContain('z-index: 100000200 !important;')
    expect(styleSource).toContain('#app .app-layout-content .ops-dashboard-atelier :where(.ops-monitor-header, .ops-monitor-header > .grid, .ops-live-panel, .ops-live-grid, .ops-health-score-card)')
    expect(styleSource).toContain('#app .app-layout-content .ops-dashboard-atelier .ops-realtime-panel')
    expect(styleSource).toContain('#app .app-layout-content .ops-dashboard-atelier .ops-live-panel:has(.ops-health-score-card:hover)')
    expect(styleSource).toContain('.ops-health-score-card:hover .ops-diagnosis-popover')
    expect(styleSource).toContain('.ops-diagnosis-popover > div')
    expect(styleSource).toContain('background-color: var(--atelier-ink) !important;')
    expect(styleSource).toContain('#app .app-layout-content .ops-dashboard-atelier .ops-diagnosis-popover *')
    expect(styleSource).toContain('-webkit-text-fill-color: var(--atelier-paper) !important;')
    expect(styleSource).toContain('.ops-diagnosis-popover :where(svg, path)')
    expect(styleSource).toContain('fill: currentColor !important;')
    expect(styleSource).toContain('.ops-dashboard-atelier .ops-realtime-panel .h-8.w-full.overflow-hidden')
    expect(styleSource).toContain('display: none !important;')
    expect(styleSource).toContain('.app-layout-content .ops-dashboard-atelier .ops-monitor-header .ops-metric-card:hover')
    expect(styleSource).toContain('#app .app-layout-content .ops-dashboard-atelier .ops-monitor-header')
    expect(styleSource).toContain('background: var(--ops-panel-surface) !important;')
    expect(styleSource).toContain('#app .app-layout-content .ops-dashboard-atelier .ops-live-panel')
    expect(styleSource).toContain('#app .app-layout-content .ops-dashboard-atelier .ops-health-score-card')
    expect(styleSource).toContain('background: var(--ops-card-surface) !important;')
    expect(styleSource).toContain('#app .app-layout-content .ops-dashboard-atelier .ops-monitor-toolbar')
    expect(styleSource).toContain('.ops-monitor-toolbar-meta')
    expect(styleSource).toContain('background: var(--atelier-ink) !important;')
    expect(styleSource).toContain('.ops-monitor-toolbar:hover .ops-monitor-toolbar-meta')
    expect(styleSource).not.toContain('.ops-monitor-header:hover .ops-monitor-toolbar-meta')
    expect(styleSource).toContain('.ops-monitor-toolbar-meta :where(h1, div, span, svg)')
    expect(styleSource).toContain('-webkit-text-fill-color: var(--atelier-paper) !important;')
    expect(styleSource).toContain('.ops-monitor-toolbar-controls')
    expect(styleSource).toContain('.ops-toolbar-icon-button')
    expect(styleSource).toContain('.ops-toolbar-text-button')
    expect(styleSource).toContain('.select-dropdown-portal.ops-toolbar-select-menu')
    expect(styleSource).toContain('background: var(--atelier-ink) !important;')
    expect(styleSource).toContain('--atelier-material-2: var(--atelier-butter);')
    expect(styleSource).toContain('background-color: var(--atelier-butter) !important;')
    expect(styleSource).toContain('.ops-dashboard-atelier .ops-monitor-header :where(.ops-metric-card, .ops-system-card)')
    expect(styleSource).toContain('.ops-dashboard-atelier :where(.ops-monitor-panel, .ops-metric-card, .ops-system-card):hover')
    expect(styleSource).not.toContain('--ops-paper-3: #fbf8f0;')
    expect(styleSource).not.toContain('background: #fbf8f0 !important;')
    expect(styleSource).not.toContain('border: 1px solid var(--ops-ink) !important;')

    expect(opsSwitchSource).toContain("dust: '#4f6a8c'")
    expect(opsSwitchSource).toContain("dustAlpha: '#4f6a8c26'")
    expect(opsSwitchSource).not.toContain('#14b8a6')
    expect(opsThroughputSource).toContain("butter: '#c79a3a'")
    expect(opsThroughputSource).toContain("butterAlpha: '#c79a3a26'")
    expect(opsThroughputSource).not.toContain('#10b981')
    expect(opsErrorDistributionSource).toContain("red: '#b44536'")
    expect(opsErrorDistributionSource).toContain("dust: '#4f6a8c'")
    expect(opsErrorDistributionSource).not.toContain('#f59e0b')
    expect(opsErrorTrendSource).toContain("butter: '#c79a3a'")
    expect(opsErrorTrendSource).toContain("dust: '#4f6a8c'")
    expect(opsErrorTrendSource).not.toContain('#ef4444')
  })

  it('themes console tables, inputs, and teleported menus as opaque atelier paper surfaces', () => {
    expect(tablePageLayoutSource).toContain('class="table-page-layout"')
    expect(tablePageLayoutSource).toContain('class="layout-section-fixed table-page-actions-section"')
    expect(tablePageLayoutSource).toContain('class="layout-section-fixed table-page-filter-section"')
    expect(tablePageLayoutSource).toContain('class="layout-section-fixed table-page-pagination-section"')
    expect(tablePageLayoutSource).toContain('class="card table-scroll-container"')
    expect(materialSystemBlock).toContain('background: var(--atelier-paper-2) !important;')
    expect(materialSystemBlock).toContain('border-bottom: 1px solid var(--atelier-material-edge) !important;')
    expect(materialSystemBlock).toContain('background: var(--atelier-paper-2) !important;')
    expect(materialSystemBlock).toContain('background: var(--atelier-butter) !important;')
    expect(materialSystemBlock).toContain('border-top: 1px dotted var(--atelier-material-edge) !important;')
    expect(materialSystemBlock).toContain('Console-wide parity for pages that do not use the dashboard/ops hooks.')
    expect(materialSystemBlock).toContain('.app-layout-content .table-page-layout > .layout-section-fixed')
    expect(materialSystemBlock).toContain('table-page-filter-section')
    expect(usersSource).toContain('users-filter-shell')
    expect(usersSource).toContain('users-filter-actions')
    expect(usersSource).toContain('users-filter-create btn btn-primary')
    expect(usersSource).toContain("value === 'active' ? 'status-dot-active' : 'status-dot-disabled'")
    expect(usersSource).not.toContain("value === 'active' ? 'bg-green-500' : 'bg-red-500'")
    expect(materialSystemBlock).toContain('.app-layout-content :where(.status-dot-active)')
    expect(materialSystemBlock).toContain('background: var(--atelier-blue) !important;')
    expect(materialSystemBlock).toContain('.layout-section-fixed.table-page-filter-section :where(.btn-primary, .users-filter-create)')
    expect(materialSystemBlock).toContain('border-image: none !important;')
    expect(materialSystemBlock).toContain('overflow: hidden;')
    expect(materialSystemBlock).toContain('.users-filter-create::before')
    expect(materialSystemBlock).toContain('.users-filter-create::before')
    expect(materialSystemBlock).toContain('content: none;')
    expect(accountTableFiltersSource).toContain('table-filter-left flex flex-wrap items-center gap-3')
    expect(accountTableActionsSource).toContain('table-filter-actions flex flex-wrap items-center gap-3')
    expect(groupsSource).toContain('table-filter-left flex flex-1 flex-wrap items-center gap-3')
    expect(groupsSource).toContain('table-filter-actions flex w-full flex-shrink-0')
    expect(channelsSource).toContain('table-filter-left flex flex-1 flex-wrap items-center gap-3')
    expect(channelsSource).toContain('table-filter-actions flex w-full flex-shrink-0')
    expect(proxiesSource).toContain('table-filter-left flex flex-1 flex-wrap items-center gap-3')
    expect(proxiesSource).toContain('table-filter-search relative w-full sm:w-64')
    expect(proxiesSource).toContain('table-filter-actions flex w-full flex-shrink-0')
    expect(monitorFiltersBarSource).toContain('table-filter-left flex flex-1 flex-wrap items-center gap-3')
    expect(monitorFiltersBarSource).toContain('table-filter-actions flex w-full flex-shrink-0')
    expect(adminUsageFiltersSource).toContain('usage-filter-card')
    expect(adminUsageFiltersSource).toContain('usage-filter-shell')
    expect(adminUsageFiltersSource).toContain('usage-filter-left')
    expect(adminUsageFiltersSource).toContain('usage-filter-actions')
    expect(userUsageSource).toContain('card usage-filter-card')
    expect(userUsageSource).toContain('usage-filter-shell')
    expect(userUsageSource).toContain('usage-filter-left')
    expect(userUsageSource).toContain('usage-filter-actions')
    expect(materialSystemBlock).toContain('.app-layout-content .table-page-layout > .layout-section-fixed.table-page-filter-section > :where(.flex-wrap, .flex-wrap-reverse, .justify-between, .users-filter-shell)')
    expect(materialSystemBlock).toContain('background: var(--atelier-ink) !important;')
    expect(materialSystemBlock).toContain(':where(.usage-filter-left, .users-filter-left, .table-filter-left)')
    expect(materialSystemBlock).toContain(':where(.usage-filter-actions, .users-filter-actions, .table-filter-actions)')
    expect(materialSystemBlock).toContain('.layout-section-fixed.table-page-filter-section > .flex-col')
    expect(materialSystemBlock).toContain('.layout-section-fixed.table-page-filter-section > .flex-col > :first-child')
    expect(materialSystemBlock).toContain('.layout-section-fixed.table-page-filter-section > .flex-col > :last-child')
    expect(materialSystemBlock).toContain('margin: -1rem 0 -1rem -1rem;')
    expect(materialSystemBlock).toContain('margin: -1rem -1rem -1rem 0;')
    expect(materialSystemBlock).toContain('> :not(:last-child) :where(.select-trigger, .date-picker-trigger, input[type="date"], input[type="search"], input[type="text"].input, .input)')
    expect(materialSystemBlock).toContain('border-color: var(--atelier-ink) !important;')
    expect(materialSystemBlock).toContain('outline: 1px solid rgba(255, 250, 240, 0.42) !important;')
    expect(materialSystemBlock).toContain('background: var(--atelier-ink) !important;')
    expect(materialSystemBlock).toContain('color: var(--atelier-paper) !important;')
    expect(materialSystemBlock).toContain(':where(.usage-filter-actions, .users-filter-actions, .table-filter-actions)::before')
    expect(materialSystemBlock).toContain('left: 0;')
    expect(materialSystemBlock).toContain('background: var(--atelier-console-rule-vertical-invert);')
    expect(materialSystemBlock).toContain('border-color: var(--atelier-ink) !important;')
    expect(materialSystemBlock).toContain('color: var(--atelier-paper) !important;')
    expect(materialSystemBlock).toContain('.layout-section-fixed.table-page-filter-section .relative > svg.absolute')
    expect(materialSystemBlock).toContain('left: 0.75rem !important;')
    expect(materialSystemBlock).toContain('input.input.pl-10')
    expect(materialSystemBlock).toContain('.layout-section-fixed.table-page-filter-section .table-filter-search')
    expect(materialSystemBlock).toContain('.table-filter-search > input.input.pl-10')
    expect(materialSystemBlock).toContain('box-sizing: border-box;')
    expect(accountsSource).toContain('class="accounts-table-page"')
    expect(materialSystemBlock).toContain('.table-page-layout.accounts-table-page > .layout-section-fixed.table-page-filter-section')
    expect(materialSystemBlock).toContain('.table-page-layout.accounts-table-page > .layout-section-fixed.table-page-filter-section :where(.table-filter-left, .table-filter-actions)')
    expect(materialSystemBlock).toContain('border-color: var(--atelier-material-edge) !important;')
    expect(materialSystemBlock).toContain('background: var(--atelier-paper) !important;')
    expect(materialSystemBlock).toContain('content: none !important;')
    expect(tablePageLayoutSource).toContain('table-page-pagination-section')
    expect(materialSystemBlock).toContain('border: 1px solid var(--atelier-material-edge) !important;')
    expect(materialSystemBlock).toContain('background: var(--atelier-ink) !important;')
    expect(materialSystemBlock).toContain('color: var(--atelier-paper) !important;')
    expect(materialSystemBlock).toContain('.pagination-shell')
    expect(materialSystemBlock).toContain('box-shadow: inset 0 -2px 0 var(--atelier-lime) !important;')
    expect(materialSystemBlock).toContain('.table-page-pagination-section')
    expect(materialSystemBlock).toContain('.layout-section-fixed.table-page-pagination-section :where(button[aria-current="page"])')
    expect(materialSystemBlock).toContain('body:has(.table-page-layout) :where(.select-dropdown-portal, .date-picker-dropdown-portal)')
    expect(materialSystemBlock).toContain('button[aria-selected="true"]')
    expect(materialSystemBlock).toContain('background: var(--atelier-blue) !important;')
    expect(materialSystemBlock).toContain('font-variant-numeric: tabular-nums;')
    expect(materialSystemBlock).toContain('tbody tr:hover :where(td, .sticky-col, .table-cell)')
    expect(materialSystemBlock).toContain(':where(.admin-dashboard-atelier, .ops-dashboard-atelier, .admin-usage-atelier, .user-usage-atelier) :where(.table-wrapper, .table-scroll-container) tbody tr:hover')
    expect(materialSystemBlock).toContain('#app .app-layout-content :where(.admin-dashboard-atelier, .ops-dashboard-atelier, .admin-usage-atelier, .user-usage-atelier) :where(.card, .paper-card, .stat-card, .summary-tile, .admin-material-surface, .ops-monitor-panel, .ops-metric-card, .ops-system-card):hover')
    expect(materialSystemBlock).toContain('#app .app-layout-content .ops-dashboard-atelier .ops-monitor-header:hover')
    expect(materialSystemBlock).toContain('.ops-monitor-header:hover :where(.ops-metric-card, .ops-system-card, .ops-health-score-card, .ops-realtime-panel):not(:hover)')
    expect(materialSystemBlock).toContain('.ops-monitor-header:hover :where(.ops-metric-card, .ops-system-card):not(:hover) :where(.text-3xl, .text-4xl, .text-5xl, .text-lg, .text-xl, .text-2xl, .font-black, .font-bold, .text-primary-500, .text-primary-600, .text-primary-700, .text-blue-500, .text-blue-600, .text-red-500, .text-red-600, .text-rose-500, .text-rose-600)')
    expect(materialSystemBlock).toContain(':where(.ops-monitor-header, .ops-live-panel) :where(.ops-metric-card, .ops-system-card):hover :where(.text-3xl, .text-4xl, .text-5xl, .text-lg, .text-xl, .text-2xl, .font-black, .font-bold, .text-primary-500, .text-primary-600, .text-primary-700, .text-blue-500, .text-blue-600, .text-red-500, .text-red-600, .text-rose-500, .text-rose-600)')
    expect(materialSystemBlock).toContain(':where(.ops-monitor-header, .ops-live-panel) :where(.ops-metric-card, .ops-system-card) :where([class~="h-2"][class~="w-full"][class~="overflow-hidden"])')
    expect(materialSystemBlock).toContain('.floating-dropdown-portal')
    expect(materialSystemBlock).toContain('.select-dropdown-portal')
    expect(selectSource).toContain('portalClass?: string')
    expect(selectSource).toContain(':class="[instanceId, portalClass]"')
    expect(materialSystemBlock).toContain('.date-picker-dropdown-portal')
    expect(materialSystemBlock).toContain('body.dashboard-filter-menu-open .date-picker-dropdown-portal .date-picker-presets')
    expect(materialSystemBlock).toContain('.date-picker-dropdown-portal .date-picker-preset-active:hover')
    expect(materialSystemBlock).toContain('body:has(.table-page-layout) .date-picker-dropdown-portal :where(.date-picker-input)')
    expect(materialSystemBlock).toContain('body:has(.table-page-layout) .date-picker-dropdown-portal :where(.date-picker-preset:hover, .date-picker-preset-active, .date-picker-preset-active:hover, .date-picker-apply, .date-picker-apply:hover)')
    expect(materialSystemBlock).toContain('body:has(.admin-usage-atelier) .date-picker-dropdown-portal')
    expect(materialSystemBlock).toContain('body:has(.admin-usage-atelier) .date-picker-dropdown-portal :where(.date-picker-input)')
    expect(materialSystemBlock).toContain('body:has(.admin-usage-atelier) .date-picker-dropdown-portal :where(.date-picker-preset:hover, .date-picker-preset-active, .date-picker-preset-active:hover, .date-picker-apply, .date-picker-apply:hover)')
    expect(materialSystemBlock).not.toContain('.dropdown {\n  background: transparent !important;')
  })

  it('keeps the latest filter split, account cards, quota bars, and settings nav palette hooks', () => {
    expect(accountsSource).toContain('accounts-filter-shell flex flex-wrap-reverse')
    expect(accountsSource).toContain('account-card-table-frame flex min-h-fit flex-none flex-col overflow-visible')
    expect(accountsSource).toContain(':lenis-scroll="false"')
    expect(adminUsageSource).toContain('usage-record-filter-wrap')
    expect(materialSystemBlock).toContain('> :where(.flex-wrap, .flex-wrap-reverse, .flex-col, .users-filter-shell, .accounts-filter-shell, .table-filter-shell)')
    expect(materialSystemBlock).toContain('> :where(.ml-auto, .table-filter-actions, .users-filter-actions, .usage-filter-actions)::before')
    expect(materialSystemBlock).toContain('Current visual iteration: precise split filters, account cards, and settings tabs.')
    expect(materialSystemBlock).toContain('.admin-dashboard-atelier .dashboard-filter-card > div > .dashboard-filter-refresh::after')
    expect(materialSystemBlock).toContain('right: 0 !important;')
    expect(materialSystemBlock).toContain('.admin-usage-atelier .usage-time-filter-card')
    expect(materialSystemBlock).toContain('.admin-usage-atelier .usage-time-filter-granularity::before')
    expect(materialSystemBlock).toContain('.admin-usage-atelier .usage-record-filter-wrap')
    expect(adminUsageStatsCardsSource).toContain('usage-stats-grid grid grid-cols-2 gap-4 lg:grid-cols-4')
    expect(adminUsageStatsCardsSource.match(/card usage-stat-card p-4/g)?.length).toBe(4)
    expect(adminUsageStatsCardsSource.match(/usage-stat-icon rounded-lg/g)?.length).toBe(4)
    expect(materialSystemBlock).toContain(':where(.admin-usage-atelier, .user-usage-atelier) .usage-stat-card')
    expect(materialSystemBlock).toContain(':where(.admin-usage-atelier, .user-usage-atelier) .usage-stat-icon')
    expect(materialSystemBlock).toContain(':where(.admin-usage-atelier, .user-usage-atelier) .usage-stat-card :where(.text-xl)')
    expect(materialSystemBlock).toContain('.user-usage-atelier > .table-page-actions-section .card:hover')
    expect(materialSystemBlock).toContain(':where(.admin-usage-atelier, .user-usage-atelier) .usage-stat-card:hover')
    expect(materialSystemBlock).toContain('.admin-usage-atelier .usage-time-filter-granularity .select-trigger')

    expect(materialSystemBlock).toContain('.accounts-table-page .table-wrapper tbody')
    expect(materialSystemBlock).toContain('.accounts-table-page .table-wrapper tbody.table-body')
    expect(materialSystemBlock).toContain('border-top: 0 !important;')
    expect(materialSystemBlock).toContain('grid-template-columns: repeat(auto-fill, minmax(min(100%, 340px), 1fr));')
    expect(materialSystemBlock).toContain('grid-template-columns: repeat(3, minmax(0, 1fr));')
    expect(materialSystemBlock).toContain('padding-right: 3rem !important;')
    expect(materialSystemBlock).toContain('td[data-column-key="usage"]')
    expect(materialSystemBlock).toContain('width: max-content !important;')
    expect(materialSystemBlock).toContain('grid-column: span 2;')
    expect(materialSystemBlock).toContain('td[data-column-key="schedulable"] button.relative.inline-flex')
    expect(materialSystemBlock).toContain('td[data-column-key="schedulable"] button.relative.inline-flex.bg-gray-200')
    expect(materialSystemBlock).toContain('td[data-column-key="schedulable"] button.relative.inline-flex > span')
    expect(materialSystemBlock).toContain('.accounts-table-page .table-wrapper tbody tr > td::before')
    expect(materialSystemBlock).toContain('content: attr(data-column-label);')
    expect(materialSystemBlock).toContain('.accounts-table-page .usage-progress-bar')
    expect(materialSystemBlock).toContain('.accounts-table-page .usage-progress-track')
    expect(materialSystemBlock).toContain('background: var(--atelier-white) !important;')
    expect(materialSystemBlock).toContain('.usage-progress-fill--safe')
    expect(materialSystemBlock).toContain('background: var(--atelier-green) !important;')
    expect(materialSystemBlock).toContain('.usage-progress-fill--warning')
    expect(materialSystemBlock).toContain('background: var(--atelier-butter) !important;')
    expect(materialSystemBlock).toContain('.usage-progress-fill--danger')
    expect(materialSystemBlock).toContain('background: var(--atelier-red) !important;')
    expect(usageProgressBarSource).toContain('class="usage-progress-bar"')
    expect(usageProgressBarSource).toContain('usage-progress-window-stats')
    expect(usageProgressBarSource).toContain('usage-progress-row')
    expect(usageProgressBarSource).toContain('usage-progress-track')
    expect(usageProgressBarSource).toContain('usage-progress-fill--safe bg-green-500')
    expect(usageProgressBarSource).toContain('usage-progress-fill--warning bg-amber-500')
    expect(usageProgressBarSource).toContain('usage-progress-fill--danger bg-red-500')

    expect(settingsSource).toContain('settings-tab-icon')
    expect(materialSystemBlock).toContain('.app-layout-content .settings-tab::before')
    expect(materialSystemBlock).toContain('background: var(--atelier-butter) !important;')
    expect(materialSystemBlock).toContain('.app-layout-content .settings-tab-active .settings-tab-icon')
    expect(materialSystemBlock).toContain('background: var(--atelier-blue) !important;')
  })

  it('applies the latest user account, pricing, auth, and theme iteration hooks', () => {
    expect(userKeysSource).toContain('class="user-keys-atelier"')
    expect(userKeysSource).toContain('keys-filter-shell')
    expect(userKeysSource).toContain('keys-filter-left')
    expect(userKeysSource).toContain('keys-filter-actions')
    expect(endpointPopoverSource).toContain('endpoint-popover-list')
    expect(endpointPopoverSource).toContain('endpoint-popover-item')
    expect(endpointPopoverSource).toContain('endpoint-default-badge')
    expect(endpointPopoverSource).toContain('endpoint-tooltip')
    expect(endpointPopoverSource).toContain('endpoint-code')
    expect(materialSystemBlock).toContain('.user-keys-atelier .keys-filter-shell')
    expect(materialSystemBlock).toContain('grid-template-columns: minmax(0, 1fr) minmax(18rem, auto);')
    expect(materialSystemBlock).toContain('.user-keys-atelier .keys-filter-actions::before')
    expect(materialSystemBlock).toContain('.user-keys-atelier .endpoint-popover-list')
    expect(materialSystemBlock).toContain('.user-keys-atelier .endpoint-popover-list .endpoint-popover-item')
    expect(materialSystemBlock).toContain('.user-keys-atelier .endpoint-popover-list .endpoint-default-badge')
    expect(materialSystemBlock).toContain('.user-keys-atelier .endpoint-popover-list .endpoint-tooltip')
    expect(materialSystemBlock).toContain('background-color: var(--atelier-ink) !important;')

    for (const source of [announcementsSource, redeemSource, promoCodesSource]) {
      expect(source).toContain('table-filter-shell flex flex-wrap items-center gap-3')
      expect(source).toContain('table-filter-left flex flex-1 flex-wrap items-center gap-3')
      expect(source).toContain('table-filter-search flex-1')
      expect(source).toContain('table-filter-actions flex w-full flex-shrink-0')
    }
    expect(materialSystemBlock).toContain('> :where(.flex-wrap, .flex-wrap-reverse, .flex-col, .users-filter-shell, .accounts-filter-shell, .table-filter-shell)')

    expect(userUsageSource).toContain('class="user-usage-atelier" scroll-mode="page"')
    expect(userUsageSource).toContain('usage-stats-grid grid grid-cols-2 gap-4 lg:grid-cols-4')
    expect(userUsageSource.match(/card usage-stat-card p-4/g)?.length).toBe(4)
    expect(userUsageSource.match(/usage-stat-icon rounded-lg/g)?.length).toBe(4)
    expect(userUsageSource).toContain('vertical-scroll-mode="page"')
    expect(userUsageSource).toContain(':lenis-scroll="false"')
    expect(materialSystemBlock).toContain('.user-usage-atelier > .table-page-actions-section')
    expect(materialSystemBlock).toContain(':where(.admin-usage-atelier, .user-usage-atelier) .usage-stat-card')
    expect(materialSystemBlock).toContain(':where(.admin-usage-atelier, .user-usage-atelier) .usage-stat-card::before')
    expect(materialSystemBlock).toContain(':where(.admin-usage-atelier, .user-usage-atelier) .usage-stat-card::after')
    expect(materialSystemBlock).toContain(':where(.admin-usage-atelier, .user-usage-atelier) .usage-stat-card:nth-child(2n)::after')
    expect(materialSystemBlock).toContain(':where(.admin-usage-atelier, .user-usage-atelier) .usage-stat-card:nth-child(3n)::after')
    expect(materialSystemBlock).toContain(':where(.admin-usage-atelier, .user-usage-atelier) .usage-stat-icon')
    expect(materialSystemBlock).toContain(':where(.admin-usage-atelier, .user-usage-atelier) .usage-stat-card :where(.text-xl)')
    expect(materialSystemBlock).toContain('.user-usage-atelier .usage-filter-shell')
    expect(materialSystemBlock).toContain('.user-usage-atelier .usage-filter-shell {\n  display: grid !important;\n  grid-template-columns: minmax(0, 1fr) auto;')
    expect(materialSystemBlock).toContain('.user-usage-atelier .usage-filter-shell {\n  display: grid !important;\n  grid-template-columns: minmax(0, 1fr) auto;\n  gap: 0 !important;\n  align-items: stretch !important;\n  min-height: 3.25rem;\n  margin: 0 !important;\n  padding: 0 !important;\n  background: var(--atelier-butter) !important;')
    expect(materialSystemBlock).toContain('.user-usage-atelier .usage-filter-left {\n  align-self: stretch !important;\n  position: relative !important;')
    expect(materialSystemBlock).toContain('.user-usage-atelier .usage-filter-left {\n  align-self: stretch !important;\n  position: relative !important;\n  z-index: 0;\n  margin: 0 !important;\n  padding: 1rem !important;\n  background: var(--atelier-ink) !important;')
    expect(materialSystemBlock).toContain('.user-usage-atelier .table-wrapper.is-page-scroll')
    expect(materialSystemBlock).toContain('.user-usage-atelier .table-scroll-container {\n  max-width: 100% !important;\n  overflow: hidden !important;')
    expect(materialSystemBlock).toContain('.user-usage-atelier .table-scroll-container:hover {\n  --atelier-card-surface: var(--atelier-paper-2);')
    expect(materialSystemBlock).toContain('.user-usage-atelier .table-wrapper.is-page-scroll {\n  width: 100% !important;\n  max-width: 100% !important;\n  overflow-x: auto !important;\n  overflow-y: visible !important;')

    expect(globalPricingSource).toContain('class="global-pricing-atelier" scroll-mode="page"')
    expect(globalPricingSource).toContain('global-pricing-summary-row')
    expect(globalPricingSource).toContain('global-pricing-filter-card')
    expect(globalPricingSource).toContain('global-pricing-filter-shell')
    expect(globalPricingSource).toContain('global-pricing-card-frame')
    expect(globalPricingSource).toContain('global-pricing-card-body')
    expect(globalPricingSource).toContain(':data-card-label="t(\'globalPricing.columns.model\')"')
    expect(materialSystemBlock).toContain('.global-pricing-summary-row .summary-tile:hover')
    expect(materialSystemBlock).toContain('.global-pricing-atelier .global-pricing-summary-row .summary-tile:hover')
    expect(materialSystemBlock).toContain('.global-pricing-card-frame .global-pricing-card-body')
    expect(materialSystemBlock).toContain('.global-pricing-card-frame .pricing-row')
    expect(materialSystemBlock).toContain('content: attr(data-card-label);')

    expect(appSidebarSource).not.toContain('toggleTheme')
    expect(appSidebarSource).not.toContain('MoonIcon')
    expect(appSidebarSource).not.toContain('SunIcon')
    expect(homeSource).not.toContain('toggleTheme')
    expect(keyUsageSource).not.toContain('toggleTheme')
    expect(styleSource).toContain('.auth-ascii-shell .paper-card')
    expect(styleSource).toContain('.home-ascii-shell .home-provider-logo-mark .provider-brand-icon')
  })

  it('keeps CPA/Codex panels on the same module palette without moving their layout', () => {
    expect(codexThemeSource).toContain('--codex-module-rule: var(--atelier-console-rule);')
    expect(codexThemeSource).toContain('border-bottom: 1px dotted var(--codex-border-strong);')
    expect(codexThemeSource).toContain('box-shadow: 0 10px 24px -22px var(--material-card-shadow);')
    expect(codexThemeSource).not.toContain('inset 4px 0 0 var(--codex-accent)')
    expect(codexThemeSource).not.toContain('grid-template-columns: minmax(0, 1fr) 420px;')
    expect(codexThemeSource).toContain('grid-template-columns: minmax(0, 1fr) 360px;')
  })

  it('keeps platform logos brand colored inside themed select dropdowns', () => {
    expect(platformIconSource).toContain('platformIconClass')
    expect(platformIconSource).toContain("'platform-icon'")
    expect(platformIconSource).toContain('platform-icon--openai')
    expect(platformIconSource).toContain('platform-icon--anthropic')
    expect(platformIconSource).toContain('platform-icon--gemini')
    expect(platformIconSource).toContain('platform-icon--antigravity')
    expect(styleSource).toContain('.select-dropdown-portal .platform-icon')
    expect(styleSource).toContain('color: var(--platform-icon-color, currentColor) !important;')
    expect(styleSource).toContain('body .select-dropdown-portal.ops-toolbar-select-menu .platform-icon')
    expect(styleSource).toContain('.platform-icon--openai')
    expect(styleSource).toContain('.platform-icon--anthropic')
  })
})
