import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

const frontendRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const readFile = (file: string) => readFileSync(resolve(frontendRoot, file), 'utf8')
const fileExists = (file: string) => existsSync(resolve(frontendRoot, file))

describe('home CTA BorderGlow integration', () => {
  it('wraps the home console CTA with the BorderGlow effect', () => {
    const home = readFile('src/views/HomeView.vue')

    expect(home).toContain("import BorderGlow from '@/components/home/BorderGlow.vue'")
    expect(home).toContain('<BorderGlow')
    expect(home).toContain('class="home-cta-glow"')
    expect(home).toContain(':edge-sensitivity="38"')
    expect(home).toContain('glow-color="32 96 69"')
    expect(home).toContain('background-color="#f6821f"')
    expect(home).toContain(':glow-radius="24"')
    expect(home).toContain(':glow-intensity="0.68"')
    expect(home).toContain(':cone-spread="12"')
    expect(home).toContain('animated')
    expect(home).toContain(':colors="[\'#f6821f\', \'#fbad41\', \'#fff4cf\']"')
    expect(home).toContain(':fill-opacity="0"')
    expect(home).toContain('class="home-cta inline-flex items-center rounded-lg px-8 py-3 text-base font-semibold shadow-glow transition-colors"')
    expect(home).toContain('.home-cta-glow :deep(.border-glow-card)')
    expect(home).toContain('border: 1px solid var(--atelier-ink);')
    expect(home).toContain('border: 0;')
    expect(home).toContain('background: transparent;')
    expect(home).toContain('box-shadow: 0 16px 36px -26px rgba(0, 47, 167, 0.78);')
    expect(home).toContain('box-shadow: none;')
    expect(home).toContain('box-shadow: 0 24px 44px -30px rgba(0, 47, 167, 0.9);')
    expect(home).not.toContain('border: 1px solid rgba(255, 250, 240, 0.32);')
    expect(home).not.toContain('rgba(246, 130, 31, 0.82)')
  })

  it('ports the pasted React Bits BorderGlow layers to Vue', () => {
    expect(fileExists('src/components/home/BorderGlow.vue')).toBe(true)

    const component = readFile('src/components/home/BorderGlow.vue')

    expect(component).toContain('class="border-glow-card"')
    expect(component).toContain('class="edge-light"')
    expect(component).toContain('@pointermove="handlePointerMove"')
    expect(component).toContain('card.style.setProperty(\'--edge-proximity\'')
    expect(component).toContain('card.style.setProperty(\'--cursor-angle\'')
    expect(component).toContain('function getCursorAngle')
    expect(component).toContain('function getEdgeProximity')
    expect(component).toContain('function animateValue')
    expect(component).toContain("card.classList.add('sweep-active')")
    expect(component).toContain("card.classList.remove('sweep-active')")
    expect(component).toContain('const angleStart = 110')
    expect(component).toContain('const angleEnd = 465')
    expect(component).toContain('--cone-spread: 25;')
    expect(component).toContain('border: 1px solid rgb(255 255 255 / 15%);')
    expect(component).toContain('background: var(--card-bg, #120F17);')
    expect(component).toContain('overflow: visible;')
    expect(component).toContain('.border-glow-card::before,')
    expect(component).toContain('.border-glow-card::after,')
    expect(component).toContain('.border-glow-card:not(:hover):not(.sweep-active)::before')
    expect(component).toContain('linear-gradient(var(--card-bg, #120F17) 0 100%) padding-box')
    expect(component).toContain('mask-image:')
    expect(component).toContain('conic-gradient(')
    expect(component).toContain('mask-composite: subtract, add, add, add, add, add;')
    expect(component).toContain('mix-blend-mode: soft-light;')
    expect(component).toContain('mix-blend-mode: plus-lighter;')
    expect(component).toContain('inset: calc(var(--glow-padding) * -1);')
    expect(component).toContain('inset: var(--glow-padding);')
    expect(component).toContain('.border-glow-inner')
    expect(component).toContain('overflow: auto;')
    expect(component).toContain('z-index: 1;')
    expect(component).not.toContain('class="sweep-light"')
    expect(component).not.toContain('linear-gradient(105deg')
    expect(component).not.toContain('transform: translate3d(var(--sweep-x), 0, 0) skewX(-18deg);')
    expect(component).not.toContain('--edge-width: 2px;')
    expect(component).not.toContain('linear-gradient(#000 0 0) content-box')
    expect(component).not.toContain('-webkit-mask-composite: xor;')
  })
})
