import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

const frontendRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const readFile = (file: string) => readFileSync(resolve(frontendRoot, file), 'utf8')

describe('home and auth contrast on Atelier structured color surfaces', () => {
  const cssBlock = (content: string, selector: string): string => {
    const start = content.indexOf(`${selector} {`)
    expect(start, `Expected CSS selector ${selector}`).toBeGreaterThanOrEqual(0)
    const end = content.indexOf('\n}', start)
    expect(end, `Expected CSS selector ${selector} to close`).toBeGreaterThan(start)
    return content.slice(start, end + 2)
  }

  it('uses static themed footer microcopy and links on auth pages', () => {
    const authLayout = readFile('src/components/layout/AuthLayout.vue')
    const style = readFile('src/style.css')

    expect(authLayout).toContain('auth-footer-link')
    expect(authLayout).toContain('color: var(--atelier-muted);')
    expect(authLayout).toContain('color: var(--atelier-blue);')
    expect(authLayout).not.toContain("import GuizangAsciiBackground from '@/components/common/GuizangAsciiBackground.vue'")
    expect(authLayout).not.toContain('<GuizangAsciiBackground tone="light" class="auth-ascii-background" />')
    expect(style).toContain('.auth-ascii-shell,')
    expect(style).toContain('.auth-ascii-shell .paper-card')
    expect(style).toContain('.auth-ascii-shell .text-gradient')
    expect(style).toContain('--atelier-canvas:')
    expect(style).toContain('--atelier-surface-panel:')
    expect(style).not.toContain('.auth-ascii-background')
  })

  it('keeps default home header and CTA readable on the ASCII background', () => {
    const home = readFile('src/views/HomeView.vue')
    const css = readFile('src/style.css')

    expect(home).toContain('<router-link to="/home" class="flex items-center" aria-label="Home">')
    expect(home).toContain('<LocaleSwitcher tone="on-deep" />')
    expect(home).toContain("import ProviderBrandIcon from '@/components/common/ProviderBrandIcon.vue'")
    expect(home).not.toContain("import PixelCard from '@/components/home/PixelCard.vue'")
    expect(home).not.toContain("import FluidGlassButton from '@/components/home/FluidGlassButton.vue'")
    expect(home).toContain('<ProviderBrandIcon provider="anthropic" model="claude" prefer-model-icon />')
    expect(home).toContain('<ProviderBrandIcon provider="openai" model="gpt" />')
    expect(home).toContain('<ProviderBrandIcon provider="gemini" model="gemini" />')
    expect(home).toContain('<ProviderBrandIcon provider="antigravity" model="antigravity" />')
    expect(home).toContain('<ProviderBrandIcon provider="codex" model="codex" />')
    expect(home).not.toContain('@click="toggleTheme"')
    expect(home).toContain('class="home-hero-subtitle mb-8 text-lg md:text-xl"')
    expect(home).toContain('class="home-cta inline-flex items-center rounded-lg px-8 py-3 text-base font-semibold transition-colors"')
    expect(home).toContain('background: var(--atelier-terracotta-action, #c96442);')
    expect(home).toContain('color: rgba(255, 250, 240, 0.9);')
    expect(home).toContain('color: var(--atelier-paper-2);')
    expect(home).not.toContain('class="btn btn-primary px-8 py-3 text-base"')
    expect(css).not.toContain('.home-ascii-shell .home-provider-logo-mark .provider-brand-icon svg')
  })

  it('applies Zero Landing style reveal motion to every visible home module', () => {
    const home = readFile('src/views/HomeView.vue')

    expect((home.match(/data-home-reveal/g) ?? []).length).toBeGreaterThanOrEqual(20)
    expect(home).not.toContain('data-home-module="topbar"')
    expect(home).toContain('data-home-module="nav"')
    expect(home).toContain('data-home-module="hero-label"')
    expect(home).toContain('data-home-module="hero-title"')
    expect(home).toContain('data-home-module="hero-lead"')
    expect(home).toContain('data-home-module="hero-copy"')
    expect(home).toContain('data-home-module="hero-cta"')
    expect(home).toContain('data-home-module="hero-index"')
    expect(home).toContain('data-home-module="terminal-console"')
    expect(home).not.toContain('data-home-module="terminal-plate"')
    expect(home).toContain('data-home-module="metric-ring"')
    expect(home).toContain('data-home-module="feature-section-label"')
    expect(home).toContain('data-home-module="provider-section-label"')
    expect(home).toContain('class="home-capability-kicker-item')
    expect(home).toContain('class="home-cap-card')
    expect(home).toContain('class="home-provider-specimen')
    expect(home).toContain('.home-ascii-shell .home-capability-kicker-item')
    expect(home).toContain('.home-ascii-shell .home-cap-card')
    expect(home).toContain('.home-ascii-shell .home-provider-specimen')
    expect(home).toContain('.home-ascii-shell [data-home-reveal]')
    expect(home).toContain('[data-home-reveal].is-visible')
    expect(home).toContain('transition-delay: var(--home-reveal-delay, 0ms);')
    expect(home).toContain('IntersectionObserver')
    expect(home).toContain('observer.observe(item)')
    expect(home).toContain('function markHomeRevealVisible(item: HTMLElement)')
    expect(home).toContain('item.classList.add(\'is-visible\')')
    expect(home).toContain('markHomeRevealVisible(entry.target as HTMLElement)')
    expect(home).toContain('function revealPassedHomeItems()')
    expect(home).toContain('item.getBoundingClientRect().top <= window.innerHeight * 1.18')
    expect(home).toContain("revealScrollElement?.addEventListener('scroll', scheduleRevealPassedHomeItems, { passive: true })")
    expect(home).toContain("revealScrollElement?.addEventListener('wheel', handleHomeWheel, { passive: false })")
    expect(home).toContain("revealScrollElement?.removeEventListener('scroll', scheduleRevealPassedHomeItems)")
    expect(home).toContain("revealScrollElement?.removeEventListener('wheel', handleHomeWheel)")
    expect(home).toContain('function handleHomeWheel(event: WheelEvent)')
    expect(home).toContain('snapWheelLocked')
    expect(home).toContain('function homeSnapTopForTarget(target: HTMLElement)')
    expect(home).toContain("root.scrollTo({ top: homeSnapTopForTarget(targets[nextIndex]), behavior: 'smooth' })")
    expect(home).toContain("rootMargin: '0px 0px 18% 0px'")
    expect(home).not.toContain('animation: home-component-reveal')
    expect(home).not.toContain('@keyframes home-component-reveal')
    expect(home).toContain('@media (prefers-reduced-motion: reduce)')
  })

  it('rebuilds the default home page with a visible DarkVeil hero and translucent modules', () => {
    const home = readFile('src/views/HomeView.vue')

    expect(home).toContain('.home-ascii-shell {')
    expect(home).toContain('height: 100vh;')
    expect(home).toContain('overflow-y: auto;')
    expect(home).toContain('scroll-snap-type: y mandatory;')
    expect(home).toContain('scroll-snap-align: start;')
    expect(home).toContain('scroll-snap-stop: always;')
    expect(home).toContain('.home-section {\n  position: relative;\n  max-width: var(--home-max);\n  margin: 0 auto;\n  height: 100vh;')
    expect(home).toContain('--home-surface-solid: var(--atelier-canvas);')
    expect(home).toContain('--home-surface-cool: var(--atelier-surface-cool);')
    expect(home).toContain('--home-surface-paper: var(--atelier-paper);')
    expect(home).toContain('--home-surface-paper-2: var(--atelier-paper-2);')
    expect(home).toContain('--home-surface-butter: color-mix(in srgb, var(--atelier-butter) 18%, var(--atelier-paper));')
    expect(home).toContain('--home-surface-ink: var(--atelier-ink);')
    expect(home).toContain('background: #07101e;')
    expect(home).toContain('background: var(--atelier-blue);')
    expect(home).toContain('background: var(--atelier-butter);')
    expect(home).toContain('background: rgba(7, 16, 30, 0.14);')
    expect(home).toContain('background: rgba(7, 16, 30, 0.13);')
    expect(home).toContain('background: rgba(7, 16, 30, 0.12);')
    expect(home).toContain('backdrop-filter: blur(12px) saturate(1.08);')
    expect(home).not.toContain('.home-ring::before')
    expect(home).not.toContain('.home-ring::after')
    expect(home).not.toContain('radial-gradient(circle at 28% 18%, rgba(255, 250, 240, 0.72), transparent 24%)')
    expect(home).not.toContain('backdrop-filter: blur(18px) saturate(1.32);')
    expect(home).toContain('background: linear-gradient(145deg, rgba(23, 21, 18, 0.92) 0%, rgba(5, 5, 5, 0.94) 100%);')
    expect(home).not.toContain('--home-card-accent: var(--atelier-butter);')
    expect(home).not.toContain('--home-chip-accent: var(--atelier-butter);')
    expect(home).not.toContain('background: var(--home-surface-butter);')
    expect(home).not.toContain('class="home-ascii-background"')
    expect(home).not.toContain('.home-ascii-background')
    expect(home).not.toContain('opacity: 0.035;')
    expect(home).toContain('.home-site-frame {')
    expect(home).toContain('background: transparent;')
    expect(home).toContain('background: var(--home-surface-dust);')
    expect(home).not.toContain('background: var(--home-surface-blue);')
    expect(home).not.toContain('--home-surface-butter: var(--atelier-surface-butter);')
    expect(home).not.toContain('linear-gradient(90deg, rgba(23, 21, 18, 0.035) 1px, transparent 1px)')
    expect(home).not.toContain('linear-gradient(0deg, rgba(23, 21, 18, 0.025) 1px, transparent 1px)')
    expect(home).not.toContain('rgba(23, 21, 18, 1)')
    expect(home).not.toContain('rgba(79, 106, 140, 0.34)')
    expect(home).not.toContain('.home-site-frame::before')
    expect(home).not.toContain('.home-site-frame::after')
    expect(home).not.toContain('color: rgba(243, 239, 229, 0.62)')
    expect(home).not.toContain('color: rgba(243, 239, 229, 0.54)')
    expect(home).not.toContain('opacity: 0.72;')
    expect(home).not.toContain('opacity: 0.78;')
    expect(home).not.toContain('opacity: 0.76;')
    expect(home).not.toContain('.home-topbar')
    expect(home).not.toContain('home-hero-scrim')
    expect(home).toContain('.home-section-label::after')
    expect(home).toContain('background: repeating-linear-gradient(to right, var(--atelier-line-strong), var(--atelier-line-strong) 2px, transparent 2px, transparent 8px);')
    expect(home).toContain('.home-hero-grid')
    expect(home).toContain('.home-terminal-stage')
    expect(home).not.toContain('.home-hero-plate')
    expect(home).not.toContain('.home-shape-arch')
    expect(home).not.toContain('.home-shape-disk')
    expect(home).not.toContain('.home-shape-leaf')
    expect(home).toContain('.home-index-row')
    expect(home).toContain('.home-ring')
    expect(home).toContain('.home-ascii-shell .home-cap-card-featured')
    expect(home).toContain('background: var(--atelier-blue);')
    expect(home).toContain('--home-card-accent: var(--atelier-dust);')
    expect(home).toContain('--home-card-accent: var(--atelier-blue);')
    expect(home).not.toContain('--home-card-accent: var(--atelier-butter);')
    expect(home).toContain('--home-card-surface: var(--home-surface-ink);')
    expect(home).toContain('border-top: 1px solid var(--atelier-ink);')
    expect(home).toContain('background: var(--home-card-surface);')
    expect(home).toContain('.home-ascii-shell .home-capability-kicker-item')
    expect(home).toContain('.home-ascii-shell .home-cap-card')
    expect(home).toContain('.home-ascii-shell .home-provider-specimen')
    expect(home).not.toContain('box-shadow: inset 8px 0 0 var(--home-chip-accent);')
    expect(home).not.toContain('box-shadow: inset 0 6px 0 var(--home-chip-accent);')
    expect(home).not.toContain('color-mix(in srgb, var(--home-card-accent) 14%, var(--atelier-paper))')
    expect(home).not.toContain('color-mix(in srgb, var(--home-chip-accent) 8%, var(--atelier-paper))')
    expect(home).not.toContain('linear-gradient(90deg, var(--home-chip-accent) 0 8px, transparent 8px)')
    expect(home).not.toContain('linear-gradient(180deg, var(--home-chip-accent) 0 6px, transparent 6px)')
    expect(home).toContain('home-provider-intro')
    expect(home).toContain('border-top: 1px solid rgba(255, 250, 240, 0.42);')
    expect(home).toContain('.home-provider-section .home-section-label')
    expect(home).toContain('.home-footer {')
    expect(home).toContain('display: flex;')
    expect(home).toContain('width: calc(100% - var(--home-gutter) * 2);')
    expect(home).toContain('max-width: var(--home-max);')
    expect(home).toContain('margin: 0 auto;')
    expect(home).toContain('background: #050505;')
    expect(home).toContain('border-top: 0;')
    expect(cssBlock(home, '.home-footer')).not.toContain('max-width: none;')
    expect(home).not.toContain('class="home-footer-band"')
    expect(home).not.toContain('class="home-footer-inner"')
    expect(home).not.toContain('.home-footer-band')
    expect(home).not.toContain('.home-footer-inner')
    expect(home).not.toContain('.home-footer {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  gap: 20px;\n  min-height: 100vh;')
    expect(home).not.toContain('linear-gradient(115deg, transparent 0 52%, rgba(0, 47, 167, 0.94) 52.2% 100%)')
  })

  it('matches the Downloads Atelier Zero example component grammar on the home page', () => {
    const home = readFile('src/views/HomeView.vue')

    expect(home).toContain('class="home-display home-dot"')
    expect(home).toContain('class="home-capability-kicker"')
    expect(home).toContain('class="home-capability-grid"')
    expect(home).toContain('class="home-cap-card home-cap-card-featured"')
    expect(home).toContain('class="home-cap-card home-cap-card-dust"')
    expect(home).toContain('class="home-cap-card home-cap-card-ink"')
    expect(home).toContain('class="home-provider-specimen-grid"')
    expect(home).toContain('class="home-provider-specimen home-provider-specimen-featured home-provider-specimen-claude"')
    expect(home).toContain('class="home-provider-swatch"')
    expect(home).toContain('class="home-provider-meta"')
    expect(home).toContain('class="home-provider-status"')
    expect(home).toContain('.home-section-label::before')
    expect(home).toContain('.home-section-label::after')
    expect(home).toContain('background: repeating-linear-gradient(to right, var(--atelier-line-strong), var(--atelier-line-strong) 2px, transparent 2px, transparent 8px);')
    expect(home).toContain('grid-template-columns: repeat(4, minmax(0, 1fr));')
    expect(home).not.toContain('.home-ascii-shell .home-cap-card-featured {\n  grid-column: span 2;')
    expect(home).toContain('grid-template-columns: repeat(5, minmax(0, 1fr));')
    expect(home).not.toContain('.home-ascii-shell .home-provider-specimen-featured {\n  grid-column: span 6;')
    expect(home).toContain('min-height: clamp(240px, 30vh, 292px);')
    expect(home).toContain('border: 1px solid var(--atelier-ink);')
    expect(home).toContain('background: var(--home-surface-paper);')
    expect(home).toContain('background: var(--atelier-blue);')
    expect(home).toContain('<article\n              class="home-provider-specimen home-provider-specimen-featured home-provider-specimen-claude"')
    expect(home).toContain('</article>')
    expect(home).not.toContain('<PixelCard')
    expect(home).not.toContain('</PixelCard>')
    expect(home).not.toContain('<FluidGlassButton')
    expect(home).toContain('<div\n                  class="home-ring"')
    expect(home).toContain('width: 72px;')
    expect(home).toContain('height: 72px;')
    expect(home).not.toContain('width: 96px;')
    expect(home).not.toContain('height: 96px;')
    expect(home).not.toContain('width: 144px;')
    expect(home).not.toContain('height: 144px;')
    expect(home).toContain('background: transparent;')
    expect(home).toContain('border: 0;')
    expect(home).toContain('.home-provider-logo-mark :deep(.provider-brand-icon)')
    expect(home).toContain('.home-provider-logo-mark :deep(.provider-brand-image-system)')
    expect(home).toContain('.home-provider-logo-mark :deep(.provider-brand-image-custom)')
    expect(home).not.toContain('class="home-feature-tags"')
    expect(home).not.toContain('class="home-feature-grid"')
    expect(home).not.toContain('class="home-feature-card')
    expect(home).not.toContain('class="home-provider-grid"')
    expect(home).not.toContain('class="home-provider-chip')
    expect(home).not.toContain('box-shadow: inset 8px 0 0 var(--home-chip-accent);')
    expect(home).not.toContain('box-shadow: inset 0 6px 0 var(--home-chip-accent);')
  })

  it('keeps dark home overrides scoped to the home shell', () => {
    const home = readFile('src/views/HomeView.vue')

    expect(home).toContain(':global(.dark .home-ascii-shell)')
    expect(home).toContain(':global(.dark .home-ascii-shell .terminal-window)')
    expect(home).toContain(':global(.dark .home-ascii-shell .home-logo)')
    expect(home).not.toContain(':global(.dark) .home-ascii-shell')
    expect(home).not.toContain(':global(.dark) .home-logo')
    expect(home).not.toContain(':deep(.dark) .terminal-window')
  })

  it('hides the default home scrollbar without disabling the page content', () => {
    const css = readFile('src/style.css')

    expect(css).toContain('html:has(.home-ascii-shell)')
    expect(css).toContain('body:has(.home-ascii-shell)')
    expect(css).toContain('::-webkit-scrollbar')
  })

  it('keeps native smooth scrolling without JS wheel interceptors', () => {
    const css = readFile('src/style.css')
    const main = readFile('src/main.ts')

    expect(css).toContain('@media (prefers-reduced-motion: no-preference)')
    expect(css).toContain('scroll-behavior: smooth;')
    expect(css).toContain('.sidebar-nav')
    expect(css).toContain('.overflow-y-auto')
    expect(css).toContain('.overflow-auto')
    expect(css).toContain('overscroll-behavior')
    expect(css).not.toContain('html.lenis')
    expect(main).not.toContain("from 'lenis'")
    expect(main).not.toContain('new Lenis(')
    expect(main).not.toContain('installInertialScrolling')
    expect(main).not.toContain('installSmoothWheelScrolling')
  })

  it('keeps the restored home provider cards free of the failed pixel/glass wrappers', () => {
    const home = readFile('src/views/HomeView.vue')

    expect(home).toContain('<article\n              class="home-provider-specimen')
    expect(home).not.toContain('PixelCard')
    expect(home).not.toContain('pixel-card')
    expect(home).not.toContain('FluidGlassButton')
    expect(home).not.toContain('fluid-glass')
    expect(home).not.toContain('.home-ring::before')
    expect(home).not.toContain('.home-ring::after')
  })
})
