// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/codexaccountmetadata"
	"github.com/Wei-Shaw/sub2api/ent/codexgroup"
)

// CodexAccountMetadata is the model entity for the CodexAccountMetadata schema.
type CodexAccountMetadata struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AuthName holds the value of the "auth_name" field.
	AuthName string `json:"auth_name,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// LocalTags holds the value of the "local_tags" field.
	LocalTags []string `json:"local_tags,omitempty"`
	// Settings holds the value of the "settings" field.
	Settings map[string]interface{} `json:"settings,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CodexAccountMetadataQuery when eager-loading is set.
	Edges        CodexAccountMetadataEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CodexAccountMetadataEdges holds the relations/edges for other nodes in the graph.
type CodexAccountMetadataEdges struct {
	// Group holds the value of the group edge.
	Group *CodexGroup `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CodexAccountMetadataEdges) GroupOrErr() (*CodexGroup, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: codexgroup.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CodexAccountMetadata) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case codexaccountmetadata.FieldLocalTags, codexaccountmetadata.FieldSettings:
			values[i] = new([]byte)
		case codexaccountmetadata.FieldID, codexaccountmetadata.FieldGroupID, codexaccountmetadata.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case codexaccountmetadata.FieldAuthName, codexaccountmetadata.FieldDisplayName, codexaccountmetadata.FieldNote:
			values[i] = new(sql.NullString)
		case codexaccountmetadata.FieldCreatedAt, codexaccountmetadata.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CodexAccountMetadata fields.
func (_m *CodexAccountMetadata) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case codexaccountmetadata.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case codexaccountmetadata.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case codexaccountmetadata.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case codexaccountmetadata.FieldAuthName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_name", values[i])
			} else if value.Valid {
				_m.AuthName = value.String
			}
		case codexaccountmetadata.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case codexaccountmetadata.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case codexaccountmetadata.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		case codexaccountmetadata.FieldLocalTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field local_tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.LocalTags); err != nil {
					return fmt.Errorf("unmarshal field local_tags: %w", err)
				}
			}
		case codexaccountmetadata.FieldSettings:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field settings", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Settings); err != nil {
					return fmt.Errorf("unmarshal field settings: %w", err)
				}
			}
		case codexaccountmetadata.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CodexAccountMetadata.
// This includes values selected through modifiers, order, etc.
func (_m *CodexAccountMetadata) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the CodexAccountMetadata entity.
func (_m *CodexAccountMetadata) QueryGroup() *CodexGroupQuery {
	return NewCodexAccountMetadataClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this CodexAccountMetadata.
// Note that you need to call CodexAccountMetadata.Unwrap() before calling this method if this CodexAccountMetadata
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CodexAccountMetadata) Update() *CodexAccountMetadataUpdateOne {
	return NewCodexAccountMetadataClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CodexAccountMetadata entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CodexAccountMetadata) Unwrap() *CodexAccountMetadata {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CodexAccountMetadata is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CodexAccountMetadata) String() string {
	var builder strings.Builder
	builder.WriteString("CodexAccountMetadata(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("auth_name=")
	builder.WriteString(_m.AuthName)
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteString(", ")
	builder.WriteString("local_tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.LocalTags))
	builder.WriteString(", ")
	builder.WriteString("settings=")
	builder.WriteString(fmt.Sprintf("%v", _m.Settings))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// CodexAccountMetadataSlice is a parsable slice of CodexAccountMetadata.
type CodexAccountMetadataSlice []*CodexAccountMetadata
