// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/codexaccountmetadata"
	"github.com/Wei-Shaw/sub2api/ent/codexgroup"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CodexGroupUpdate is the builder for updating CodexGroup entities.
type CodexGroupUpdate struct {
	config
	hooks    []Hook
	mutation *CodexGroupMutation
}

// Where appends a list predicates to the CodexGroupUpdate builder.
func (_u *CodexGroupUpdate) Where(ps ...predicate.CodexGroup) *CodexGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CodexGroupUpdate) SetUpdatedAt(v time.Time) *CodexGroupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *CodexGroupUpdate) SetName(v string) *CodexGroupUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CodexGroupUpdate) SetNillableName(v *string) *CodexGroupUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetColor sets the "color" field.
func (_u *CodexGroupUpdate) SetColor(v string) *CodexGroupUpdate {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *CodexGroupUpdate) SetNillableColor(v *string) *CodexGroupUpdate {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *CodexGroupUpdate) SetSortOrder(v int) *CodexGroupUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *CodexGroupUpdate) SetNillableSortOrder(v *int) *CodexGroupUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *CodexGroupUpdate) AddSortOrder(v int) *CodexGroupUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddAccountMetadatumIDs adds the "account_metadata" edge to the CodexAccountMetadata entity by IDs.
func (_u *CodexGroupUpdate) AddAccountMetadatumIDs(ids ...int64) *CodexGroupUpdate {
	_u.mutation.AddAccountMetadatumIDs(ids...)
	return _u
}

// AddAccountMetadata adds the "account_metadata" edges to the CodexAccountMetadata entity.
func (_u *CodexGroupUpdate) AddAccountMetadata(v ...*CodexAccountMetadata) *CodexGroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountMetadatumIDs(ids...)
}

// Mutation returns the CodexGroupMutation object of the builder.
func (_u *CodexGroupUpdate) Mutation() *CodexGroupMutation {
	return _u.mutation
}

// ClearAccountMetadata clears all "account_metadata" edges to the CodexAccountMetadata entity.
func (_u *CodexGroupUpdate) ClearAccountMetadata() *CodexGroupUpdate {
	_u.mutation.ClearAccountMetadata()
	return _u
}

// RemoveAccountMetadatumIDs removes the "account_metadata" edge to CodexAccountMetadata entities by IDs.
func (_u *CodexGroupUpdate) RemoveAccountMetadatumIDs(ids ...int64) *CodexGroupUpdate {
	_u.mutation.RemoveAccountMetadatumIDs(ids...)
	return _u
}

// RemoveAccountMetadata removes "account_metadata" edges to CodexAccountMetadata entities.
func (_u *CodexGroupUpdate) RemoveAccountMetadata(v ...*CodexAccountMetadata) *CodexGroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountMetadatumIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CodexGroupUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CodexGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CodexGroupUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := codexgroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodexGroupUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := codexgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CodexGroup.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Color(); ok {
		if err := codexgroup.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "CodexGroup.color": %w`, err)}
		}
	}
	return nil
}

func (_u *CodexGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codexgroup.Table, codexgroup.Columns, sqlgraph.NewFieldSpec(codexgroup.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(codexgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(codexgroup.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(codexgroup.FieldColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(codexgroup.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(codexgroup.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.AccountMetadataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexgroup.AccountMetadataTable,
			Columns: []string{codexgroup.AccountMetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexaccountmetadata.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountMetadataIDs(); len(nodes) > 0 && !_u.mutation.AccountMetadataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexgroup.AccountMetadataTable,
			Columns: []string{codexgroup.AccountMetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexaccountmetadata.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountMetadataIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexgroup.AccountMetadataTable,
			Columns: []string{codexgroup.AccountMetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexaccountmetadata.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CodexGroupUpdateOne is the builder for updating a single CodexGroup entity.
type CodexGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CodexGroupMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CodexGroupUpdateOne) SetUpdatedAt(v time.Time) *CodexGroupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *CodexGroupUpdateOne) SetName(v string) *CodexGroupUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CodexGroupUpdateOne) SetNillableName(v *string) *CodexGroupUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetColor sets the "color" field.
func (_u *CodexGroupUpdateOne) SetColor(v string) *CodexGroupUpdateOne {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *CodexGroupUpdateOne) SetNillableColor(v *string) *CodexGroupUpdateOne {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *CodexGroupUpdateOne) SetSortOrder(v int) *CodexGroupUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *CodexGroupUpdateOne) SetNillableSortOrder(v *int) *CodexGroupUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *CodexGroupUpdateOne) AddSortOrder(v int) *CodexGroupUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddAccountMetadatumIDs adds the "account_metadata" edge to the CodexAccountMetadata entity by IDs.
func (_u *CodexGroupUpdateOne) AddAccountMetadatumIDs(ids ...int64) *CodexGroupUpdateOne {
	_u.mutation.AddAccountMetadatumIDs(ids...)
	return _u
}

// AddAccountMetadata adds the "account_metadata" edges to the CodexAccountMetadata entity.
func (_u *CodexGroupUpdateOne) AddAccountMetadata(v ...*CodexAccountMetadata) *CodexGroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountMetadatumIDs(ids...)
}

// Mutation returns the CodexGroupMutation object of the builder.
func (_u *CodexGroupUpdateOne) Mutation() *CodexGroupMutation {
	return _u.mutation
}

// ClearAccountMetadata clears all "account_metadata" edges to the CodexAccountMetadata entity.
func (_u *CodexGroupUpdateOne) ClearAccountMetadata() *CodexGroupUpdateOne {
	_u.mutation.ClearAccountMetadata()
	return _u
}

// RemoveAccountMetadatumIDs removes the "account_metadata" edge to CodexAccountMetadata entities by IDs.
func (_u *CodexGroupUpdateOne) RemoveAccountMetadatumIDs(ids ...int64) *CodexGroupUpdateOne {
	_u.mutation.RemoveAccountMetadatumIDs(ids...)
	return _u
}

// RemoveAccountMetadata removes "account_metadata" edges to CodexAccountMetadata entities.
func (_u *CodexGroupUpdateOne) RemoveAccountMetadata(v ...*CodexAccountMetadata) *CodexGroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountMetadatumIDs(ids...)
}

// Where appends a list predicates to the CodexGroupUpdate builder.
func (_u *CodexGroupUpdateOne) Where(ps ...predicate.CodexGroup) *CodexGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CodexGroupUpdateOne) Select(field string, fields ...string) *CodexGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CodexGroup entity.
func (_u *CodexGroupUpdateOne) Save(ctx context.Context) (*CodexGroup, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexGroupUpdateOne) SaveX(ctx context.Context) *CodexGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CodexGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CodexGroupUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := codexgroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodexGroupUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := codexgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CodexGroup.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Color(); ok {
		if err := codexgroup.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "CodexGroup.color": %w`, err)}
		}
	}
	return nil
}

func (_u *CodexGroupUpdateOne) sqlSave(ctx context.Context) (_node *CodexGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codexgroup.Table, codexgroup.Columns, sqlgraph.NewFieldSpec(codexgroup.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CodexGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codexgroup.FieldID)
		for _, f := range fields {
			if !codexgroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != codexgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(codexgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(codexgroup.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(codexgroup.FieldColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(codexgroup.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(codexgroup.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.AccountMetadataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexgroup.AccountMetadataTable,
			Columns: []string{codexgroup.AccountMetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexaccountmetadata.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountMetadataIDs(); len(nodes) > 0 && !_u.mutation.AccountMetadataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexgroup.AccountMetadataTable,
			Columns: []string{codexgroup.AccountMetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexaccountmetadata.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountMetadataIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexgroup.AccountMetadataTable,
			Columns: []string{codexgroup.AccountMetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexaccountmetadata.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CodexGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
