// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/codexaccountmetadata"
	"github.com/Wei-Shaw/sub2api/ent/codexgroup"
)

// CodexGroupCreate is the builder for creating a CodexGroup entity.
type CodexGroupCreate struct {
	config
	mutation *CodexGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CodexGroupCreate) SetCreatedAt(v time.Time) *CodexGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CodexGroupCreate) SetNillableCreatedAt(v *time.Time) *CodexGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CodexGroupCreate) SetUpdatedAt(v time.Time) *CodexGroupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CodexGroupCreate) SetNillableUpdatedAt(v *time.Time) *CodexGroupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *CodexGroupCreate) SetName(v string) *CodexGroupCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetColor sets the "color" field.
func (_c *CodexGroupCreate) SetColor(v string) *CodexGroupCreate {
	_c.mutation.SetColor(v)
	return _c
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_c *CodexGroupCreate) SetNillableColor(v *string) *CodexGroupCreate {
	if v != nil {
		_c.SetColor(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *CodexGroupCreate) SetSortOrder(v int) *CodexGroupCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *CodexGroupCreate) SetNillableSortOrder(v *int) *CodexGroupCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// AddAccountMetadatumIDs adds the "account_metadata" edge to the CodexAccountMetadata entity by IDs.
func (_c *CodexGroupCreate) AddAccountMetadatumIDs(ids ...int64) *CodexGroupCreate {
	_c.mutation.AddAccountMetadatumIDs(ids...)
	return _c
}

// AddAccountMetadata adds the "account_metadata" edges to the CodexAccountMetadata entity.
func (_c *CodexGroupCreate) AddAccountMetadata(v ...*CodexAccountMetadata) *CodexGroupCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountMetadatumIDs(ids...)
}

// Mutation returns the CodexGroupMutation object of the builder.
func (_c *CodexGroupCreate) Mutation() *CodexGroupMutation {
	return _c.mutation
}

// Save creates the CodexGroup in the database.
func (_c *CodexGroupCreate) Save(ctx context.Context) (*CodexGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CodexGroupCreate) SaveX(ctx context.Context) *CodexGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CodexGroupCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := codexgroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := codexgroup.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Color(); !ok {
		v := codexgroup.DefaultColor
		_c.mutation.SetColor(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := codexgroup.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CodexGroupCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CodexGroup.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CodexGroup.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CodexGroup.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := codexgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CodexGroup.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Color(); !ok {
		return &ValidationError{Name: "color", err: errors.New(`ent: missing required field "CodexGroup.color"`)}
	}
	if v, ok := _c.mutation.Color(); ok {
		if err := codexgroup.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "CodexGroup.color": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "CodexGroup.sort_order"`)}
	}
	return nil
}

func (_c *CodexGroupCreate) sqlSave(ctx context.Context) (*CodexGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CodexGroupCreate) createSpec() (*CodexGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &CodexGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(codexgroup.Table, sqlgraph.NewFieldSpec(codexgroup.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(codexgroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(codexgroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(codexgroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Color(); ok {
		_spec.SetField(codexgroup.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(codexgroup.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.AccountMetadataIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexgroup.AccountMetadataTable,
			Columns: []string{codexgroup.AccountMetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexaccountmetadata.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodexGroup.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodexGroupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CodexGroupCreate) OnConflict(opts ...sql.ConflictOption) *CodexGroupUpsertOne {
	_c.conflict = opts
	return &CodexGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodexGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodexGroupCreate) OnConflictColumns(columns ...string) *CodexGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodexGroupUpsertOne{
		create: _c,
	}
}

type (
	// CodexGroupUpsertOne is the builder for "upsert"-ing
	//  one CodexGroup node.
	CodexGroupUpsertOne struct {
		create *CodexGroupCreate
	}

	// CodexGroupUpsert is the "OnConflict" setter.
	CodexGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CodexGroupUpsert) SetUpdatedAt(v time.Time) *CodexGroupUpsert {
	u.Set(codexgroup.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CodexGroupUpsert) UpdateUpdatedAt() *CodexGroupUpsert {
	u.SetExcluded(codexgroup.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *CodexGroupUpsert) SetName(v string) *CodexGroupUpsert {
	u.Set(codexgroup.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CodexGroupUpsert) UpdateName() *CodexGroupUpsert {
	u.SetExcluded(codexgroup.FieldName)
	return u
}

// SetColor sets the "color" field.
func (u *CodexGroupUpsert) SetColor(v string) *CodexGroupUpsert {
	u.Set(codexgroup.FieldColor, v)
	return u
}

// UpdateColor sets the "color" field to the value that was provided on create.
func (u *CodexGroupUpsert) UpdateColor() *CodexGroupUpsert {
	u.SetExcluded(codexgroup.FieldColor)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *CodexGroupUpsert) SetSortOrder(v int) *CodexGroupUpsert {
	u.Set(codexgroup.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CodexGroupUpsert) UpdateSortOrder() *CodexGroupUpsert {
	u.SetExcluded(codexgroup.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CodexGroupUpsert) AddSortOrder(v int) *CodexGroupUpsert {
	u.Add(codexgroup.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CodexGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CodexGroupUpsertOne) UpdateNewValues() *CodexGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(codexgroup.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodexGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CodexGroupUpsertOne) Ignore() *CodexGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodexGroupUpsertOne) DoNothing() *CodexGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodexGroupCreate.OnConflict
// documentation for more info.
func (u *CodexGroupUpsertOne) Update(set func(*CodexGroupUpsert)) *CodexGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodexGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CodexGroupUpsertOne) SetUpdatedAt(v time.Time) *CodexGroupUpsertOne {
	return u.Update(func(s *CodexGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CodexGroupUpsertOne) UpdateUpdatedAt() *CodexGroupUpsertOne {
	return u.Update(func(s *CodexGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *CodexGroupUpsertOne) SetName(v string) *CodexGroupUpsertOne {
	return u.Update(func(s *CodexGroupUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CodexGroupUpsertOne) UpdateName() *CodexGroupUpsertOne {
	return u.Update(func(s *CodexGroupUpsert) {
		s.UpdateName()
	})
}

// SetColor sets the "color" field.
func (u *CodexGroupUpsertOne) SetColor(v string) *CodexGroupUpsertOne {
	return u.Update(func(s *CodexGroupUpsert) {
		s.SetColor(v)
	})
}

// UpdateColor sets the "color" field to the value that was provided on create.
func (u *CodexGroupUpsertOne) UpdateColor() *CodexGroupUpsertOne {
	return u.Update(func(s *CodexGroupUpsert) {
		s.UpdateColor()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *CodexGroupUpsertOne) SetSortOrder(v int) *CodexGroupUpsertOne {
	return u.Update(func(s *CodexGroupUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CodexGroupUpsertOne) AddSortOrder(v int) *CodexGroupUpsertOne {
	return u.Update(func(s *CodexGroupUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CodexGroupUpsertOne) UpdateSortOrder() *CodexGroupUpsertOne {
	return u.Update(func(s *CodexGroupUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *CodexGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodexGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodexGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CodexGroupUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CodexGroupUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CodexGroupCreateBulk is the builder for creating many CodexGroup entities in bulk.
type CodexGroupCreateBulk struct {
	config
	err      error
	builders []*CodexGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the CodexGroup entities in the database.
func (_c *CodexGroupCreateBulk) Save(ctx context.Context) ([]*CodexGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CodexGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CodexGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CodexGroupCreateBulk) SaveX(ctx context.Context) []*CodexGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodexGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodexGroupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CodexGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *CodexGroupUpsertBulk {
	_c.conflict = opts
	return &CodexGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodexGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodexGroupCreateBulk) OnConflictColumns(columns ...string) *CodexGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodexGroupUpsertBulk{
		create: _c,
	}
}

// CodexGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of CodexGroup nodes.
type CodexGroupUpsertBulk struct {
	create *CodexGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CodexGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CodexGroupUpsertBulk) UpdateNewValues() *CodexGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(codexgroup.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodexGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CodexGroupUpsertBulk) Ignore() *CodexGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodexGroupUpsertBulk) DoNothing() *CodexGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodexGroupCreateBulk.OnConflict
// documentation for more info.
func (u *CodexGroupUpsertBulk) Update(set func(*CodexGroupUpsert)) *CodexGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodexGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CodexGroupUpsertBulk) SetUpdatedAt(v time.Time) *CodexGroupUpsertBulk {
	return u.Update(func(s *CodexGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CodexGroupUpsertBulk) UpdateUpdatedAt() *CodexGroupUpsertBulk {
	return u.Update(func(s *CodexGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *CodexGroupUpsertBulk) SetName(v string) *CodexGroupUpsertBulk {
	return u.Update(func(s *CodexGroupUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CodexGroupUpsertBulk) UpdateName() *CodexGroupUpsertBulk {
	return u.Update(func(s *CodexGroupUpsert) {
		s.UpdateName()
	})
}

// SetColor sets the "color" field.
func (u *CodexGroupUpsertBulk) SetColor(v string) *CodexGroupUpsertBulk {
	return u.Update(func(s *CodexGroupUpsert) {
		s.SetColor(v)
	})
}

// UpdateColor sets the "color" field to the value that was provided on create.
func (u *CodexGroupUpsertBulk) UpdateColor() *CodexGroupUpsertBulk {
	return u.Update(func(s *CodexGroupUpsert) {
		s.UpdateColor()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *CodexGroupUpsertBulk) SetSortOrder(v int) *CodexGroupUpsertBulk {
	return u.Update(func(s *CodexGroupUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CodexGroupUpsertBulk) AddSortOrder(v int) *CodexGroupUpsertBulk {
	return u.Update(func(s *CodexGroupUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CodexGroupUpsertBulk) UpdateSortOrder() *CodexGroupUpsertBulk {
	return u.Update(func(s *CodexGroupUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *CodexGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CodexGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodexGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodexGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
