// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/codexgroup"
)

// CodexGroup is the model entity for the CodexGroup schema.
type CodexGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Color holds the value of the "color" field.
	Color string `json:"color,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CodexGroupQuery when eager-loading is set.
	Edges        CodexGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CodexGroupEdges holds the relations/edges for other nodes in the graph.
type CodexGroupEdges struct {
	// AccountMetadata holds the value of the account_metadata edge.
	AccountMetadata []*CodexAccountMetadata `json:"account_metadata,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountMetadataOrErr returns the AccountMetadata value or an error if the edge
// was not loaded in eager-loading.
func (e CodexGroupEdges) AccountMetadataOrErr() ([]*CodexAccountMetadata, error) {
	if e.loadedTypes[0] {
		return e.AccountMetadata, nil
	}
	return nil, &NotLoadedError{edge: "account_metadata"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CodexGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case codexgroup.FieldID, codexgroup.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case codexgroup.FieldName, codexgroup.FieldColor:
			values[i] = new(sql.NullString)
		case codexgroup.FieldCreatedAt, codexgroup.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CodexGroup fields.
func (_m *CodexGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case codexgroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case codexgroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case codexgroup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case codexgroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case codexgroup.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				_m.Color = value.String
			}
		case codexgroup.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CodexGroup.
// This includes values selected through modifiers, order, etc.
func (_m *CodexGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccountMetadata queries the "account_metadata" edge of the CodexGroup entity.
func (_m *CodexGroup) QueryAccountMetadata() *CodexAccountMetadataQuery {
	return NewCodexGroupClient(_m.config).QueryAccountMetadata(_m)
}

// Update returns a builder for updating this CodexGroup.
// Note that you need to call CodexGroup.Unwrap() before calling this method if this CodexGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CodexGroup) Update() *CodexGroupUpdateOne {
	return NewCodexGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CodexGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CodexGroup) Unwrap() *CodexGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CodexGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CodexGroup) String() string {
	var builder strings.Builder
	builder.WriteString("CodexGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("color=")
	builder.WriteString(_m.Color)
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// CodexGroups is a parsable slice of CodexGroup.
type CodexGroups []*CodexGroup
