// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/codexaccountmetadata"
	"github.com/Wei-Shaw/sub2api/ent/codexgroup"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CodexAccountMetadataUpdate is the builder for updating CodexAccountMetadata entities.
type CodexAccountMetadataUpdate struct {
	config
	hooks    []Hook
	mutation *CodexAccountMetadataMutation
}

// Where appends a list predicates to the CodexAccountMetadataUpdate builder.
func (_u *CodexAccountMetadataUpdate) Where(ps ...predicate.CodexAccountMetadata) *CodexAccountMetadataUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CodexAccountMetadataUpdate) SetUpdatedAt(v time.Time) *CodexAccountMetadataUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAuthName sets the "auth_name" field.
func (_u *CodexAccountMetadataUpdate) SetAuthName(v string) *CodexAccountMetadataUpdate {
	_u.mutation.SetAuthName(v)
	return _u
}

// SetNillableAuthName sets the "auth_name" field if the given value is not nil.
func (_u *CodexAccountMetadataUpdate) SetNillableAuthName(v *string) *CodexAccountMetadataUpdate {
	if v != nil {
		_u.SetAuthName(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *CodexAccountMetadataUpdate) SetGroupID(v int64) *CodexAccountMetadataUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *CodexAccountMetadataUpdate) SetNillableGroupID(v *int64) *CodexAccountMetadataUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *CodexAccountMetadataUpdate) ClearGroupID() *CodexAccountMetadataUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *CodexAccountMetadataUpdate) SetDisplayName(v string) *CodexAccountMetadataUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *CodexAccountMetadataUpdate) SetNillableDisplayName(v *string) *CodexAccountMetadataUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *CodexAccountMetadataUpdate) SetNote(v string) *CodexAccountMetadataUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *CodexAccountMetadataUpdate) SetNillableNote(v *string) *CodexAccountMetadataUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetLocalTags sets the "local_tags" field.
func (_u *CodexAccountMetadataUpdate) SetLocalTags(v []string) *CodexAccountMetadataUpdate {
	_u.mutation.SetLocalTags(v)
	return _u
}

// AppendLocalTags appends value to the "local_tags" field.
func (_u *CodexAccountMetadataUpdate) AppendLocalTags(v []string) *CodexAccountMetadataUpdate {
	_u.mutation.AppendLocalTags(v)
	return _u
}

// SetSettings sets the "settings" field.
func (_u *CodexAccountMetadataUpdate) SetSettings(v map[string]interface{}) *CodexAccountMetadataUpdate {
	_u.mutation.SetSettings(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *CodexAccountMetadataUpdate) SetSortOrder(v int) *CodexAccountMetadataUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *CodexAccountMetadataUpdate) SetNillableSortOrder(v *int) *CodexAccountMetadataUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *CodexAccountMetadataUpdate) AddSortOrder(v int) *CodexAccountMetadataUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetGroup sets the "group" edge to the CodexGroup entity.
func (_u *CodexAccountMetadataUpdate) SetGroup(v *CodexGroup) *CodexAccountMetadataUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the CodexAccountMetadataMutation object of the builder.
func (_u *CodexAccountMetadataUpdate) Mutation() *CodexAccountMetadataMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the CodexGroup entity.
func (_u *CodexAccountMetadataUpdate) ClearGroup() *CodexAccountMetadataUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CodexAccountMetadataUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexAccountMetadataUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CodexAccountMetadataUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexAccountMetadataUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CodexAccountMetadataUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := codexaccountmetadata.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodexAccountMetadataUpdate) check() error {
	if v, ok := _u.mutation.AuthName(); ok {
		if err := codexaccountmetadata.AuthNameValidator(v); err != nil {
			return &ValidationError{Name: "auth_name", err: fmt.Errorf(`ent: validator failed for field "CodexAccountMetadata.auth_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := codexaccountmetadata.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "CodexAccountMetadata.display_name": %w`, err)}
		}
	}
	return nil
}

func (_u *CodexAccountMetadataUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codexaccountmetadata.Table, codexaccountmetadata.Columns, sqlgraph.NewFieldSpec(codexaccountmetadata.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(codexaccountmetadata.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AuthName(); ok {
		_spec.SetField(codexaccountmetadata.FieldAuthName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(codexaccountmetadata.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(codexaccountmetadata.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalTags(); ok {
		_spec.SetField(codexaccountmetadata.FieldLocalTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLocalTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, codexaccountmetadata.FieldLocalTags, value)
		})
	}
	if value, ok := _u.mutation.Settings(); ok {
		_spec.SetField(codexaccountmetadata.FieldSettings, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(codexaccountmetadata.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(codexaccountmetadata.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codexaccountmetadata.GroupTable,
			Columns: []string{codexaccountmetadata.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexgroup.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codexaccountmetadata.GroupTable,
			Columns: []string{codexaccountmetadata.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexaccountmetadata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CodexAccountMetadataUpdateOne is the builder for updating a single CodexAccountMetadata entity.
type CodexAccountMetadataUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CodexAccountMetadataMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CodexAccountMetadataUpdateOne) SetUpdatedAt(v time.Time) *CodexAccountMetadataUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAuthName sets the "auth_name" field.
func (_u *CodexAccountMetadataUpdateOne) SetAuthName(v string) *CodexAccountMetadataUpdateOne {
	_u.mutation.SetAuthName(v)
	return _u
}

// SetNillableAuthName sets the "auth_name" field if the given value is not nil.
func (_u *CodexAccountMetadataUpdateOne) SetNillableAuthName(v *string) *CodexAccountMetadataUpdateOne {
	if v != nil {
		_u.SetAuthName(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *CodexAccountMetadataUpdateOne) SetGroupID(v int64) *CodexAccountMetadataUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *CodexAccountMetadataUpdateOne) SetNillableGroupID(v *int64) *CodexAccountMetadataUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *CodexAccountMetadataUpdateOne) ClearGroupID() *CodexAccountMetadataUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *CodexAccountMetadataUpdateOne) SetDisplayName(v string) *CodexAccountMetadataUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *CodexAccountMetadataUpdateOne) SetNillableDisplayName(v *string) *CodexAccountMetadataUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *CodexAccountMetadataUpdateOne) SetNote(v string) *CodexAccountMetadataUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *CodexAccountMetadataUpdateOne) SetNillableNote(v *string) *CodexAccountMetadataUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetLocalTags sets the "local_tags" field.
func (_u *CodexAccountMetadataUpdateOne) SetLocalTags(v []string) *CodexAccountMetadataUpdateOne {
	_u.mutation.SetLocalTags(v)
	return _u
}

// AppendLocalTags appends value to the "local_tags" field.
func (_u *CodexAccountMetadataUpdateOne) AppendLocalTags(v []string) *CodexAccountMetadataUpdateOne {
	_u.mutation.AppendLocalTags(v)
	return _u
}

// SetSettings sets the "settings" field.
func (_u *CodexAccountMetadataUpdateOne) SetSettings(v map[string]interface{}) *CodexAccountMetadataUpdateOne {
	_u.mutation.SetSettings(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *CodexAccountMetadataUpdateOne) SetSortOrder(v int) *CodexAccountMetadataUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *CodexAccountMetadataUpdateOne) SetNillableSortOrder(v *int) *CodexAccountMetadataUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *CodexAccountMetadataUpdateOne) AddSortOrder(v int) *CodexAccountMetadataUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetGroup sets the "group" edge to the CodexGroup entity.
func (_u *CodexAccountMetadataUpdateOne) SetGroup(v *CodexGroup) *CodexAccountMetadataUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the CodexAccountMetadataMutation object of the builder.
func (_u *CodexAccountMetadataUpdateOne) Mutation() *CodexAccountMetadataMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the CodexGroup entity.
func (_u *CodexAccountMetadataUpdateOne) ClearGroup() *CodexAccountMetadataUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the CodexAccountMetadataUpdate builder.
func (_u *CodexAccountMetadataUpdateOne) Where(ps ...predicate.CodexAccountMetadata) *CodexAccountMetadataUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CodexAccountMetadataUpdateOne) Select(field string, fields ...string) *CodexAccountMetadataUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CodexAccountMetadata entity.
func (_u *CodexAccountMetadataUpdateOne) Save(ctx context.Context) (*CodexAccountMetadata, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexAccountMetadataUpdateOne) SaveX(ctx context.Context) *CodexAccountMetadata {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CodexAccountMetadataUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexAccountMetadataUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CodexAccountMetadataUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := codexaccountmetadata.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodexAccountMetadataUpdateOne) check() error {
	if v, ok := _u.mutation.AuthName(); ok {
		if err := codexaccountmetadata.AuthNameValidator(v); err != nil {
			return &ValidationError{Name: "auth_name", err: fmt.Errorf(`ent: validator failed for field "CodexAccountMetadata.auth_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := codexaccountmetadata.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "CodexAccountMetadata.display_name": %w`, err)}
		}
	}
	return nil
}

func (_u *CodexAccountMetadataUpdateOne) sqlSave(ctx context.Context) (_node *CodexAccountMetadata, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codexaccountmetadata.Table, codexaccountmetadata.Columns, sqlgraph.NewFieldSpec(codexaccountmetadata.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CodexAccountMetadata.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codexaccountmetadata.FieldID)
		for _, f := range fields {
			if !codexaccountmetadata.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != codexaccountmetadata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(codexaccountmetadata.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AuthName(); ok {
		_spec.SetField(codexaccountmetadata.FieldAuthName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(codexaccountmetadata.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(codexaccountmetadata.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalTags(); ok {
		_spec.SetField(codexaccountmetadata.FieldLocalTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLocalTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, codexaccountmetadata.FieldLocalTags, value)
		})
	}
	if value, ok := _u.mutation.Settings(); ok {
		_spec.SetField(codexaccountmetadata.FieldSettings, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(codexaccountmetadata.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(codexaccountmetadata.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codexaccountmetadata.GroupTable,
			Columns: []string{codexaccountmetadata.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexgroup.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codexaccountmetadata.GroupTable,
			Columns: []string{codexaccountmetadata.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CodexAccountMetadata{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexaccountmetadata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
