// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/codexaccountmetadata"
	"github.com/Wei-Shaw/sub2api/ent/codexgroup"
)

// CodexAccountMetadataCreate is the builder for creating a CodexAccountMetadata entity.
type CodexAccountMetadataCreate struct {
	config
	mutation *CodexAccountMetadataMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CodexAccountMetadataCreate) SetCreatedAt(v time.Time) *CodexAccountMetadataCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CodexAccountMetadataCreate) SetNillableCreatedAt(v *time.Time) *CodexAccountMetadataCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CodexAccountMetadataCreate) SetUpdatedAt(v time.Time) *CodexAccountMetadataCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CodexAccountMetadataCreate) SetNillableUpdatedAt(v *time.Time) *CodexAccountMetadataCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAuthName sets the "auth_name" field.
func (_c *CodexAccountMetadataCreate) SetAuthName(v string) *CodexAccountMetadataCreate {
	_c.mutation.SetAuthName(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *CodexAccountMetadataCreate) SetGroupID(v int64) *CodexAccountMetadataCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *CodexAccountMetadataCreate) SetNillableGroupID(v *int64) *CodexAccountMetadataCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *CodexAccountMetadataCreate) SetDisplayName(v string) *CodexAccountMetadataCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *CodexAccountMetadataCreate) SetNillableDisplayName(v *string) *CodexAccountMetadataCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *CodexAccountMetadataCreate) SetNote(v string) *CodexAccountMetadataCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *CodexAccountMetadataCreate) SetNillableNote(v *string) *CodexAccountMetadataCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetLocalTags sets the "local_tags" field.
func (_c *CodexAccountMetadataCreate) SetLocalTags(v []string) *CodexAccountMetadataCreate {
	_c.mutation.SetLocalTags(v)
	return _c
}

// SetSettings sets the "settings" field.
func (_c *CodexAccountMetadataCreate) SetSettings(v map[string]interface{}) *CodexAccountMetadataCreate {
	_c.mutation.SetSettings(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *CodexAccountMetadataCreate) SetSortOrder(v int) *CodexAccountMetadataCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *CodexAccountMetadataCreate) SetNillableSortOrder(v *int) *CodexAccountMetadataCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the CodexGroup entity.
func (_c *CodexAccountMetadataCreate) SetGroup(v *CodexGroup) *CodexAccountMetadataCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the CodexAccountMetadataMutation object of the builder.
func (_c *CodexAccountMetadataCreate) Mutation() *CodexAccountMetadataMutation {
	return _c.mutation
}

// Save creates the CodexAccountMetadata in the database.
func (_c *CodexAccountMetadataCreate) Save(ctx context.Context) (*CodexAccountMetadata, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CodexAccountMetadataCreate) SaveX(ctx context.Context) *CodexAccountMetadata {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexAccountMetadataCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexAccountMetadataCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CodexAccountMetadataCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := codexaccountmetadata.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := codexaccountmetadata.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		v := codexaccountmetadata.DefaultDisplayName
		_c.mutation.SetDisplayName(v)
	}
	if _, ok := _c.mutation.Note(); !ok {
		v := codexaccountmetadata.DefaultNote
		_c.mutation.SetNote(v)
	}
	if _, ok := _c.mutation.LocalTags(); !ok {
		v := codexaccountmetadata.DefaultLocalTags
		_c.mutation.SetLocalTags(v)
	}
	if _, ok := _c.mutation.Settings(); !ok {
		v := codexaccountmetadata.DefaultSettings()
		_c.mutation.SetSettings(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := codexaccountmetadata.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CodexAccountMetadataCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CodexAccountMetadata.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CodexAccountMetadata.updated_at"`)}
	}
	if _, ok := _c.mutation.AuthName(); !ok {
		return &ValidationError{Name: "auth_name", err: errors.New(`ent: missing required field "CodexAccountMetadata.auth_name"`)}
	}
	if v, ok := _c.mutation.AuthName(); ok {
		if err := codexaccountmetadata.AuthNameValidator(v); err != nil {
			return &ValidationError{Name: "auth_name", err: fmt.Errorf(`ent: validator failed for field "CodexAccountMetadata.auth_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "CodexAccountMetadata.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := codexaccountmetadata.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "CodexAccountMetadata.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "CodexAccountMetadata.note"`)}
	}
	if _, ok := _c.mutation.LocalTags(); !ok {
		return &ValidationError{Name: "local_tags", err: errors.New(`ent: missing required field "CodexAccountMetadata.local_tags"`)}
	}
	if _, ok := _c.mutation.Settings(); !ok {
		return &ValidationError{Name: "settings", err: errors.New(`ent: missing required field "CodexAccountMetadata.settings"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "CodexAccountMetadata.sort_order"`)}
	}
	return nil
}

func (_c *CodexAccountMetadataCreate) sqlSave(ctx context.Context) (*CodexAccountMetadata, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CodexAccountMetadataCreate) createSpec() (*CodexAccountMetadata, *sqlgraph.CreateSpec) {
	var (
		_node = &CodexAccountMetadata{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(codexaccountmetadata.Table, sqlgraph.NewFieldSpec(codexaccountmetadata.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(codexaccountmetadata.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(codexaccountmetadata.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AuthName(); ok {
		_spec.SetField(codexaccountmetadata.FieldAuthName, field.TypeString, value)
		_node.AuthName = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(codexaccountmetadata.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(codexaccountmetadata.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.LocalTags(); ok {
		_spec.SetField(codexaccountmetadata.FieldLocalTags, field.TypeJSON, value)
		_node.LocalTags = value
	}
	if value, ok := _c.mutation.Settings(); ok {
		_spec.SetField(codexaccountmetadata.FieldSettings, field.TypeJSON, value)
		_node.Settings = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(codexaccountmetadata.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codexaccountmetadata.GroupTable,
			Columns: []string{codexaccountmetadata.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodexAccountMetadata.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodexAccountMetadataUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CodexAccountMetadataCreate) OnConflict(opts ...sql.ConflictOption) *CodexAccountMetadataUpsertOne {
	_c.conflict = opts
	return &CodexAccountMetadataUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodexAccountMetadata.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodexAccountMetadataCreate) OnConflictColumns(columns ...string) *CodexAccountMetadataUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodexAccountMetadataUpsertOne{
		create: _c,
	}
}

type (
	// CodexAccountMetadataUpsertOne is the builder for "upsert"-ing
	//  one CodexAccountMetadata node.
	CodexAccountMetadataUpsertOne struct {
		create *CodexAccountMetadataCreate
	}

	// CodexAccountMetadataUpsert is the "OnConflict" setter.
	CodexAccountMetadataUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CodexAccountMetadataUpsert) SetUpdatedAt(v time.Time) *CodexAccountMetadataUpsert {
	u.Set(codexaccountmetadata.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsert) UpdateUpdatedAt() *CodexAccountMetadataUpsert {
	u.SetExcluded(codexaccountmetadata.FieldUpdatedAt)
	return u
}

// SetAuthName sets the "auth_name" field.
func (u *CodexAccountMetadataUpsert) SetAuthName(v string) *CodexAccountMetadataUpsert {
	u.Set(codexaccountmetadata.FieldAuthName, v)
	return u
}

// UpdateAuthName sets the "auth_name" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsert) UpdateAuthName() *CodexAccountMetadataUpsert {
	u.SetExcluded(codexaccountmetadata.FieldAuthName)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *CodexAccountMetadataUpsert) SetGroupID(v int64) *CodexAccountMetadataUpsert {
	u.Set(codexaccountmetadata.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsert) UpdateGroupID() *CodexAccountMetadataUpsert {
	u.SetExcluded(codexaccountmetadata.FieldGroupID)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *CodexAccountMetadataUpsert) ClearGroupID() *CodexAccountMetadataUpsert {
	u.SetNull(codexaccountmetadata.FieldGroupID)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *CodexAccountMetadataUpsert) SetDisplayName(v string) *CodexAccountMetadataUpsert {
	u.Set(codexaccountmetadata.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsert) UpdateDisplayName() *CodexAccountMetadataUpsert {
	u.SetExcluded(codexaccountmetadata.FieldDisplayName)
	return u
}

// SetNote sets the "note" field.
func (u *CodexAccountMetadataUpsert) SetNote(v string) *CodexAccountMetadataUpsert {
	u.Set(codexaccountmetadata.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsert) UpdateNote() *CodexAccountMetadataUpsert {
	u.SetExcluded(codexaccountmetadata.FieldNote)
	return u
}

// SetLocalTags sets the "local_tags" field.
func (u *CodexAccountMetadataUpsert) SetLocalTags(v []string) *CodexAccountMetadataUpsert {
	u.Set(codexaccountmetadata.FieldLocalTags, v)
	return u
}

// UpdateLocalTags sets the "local_tags" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsert) UpdateLocalTags() *CodexAccountMetadataUpsert {
	u.SetExcluded(codexaccountmetadata.FieldLocalTags)
	return u
}

// SetSettings sets the "settings" field.
func (u *CodexAccountMetadataUpsert) SetSettings(v map[string]interface{}) *CodexAccountMetadataUpsert {
	u.Set(codexaccountmetadata.FieldSettings, v)
	return u
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsert) UpdateSettings() *CodexAccountMetadataUpsert {
	u.SetExcluded(codexaccountmetadata.FieldSettings)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *CodexAccountMetadataUpsert) SetSortOrder(v int) *CodexAccountMetadataUpsert {
	u.Set(codexaccountmetadata.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsert) UpdateSortOrder() *CodexAccountMetadataUpsert {
	u.SetExcluded(codexaccountmetadata.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CodexAccountMetadataUpsert) AddSortOrder(v int) *CodexAccountMetadataUpsert {
	u.Add(codexaccountmetadata.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CodexAccountMetadata.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CodexAccountMetadataUpsertOne) UpdateNewValues() *CodexAccountMetadataUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(codexaccountmetadata.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodexAccountMetadata.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CodexAccountMetadataUpsertOne) Ignore() *CodexAccountMetadataUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodexAccountMetadataUpsertOne) DoNothing() *CodexAccountMetadataUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodexAccountMetadataCreate.OnConflict
// documentation for more info.
func (u *CodexAccountMetadataUpsertOne) Update(set func(*CodexAccountMetadataUpsert)) *CodexAccountMetadataUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodexAccountMetadataUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CodexAccountMetadataUpsertOne) SetUpdatedAt(v time.Time) *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsertOne) UpdateUpdatedAt() *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAuthName sets the "auth_name" field.
func (u *CodexAccountMetadataUpsertOne) SetAuthName(v string) *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.SetAuthName(v)
	})
}

// UpdateAuthName sets the "auth_name" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsertOne) UpdateAuthName() *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.UpdateAuthName()
	})
}

// SetGroupID sets the "group_id" field.
func (u *CodexAccountMetadataUpsertOne) SetGroupID(v int64) *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsertOne) UpdateGroupID() *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *CodexAccountMetadataUpsertOne) ClearGroupID() *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.ClearGroupID()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *CodexAccountMetadataUpsertOne) SetDisplayName(v string) *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsertOne) UpdateDisplayName() *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.UpdateDisplayName()
	})
}

// SetNote sets the "note" field.
func (u *CodexAccountMetadataUpsertOne) SetNote(v string) *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsertOne) UpdateNote() *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.UpdateNote()
	})
}

// SetLocalTags sets the "local_tags" field.
func (u *CodexAccountMetadataUpsertOne) SetLocalTags(v []string) *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.SetLocalTags(v)
	})
}

// UpdateLocalTags sets the "local_tags" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsertOne) UpdateLocalTags() *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.UpdateLocalTags()
	})
}

// SetSettings sets the "settings" field.
func (u *CodexAccountMetadataUpsertOne) SetSettings(v map[string]interface{}) *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.SetSettings(v)
	})
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsertOne) UpdateSettings() *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.UpdateSettings()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *CodexAccountMetadataUpsertOne) SetSortOrder(v int) *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CodexAccountMetadataUpsertOne) AddSortOrder(v int) *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsertOne) UpdateSortOrder() *CodexAccountMetadataUpsertOne {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *CodexAccountMetadataUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodexAccountMetadataCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodexAccountMetadataUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CodexAccountMetadataUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CodexAccountMetadataUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CodexAccountMetadataCreateBulk is the builder for creating many CodexAccountMetadata entities in bulk.
type CodexAccountMetadataCreateBulk struct {
	config
	err      error
	builders []*CodexAccountMetadataCreate
	conflict []sql.ConflictOption
}

// Save creates the CodexAccountMetadata entities in the database.
func (_c *CodexAccountMetadataCreateBulk) Save(ctx context.Context) ([]*CodexAccountMetadata, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CodexAccountMetadata, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CodexAccountMetadataMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CodexAccountMetadataCreateBulk) SaveX(ctx context.Context) []*CodexAccountMetadata {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexAccountMetadataCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexAccountMetadataCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodexAccountMetadata.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodexAccountMetadataUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CodexAccountMetadataCreateBulk) OnConflict(opts ...sql.ConflictOption) *CodexAccountMetadataUpsertBulk {
	_c.conflict = opts
	return &CodexAccountMetadataUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodexAccountMetadata.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodexAccountMetadataCreateBulk) OnConflictColumns(columns ...string) *CodexAccountMetadataUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodexAccountMetadataUpsertBulk{
		create: _c,
	}
}

// CodexAccountMetadataUpsertBulk is the builder for "upsert"-ing
// a bulk of CodexAccountMetadata nodes.
type CodexAccountMetadataUpsertBulk struct {
	create *CodexAccountMetadataCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CodexAccountMetadata.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CodexAccountMetadataUpsertBulk) UpdateNewValues() *CodexAccountMetadataUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(codexaccountmetadata.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodexAccountMetadata.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CodexAccountMetadataUpsertBulk) Ignore() *CodexAccountMetadataUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodexAccountMetadataUpsertBulk) DoNothing() *CodexAccountMetadataUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodexAccountMetadataCreateBulk.OnConflict
// documentation for more info.
func (u *CodexAccountMetadataUpsertBulk) Update(set func(*CodexAccountMetadataUpsert)) *CodexAccountMetadataUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodexAccountMetadataUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CodexAccountMetadataUpsertBulk) SetUpdatedAt(v time.Time) *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsertBulk) UpdateUpdatedAt() *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAuthName sets the "auth_name" field.
func (u *CodexAccountMetadataUpsertBulk) SetAuthName(v string) *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.SetAuthName(v)
	})
}

// UpdateAuthName sets the "auth_name" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsertBulk) UpdateAuthName() *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.UpdateAuthName()
	})
}

// SetGroupID sets the "group_id" field.
func (u *CodexAccountMetadataUpsertBulk) SetGroupID(v int64) *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsertBulk) UpdateGroupID() *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *CodexAccountMetadataUpsertBulk) ClearGroupID() *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.ClearGroupID()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *CodexAccountMetadataUpsertBulk) SetDisplayName(v string) *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsertBulk) UpdateDisplayName() *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.UpdateDisplayName()
	})
}

// SetNote sets the "note" field.
func (u *CodexAccountMetadataUpsertBulk) SetNote(v string) *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsertBulk) UpdateNote() *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.UpdateNote()
	})
}

// SetLocalTags sets the "local_tags" field.
func (u *CodexAccountMetadataUpsertBulk) SetLocalTags(v []string) *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.SetLocalTags(v)
	})
}

// UpdateLocalTags sets the "local_tags" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsertBulk) UpdateLocalTags() *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.UpdateLocalTags()
	})
}

// SetSettings sets the "settings" field.
func (u *CodexAccountMetadataUpsertBulk) SetSettings(v map[string]interface{}) *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.SetSettings(v)
	})
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsertBulk) UpdateSettings() *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.UpdateSettings()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *CodexAccountMetadataUpsertBulk) SetSortOrder(v int) *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CodexAccountMetadataUpsertBulk) AddSortOrder(v int) *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CodexAccountMetadataUpsertBulk) UpdateSortOrder() *CodexAccountMetadataUpsertBulk {
	return u.Update(func(s *CodexAccountMetadataUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *CodexAccountMetadataUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CodexAccountMetadataCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodexAccountMetadataCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodexAccountMetadataUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
