import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const sourcePath = resolve(__dirname, '../AccountsView.vue')
const source = readFileSync(sourcePath, 'utf8')
const styleSource = readFileSync(resolve(__dirname, '../../../style.css'), 'utf8')
const dataTableSource = readFileSync(resolve(__dirname, '../../../components/common/DataTable.vue'), 'utf8')
const externalSubscriptionMatchSource = readFileSync(resolve(__dirname, '../../../utils/externalSubscriptionMatch.ts'), 'utf8')
const externalQuotaSettingsModalSource = readFileSync(resolve(__dirname, '../../../components/admin/account/ExternalQuotaProgressSettingsModal.vue'), 'utf8')
const electricBorderPath = resolve(__dirname, '../../../components/common/ElectricBorder.vue')
const electricBorderSource = existsSync(electricBorderPath) ? readFileSync(electricBorderPath, 'utf8') : ''

describe('AccountsView external quota card metadata', () => {
  it('loads generic external subscription quota summaries for matching account cards', () => {
    expect(source).not.toContain("import buzzBalanceAPI")
    expect(source).toContain("import externalSubscriptionsAPI")
    expect(source).toContain("type ExternalSubscriptionStatus")
    expect(source).toContain("fetchExternalQuotaSummaries")
    expect(source).toContain("externalSubscriptionsAPI.getDisplayStatuses()")
    expect(source).toContain("getAccountExternalQuota")
    expect(source).not.toContain("externalSubscriptionsAPI.getStatuses()")
    expect(source).not.toContain("buzzBalanceAPI.getBalance()")
    expect(source).not.toContain("buildBuzzExternalQuota")
    expect(source).not.toContain("canShowBuzzExternalQuota")
  })

  it('renders external quota details inside the account card name area with provider links', () => {
    expect(source).toContain('data-testid="account-external-quota"')
    expect(source).toContain('account-external-quota-link')
    expect(source).toContain('account-card-name-main')
    expect(source).toContain('getAccountExternalQuota(row)?.formattedBalance')
    expect(source).toContain('getAccountExternalQuota(row)?.formattedExpiry')
    expect(source).not.toContain('data-testid="account-external-quota-card-progress"')
    expect(source).not.toContain('account-external-quota-card-progress')
    expect(source).toContain("localText('前往官网', 'Official site')")
    expect(source).toContain("return localText('长期', 'Long-term')")
    expect(source).not.toContain("return localText('未返回', 'Not returned')")
    expect(source).not.toContain("localText('打开', 'Open')")
    expect(styleSource).toContain('.account-card-name-main')
    expect(styleSource).toContain('.account-external-quota')
    expect(styleSource).toContain('width: 100%;')
    expect(styleSource).not.toMatch(/td\[data-column-key="name"\]\s*\{\s*padding-right: 9\.25rem !important;/)
  })

  it('matches generic external subscriptions from provider match_keywords instead of hardcoded provider branches', () => {
    expect(source).toContain('externalSubscriptionStatuses')
    expect(source).toContain('getMatchedExternalSubscription')
    expect(source).toContain("import { findMatchingExternalSubscription } from '@/utils/externalSubscriptionMatch'")
    expect(source).toContain('findMatchingExternalSubscription(account, externalSubscriptionStatuses.value)')
    expect(externalSubscriptionMatchSource).toContain('match_keywords')
    expect(externalSubscriptionMatchSource).toContain('GENERIC_MODEL_KEYWORDS')
    expect(externalSubscriptionMatchSource).toContain('buildExternalSubscriptionSearchText(account)')
    expect(source).not.toContain('buildExternalSearchText(account)')
    expect(source).toContain("rawchat: 'RawChat'")
    expect(source).not.toContain('canShowTCDMXExternalQuota')
    expect(source).not.toContain('canShowQLHazyCoderExternalQuota')
    expect(source).not.toContain("text.includes('buzzai.cc')")
    expect(source).not.toContain("if (provider === 'packycode'")
    expect(source).not.toContain("text.includes('xhyapi.com') || text.includes('xhyapi') || text.includes('xhy')")
  })

  it('keeps invalid external subscription tokens visible with a clear state', () => {
    expect(source).toContain('subscription.error_code')
    expect(source).toContain('isExternalSubscriptionInvalidToken')
    expect(source).toContain("localText('Token 失效', 'Token invalid')")
    expect(source).toContain("localText('请更新 Token', 'Update token')")
  })

  it('uses per-account quota progress settings instead of a global account-page switch', () => {
    expect(source).toContain("import ExternalQuotaProgressSettingsModal from '@/components/admin/account/ExternalQuotaProgressSettingsModal.vue'")
    expect(source).toContain("import UsageProgressBar from '@/components/account/UsageProgressBar.vue'")
    expect(source).toContain("import { useAccountExternalQuotaProgressSettings } from '@/composables/useAccountExternalQuotaProgressSettings'")
    expect(source).toContain('loadAccountExternalQuotaProgressSettings')
    expect(source).toContain('void loadAccountExternalQuotaProgressSettings()')
    expect(source).toContain('getAccountExternalQuotaProgressPreference(account, subscription)')
    expect(source).toContain('openExternalQuotaProgressSettings(row)')
    expect(source).toContain('saveExternalQuotaProgressSettings')
    expect(source).toContain('data-testid="account-external-quota-progress-action"')
    expect(source).toContain("localText('额度条', 'Quota bar')")
    expect(source).toContain('<ExternalQuotaProgressSettingsModal')
    expect(source).toContain(':settings="externalQuotaProgressSettings.current"')
    expect(externalQuotaSettingsModalSource).toContain('hasProviderTotal(props.subscription)')
    expect(externalQuotaSettingsModalSource).not.toContain('supportsExternalQuotaProgress(props.subscription)')
    expect(externalQuotaSettingsModalSource).toContain("form.mode = next.mode === 'custom_total' || hasStatusTotal.value")
    expect(source).not.toContain("import { useExternalQuotaProgressPreference } from '@/composables/useExternalQuotaProgressPreference'")
    expect(source).not.toContain('setExternalQuotaProgressEnabled(!externalQuotaProgressEnabled)')
    expect(source).not.toContain("localText('显示额度进度条', 'Show quota progress')")
  })

  it('places the external quota progress under the official usage window cell', () => {
    const usageCellIndex = source.indexOf('<template #cell-usage="{ row }">')
    const progressIndex = source.indexOf('data-testid="account-external-quota-usage-progress"')

    expect(usageCellIndex).toBeGreaterThan(0)
    expect(progressIndex).toBeGreaterThan(usageCellIndex)
    expect(progressIndex).toBeLessThan(source.indexOf('<template #cell-proxy="{ row }">'))
    expect(source.slice(usageCellIndex, progressIndex)).toContain('<AccountUsageCell')
    expect(source.slice(usageCellIndex, source.indexOf('<template #cell-proxy="{ row }">'))).toContain('<UsageProgressBar')
    expect(source).not.toContain('data-testid="account-external-quota-card-progress"')
    expect(source).not.toContain('account-external-quota-progress-track')
    expect(styleSource).not.toContain('.account-external-quota-progress-track')
    expect(styleSource).not.toContain('.account-external-quota-card-progress')
  })

  it('keeps account calling helpers hoisted before the immediate watcher runs', () => {
    expect(source).toContain('function hasLiveAccountActivity(row: Account)')
    expect(source).toContain('function syncAccountCallingGrace()')
    expect(source).not.toContain('const syncAccountCallingGrace = () =>')
    expect(source.indexOf('function syncAccountCallingGrace()')).toBeLessThan(
      source.indexOf('{ immediate: true }')
    )
  })

  it('renders a provider logo before each account card name and supports custom logo URLs', () => {
    expect(source).toContain('data-testid="account-provider-logo"')
    expect(source).toContain("import ProviderBrandIcon from '@/components/common/ProviderBrandIcon.vue'")
    expect(source).toContain('<ProviderBrandIcon')
    expect(source).toContain(':provider="getAccountLogoProvider(row)"')
    expect(source).toContain(':logo-url="getAccountCustomLogo(row)"')
    expect(source).not.toContain('account-provider-logo-img')
    expect(source).not.toContain('account-provider-logo-fallback')
    expect(source).toContain('custom_logo_url')
    expect(source).toContain('logo_url')
    expect(source).not.toContain("import { aiLogoUrlForProvider } from '@/utils/providerBrandIcon'")
  })

  it('keeps rate and priority together on the account card and supports quick priority edits', () => {
    expect(source).toContain('data-testid="account-rate-quick-adjust"')
    expect(source).toContain('data-testid="account-priority-quick-adjust"')
    expect(source).toContain('data-testid="account-card-controls"')
    expect(source).toContain("localText('降低优先级', 'Lower priority')")
    expect(source).toContain("localText('提高优先级', 'Raise priority')")
    expect(source).toContain('rateMultiplierMenu')
    expect(source).toContain('openRateMultiplierMenu(row, $event)')
    expect(source).toContain('adminAPI.accounts.updateRateMultiplier')
    expect(source).toContain('handleRateMultiplierSave')
    expect(source).toContain('handlePriorityQuickAdjust')
    expect(source).toContain('priorityUpdatingIds')
    expect(source).toContain('adminAPI.accounts.update(account.id, { priority: nextPriority })')
    expect(source).toContain('rate_multiplier')
    expect(source).not.toContain('account-rate-quick-adjust flex flex-col items-center')
    expect(source.indexOf('data-testid="account-rate-quick-adjust"')).toBeLessThan(
      source.indexOf('data-testid="account-priority-quick-adjust"')
    )
    expect(source).not.toContain('adminAPI.accounts.update(row.id, { rate_multiplier')
  })

  it('marks actively used account rows with the pasted canvas ElectricBorder treatment', () => {
    expect(electricBorderSource).not.toBe('')
    expect(electricBorderSource).toContain('canvas.getContext')
    expect(electricBorderSource).toContain('octavedNoise')
    expect(electricBorderSource).toContain('getRoundedRectPoint')
    expect(electricBorderSource).toContain('ResizeObserver')
    expect(electricBorderSource).toContain('requestAnimationFrame')
    expect(electricBorderSource).toContain('eb-glow-1')
    expect(electricBorderSource).toContain('ctx.lineWidth = 1')
    expect(electricBorderSource).not.toContain('ctx.lineWidth = props.thickness')
    expect(dataTableSource).toContain('name="row-overlay"')
    expect(source).toContain("import ElectricBorder from '@/components/common/ElectricBorder.vue'")
    expect(source).toContain('<template #row-overlay="{ row }">')
    expect(source).toContain('<ElectricBorder')
    expect(source).toContain('color="#c96442"')
    expect(source).toContain(':speed="1.5"')
    expect(source).toContain(':chaos="0.02"')
    expect(source).toContain(':border-radius="16"')
    expect(source).toContain(':thickness="2"')
    expect(source).toContain(':row-class="getAccountRowClass"')
    expect(source).toContain('getAccountRowClass')
    expect(source).toContain('isAccountCalling(row)')
    expect(source).toContain('current_concurrency')
    expect(source).toContain('active_sessions')
    expect(source).toContain('codex-account-card-calling')
    expect(source).toContain('account-electric-border')
    expect(styleSource).not.toContain('account-electric-border-spin')
    expect(styleSource).not.toContain('conic-gradient(')
  })

  it('keeps the active account border alive for one minute after a short activity gap', () => {
    expect(source).toContain('const ACCOUNT_CALLING_GRACE_MS = 60_000')
    expect(source).toContain('accountCallingGraceUntil')
    expect(source).toContain('accountCallingNow')
    expect(source).toContain('hasLiveAccountActivity(row)')
    expect(source).toContain('syncAccountCallingGrace')
    expect(source).toContain('startAccountCallingGraceTicker')
    expect(source).toContain('stopAccountCallingGraceTicker')
    expect(source).toContain('accountCallingGraceUntil.set(account.id, Date.now() + ACCOUNT_CALLING_GRACE_MS)')
    expect(source).toContain('return graceUntil > accountCallingNow.value')
    expect(source).toContain('watch(')
  })
})
