import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const sourcePath = resolve(__dirname, '../AccountsView.vue')
const source = readFileSync(sourcePath, 'utf8')
const styleSource = readFileSync(resolve(__dirname, '../../../style.css'), 'utf8')
const targetedRepairSource = readFileSync(resolve(__dirname, '../../../styles/targeted-visual-repair.css'), 'utf8')
const bulkActionsSource = readFileSync(resolve(__dirname, '../../../components/admin/account/AccountBulkActionsBar.vue'), 'utf8')
const accountActionMenuSource = readFileSync(resolve(__dirname, '../../../components/admin/account/AccountActionMenu.vue'), 'utf8')
const dataTableSource = readFileSync(resolve(__dirname, '../../../components/common/DataTable.vue'), 'utf8')
const iconSource = readFileSync(resolve(__dirname, '../../../components/icons/Icon.vue'), 'utf8')
const monitorCapacitySource = readFileSync(resolve(__dirname, '../../../components/user/monitor/MonitorCapacityOverview.vue'), 'utf8')
const externalSubscriptionMatchSource = readFileSync(resolve(__dirname, '../../../utils/externalSubscriptionMatch.ts'), 'utf8')
const externalQuotaSettingsModalSource = readFileSync(resolve(__dirname, '../../../components/admin/account/ExternalQuotaProgressSettingsModal.vue'), 'utf8')
const accountsAPISource = readFileSync(resolve(__dirname, '../../../api/admin/accounts.ts'), 'utf8')
const electricBorderPath = resolve(__dirname, '../../../components/common/ElectricBorder.vue')
const electricBorderSource = existsSync(electricBorderPath) ? readFileSync(electricBorderPath, 'utf8') : ''

const cssBlock = (content: string, selector: string): string => {
  const start = content.indexOf(`${selector} {`)
  expect(start, `Expected CSS selector ${selector}`).toBeGreaterThanOrEqual(0)
  const end = content.indexOf('\n}', start)
  expect(end, `Expected CSS selector ${selector} to close`).toBeGreaterThan(start)
  return content.slice(start, end + 2)
}

const lastCssBlock = (content: string, selector: string): { block: string; start: number } => {
  const start = content.lastIndexOf(`${selector} {`)
  expect(start, `Expected CSS selector ${selector}`).toBeGreaterThanOrEqual(0)
  const end = content.indexOf('\n}', start)
  expect(end, `Expected CSS selector ${selector} to close`).toBeGreaterThan(start)
  return { block: content.slice(start, end + 2), start }
}

describe('AccountsView external quota card metadata', () => {
  it('loads generic external subscription quota summaries for matching account cards', () => {
    expect(source).not.toContain("import buzzBalanceAPI")
    expect(source).toContain("import externalSubscriptionsAPI")
    expect(source).toContain("type ExternalSubscriptionStatus")
    expect(source).toContain("fetchExternalQuotaSummaries")
    expect(source).toContain("externalSubscriptionsAPI.getDisplayStatuses()")
    expect(source).toContain("getAccountExternalQuota")
    expect(source).not.toContain("externalSubscriptionsAPI.getStatuses()")
    expect(source).not.toContain("buzzBalanceAPI.getBalance()")
    expect(source).not.toContain("buildBuzzExternalQuota")
    expect(source).not.toContain("canShowBuzzExternalQuota")
  })

  it('renders external quota details inside the account card name area with provider links', () => {
    expect(source).toContain('data-testid="account-external-quota"')
    expect(source).toContain('account-external-quota-link')
    expect(source).toContain('account-external-quota-row account-external-quota-row-head')
    expect(source).toContain('account-external-quota-label')
    expect(source).toContain('account-external-quota-value')
    expect(source).toContain('account-card-name-main')
    expect(source).toContain('getAccountExternalQuota(row)?.formattedBalance')
    expect(source).toContain('getAccountExternalQuota(row)?.formattedExpiry')
    expect(source).not.toContain('data-testid="account-external-quota-card-progress"')
    expect(source).not.toContain('account-external-quota-card-progress')
    expect(source).toContain("localText('前往官网', 'Official site')")
    expect(source).toContain("return localText('长期', 'Long-term')")
    expect(source).not.toContain("return localText('未返回', 'Not returned')")
    expect(source).not.toContain("localText('打开', 'Open')")
    expect(targetedRepairSource).toContain('.account-card-name-main')
    expect(targetedRepairSource).toContain('.account-external-quota')
    expect(targetedRepairSource).toContain('.account-external-quota-row')
    expect(targetedRepairSource).toContain('.account-external-quota-value')
    expect(targetedRepairSource).toContain('width: 100%;')
    expect(targetedRepairSource).toContain('border: 0 !important;')
    expect(targetedRepairSource).toContain('background: transparent !important;')
    expect(styleSource).not.toMatch(/td\[data-column-key="name"\]\s*\{\s*padding-right: 9\.25rem !important;/)
  })

  it('matches generic external subscriptions from provider match_keywords instead of hardcoded provider branches', () => {
    expect(source).toContain('externalSubscriptionStatuses')
    expect(source).toContain('getMatchedExternalSubscription')
    expect(source).toContain("import { findMatchingExternalSubscription } from '@/utils/externalSubscriptionMatch'")
    expect(source).toContain('findMatchingExternalSubscription(account, externalSubscriptionStatuses.value)')
    expect(externalSubscriptionMatchSource).toContain('match_keywords')
    expect(externalSubscriptionMatchSource).toContain('GENERIC_MODEL_KEYWORDS')
    expect(externalSubscriptionMatchSource).toContain('buildExternalSubscriptionSearchText(account)')
    expect(source).not.toContain('buildExternalSearchText(account)')
    expect(source).toContain("rawchat: 'RawChat'")
    expect(source).not.toContain('canShowTCDMXExternalQuota')
    expect(source).not.toContain('canShowQLHazyCoderExternalQuota')
    expect(source).not.toContain("text.includes('buzzai.cc')")
    expect(source).not.toContain("if (provider === 'packycode'")
    expect(source).not.toContain("text.includes('xhyapi.com') || text.includes('xhyapi') || text.includes('xhy')")
  })

  it('keeps invalid external subscription tokens visible with a clear state', () => {
    expect(source).toContain('subscription.error_code')
    expect(source).toContain('isExternalSubscriptionInvalidToken')
    expect(source).toContain("localText('Token 失效', 'Token invalid')")
    expect(source).toContain("localText('请更新 Token', 'Update token')")
  })

  it('uses per-account quota progress settings instead of a global account-page switch', () => {
    expect(source).toContain("import ExternalQuotaProgressSettingsModal from '@/components/admin/account/ExternalQuotaProgressSettingsModal.vue'")
    expect(source).toContain("import UsageProgressBar from '@/components/account/UsageProgressBar.vue'")
    expect(source).toContain("import { buildAccountExternalQuotaProgressPreferenceKey, useAccountExternalQuotaProgressSettings } from '@/composables/useAccountExternalQuotaProgressSettings'")
    expect(source).toContain('loadAccountExternalQuotaProgressSettings')
    expect(source).toContain('void loadAccountExternalQuotaProgressSettings()')
    expect(source).toContain('getAccountExternalQuotaProgressPreference(account, subscription)')
    expect(source).toContain('buildAccountExternalQuotaProgressPreferenceKey(account, subscription)')
    expect(source).toContain('account.external_quota_token_stats?.[preferenceKey]')
    expect(source).toContain('openExternalQuotaProgressSettings(row)')
    expect(source).toContain('getAccountExternalQuotaProgressPreference(account, subscription ?? null)')
    expect(source).toContain('setAccountExternalQuotaProgressPreference(')
    expect(source).not.toContain('if (!subscription) return')
    expect(source).toContain('saveExternalQuotaProgressSettings')
    expect(source).toContain('data-testid="account-external-quota-progress-action"')
    expect(source).toContain("localText('额度条', 'Quota bar')")
    expect(source).not.toContain('v-if="getMatchedExternalSubscription(row)"')
    expect(source).toContain('<ExternalQuotaProgressSettingsModal')
    expect(source).toContain(':settings="externalQuotaProgressSettings.current"')
    expect(externalQuotaSettingsModalSource).toContain('hasProviderTotal(props.subscription)')
    expect(externalQuotaSettingsModalSource).not.toContain('supportsExternalQuotaProgress(props.subscription)')
    expect(externalQuotaSettingsModalSource).toContain("form.mode = next.mode === 'token_total' || next.mode === 'custom_total' || hasStatusTotal.value")
    expect(source).not.toContain("import { useExternalQuotaProgressPreference } from '@/composables/useExternalQuotaProgressPreference'")
    expect(source).not.toContain('setExternalQuotaProgressEnabled(!externalQuotaProgressEnabled)')
    expect(source).not.toContain("localText('显示额度进度条', 'Show quota progress')")
  })

  it('renders a per-account schedule lock next to the scheduling control without changing schedulable directly', () => {
    const lockPath = iconSource.match(/lock: '([^']+)'/)?.[1]
    const unlockPath = iconSource.match(/unlock: '([^']+)'/)?.[1]

    expect(source).toContain('data-testid="account-schedule-lock-action"')
    expect(source).toContain('row.schedule_locked')
    expect(source).toContain('account-schedule-lock-action-locked')
    expect(source).toContain('border-transparent bg-transparent text-[var(--anthropic-fg)]')
    expect(source).not.toContain('border-[var(--anthropic-fg)] bg-[var(--anthropic-fg)] text-[var(--anthropic-page)]')
    expect(lockPath).toBeDefined()
    expect(unlockPath).toBeDefined()
    expect(unlockPath).not.toBe(lockPath)
    expect(unlockPath).toContain('M13.5 10.5V6.75a4.5 4.5 0 119 0v1.5')
    expect(unlockPath).toContain('M6.75 10.5h10.5')
    expect(source).toContain('handleToggleScheduleLock(row)')
    expect(source).toContain('togglingScheduleLock')
    expect(source).toContain('adminAPI.accounts.setScheduleLocked')
    expect(source).toContain('updateScheduleLockedInList([a.id], updated?.schedule_locked ?? nextLocked)')
    expect(accountsAPISource).toContain('setScheduleLocked')
    expect(accountsAPISource).toContain('/schedule-lock')
  })

  it('adds a token quota progress template with account-local usage stats and a refresh action', () => {
    expect(externalQuotaSettingsModalSource).toContain("value=\"token_total\"")
    expect(externalQuotaSettingsModalSource).toContain("localText('Token 用量 / 总量', 'Token usage / total')")
    expect(externalQuotaSettingsModalSource).toContain("localText('Token 总量', 'Token total')")
    expect(externalQuotaSettingsModalSource).toContain("localText('统计窗口', 'Usage window')")
    expect(externalQuotaSettingsModalSource).toContain("localText('刷新统计', 'Refresh stats')")
    expect(externalQuotaSettingsModalSource).toContain('data-testid="external-quota-progress-refresh-token-window"')
    expect(externalQuotaSettingsModalSource).toContain('function refreshTokenWindow()')
    expect(externalQuotaSettingsModalSource).toContain('new Date().toISOString()')
    expect(externalQuotaSettingsModalSource).toContain('new Date(Math.min(parsed.getTime(), now)).toISOString()')
    expect(externalQuotaSettingsModalSource).toContain('tokenWindowText')
    expect(externalQuotaSettingsModalSource).not.toContain('type="datetime-local"')
    expect(externalQuotaSettingsModalSource).toContain('buildAccountExternalQuotaProgressPreferenceKey(props.account, props.subscription ?? null)')
    expect(externalQuotaSettingsModalSource).toContain('props.account.external_quota_token_stats?.[key]')
    expect(externalQuotaSettingsModalSource).toContain("next.mode === 'token_total'")
    expect(source).toContain('@save="saveExternalQuotaProgressSettings"')
    expect(source).toContain('await load()')
    expect(source).toContain('formatExternalTokens')
    expect(source).toContain("progress?.unit === 'tokens'")
  })

  it('places the external quota progress under the official usage window cell', () => {
    const usageCellIndex = source.indexOf('<template #cell-usage="{ row }">')
    const progressIndex = source.indexOf('data-testid="account-external-quota-usage-progress"')

    expect(usageCellIndex).toBeGreaterThan(0)
    expect(progressIndex).toBeGreaterThan(usageCellIndex)
    expect(progressIndex).toBeLessThan(source.indexOf('<template #cell-proxy="{ row }">'))
    expect(source.slice(usageCellIndex, progressIndex)).toContain('<AccountUsageCell')
    expect(source.slice(usageCellIndex, source.indexOf('<template #cell-proxy="{ row }">'))).toContain('<UsageProgressBar')
    expect(source).not.toContain('data-testid="account-external-quota-card-progress"')
    expect(source).not.toContain('account-external-quota-progress-track')
    expect(styleSource).not.toContain('.account-external-quota-progress-track')
    expect(styleSource).not.toContain('.account-external-quota-card-progress')
  })

  it('keeps account calling helpers hoisted before the immediate watcher runs', () => {
    expect(source).toContain('function hasLiveAccountActivity(row: Account)')
    expect(source).toContain('function syncAccountCallingGrace()')
    expect(source).not.toContain('const syncAccountCallingGrace = () =>')
    expect(source.indexOf('function syncAccountCallingGrace()')).toBeLessThan(
      source.indexOf('{ immediate: true }')
    )
  })

  it('renders a provider logo before each account card name and supports custom logo URLs', () => {
    expect(source).toContain('data-testid="account-provider-logo"')
    expect(source).toContain("import ProviderBrandIcon from '@/components/common/ProviderBrandIcon.vue'")
    expect(source).toContain('<ProviderBrandIcon')
    expect(source).toContain(':provider="getAccountLogoProvider(row)"')
    expect(source).toContain(':logo-url="getAccountCustomLogo(row)"')
    expect(source).not.toContain('account-provider-logo-img')
    expect(source).not.toContain('account-provider-logo-fallback')
    expect(source).toContain('custom_logo_url')
    expect(source).toContain('logo_url')
    expect(source).not.toContain("import { aiLogoUrlForProvider } from '@/utils/providerBrandIcon'")
  })

  it('keeps rate and priority together on the account card and supports quick priority edits', () => {
    expect(source).toContain('data-testid="account-rate-quick-adjust"')
    expect(source).toContain('data-testid="account-priority-quick-adjust"')
    expect(source).toContain('data-testid="account-card-controls"')
    expect(source).toContain("localText('降低优先级', 'Lower priority')")
    expect(source).toContain("localText('提高优先级', 'Raise priority')")
    expect(source).toContain('rateMultiplierMenu')
    expect(source).toContain('openRateMultiplierMenu(row, $event)')
    expect(source).toContain('adminAPI.accounts.updateRateMultiplier')
    expect(source).toContain('handleRateMultiplierSave')
    expect(source).toContain('handlePriorityQuickAdjust')
    expect(source).toContain('priorityUpdatingIds')
    expect(source).toContain('adminAPI.accounts.update(account.id, { priority: nextPriority })')
    expect(source).toContain('rate_multiplier')
    expect(source).not.toContain('account-rate-quick-adjust flex flex-col items-center')
    expect(source.indexOf('data-testid="account-rate-quick-adjust"')).toBeLessThan(
      source.indexOf('data-testid="account-priority-quick-adjust"')
    )
    expect(source).not.toContain('adminAPI.accounts.update(row.id, { rate_multiplier')
  })

  it('keeps account-card inline actions as text links without svg chrome', () => {
    const actionsTemplate = source.slice(
      source.indexOf('<template #cell-actions="{ row }">'),
      source.indexOf('</template>', source.indexOf('<template #cell-actions="{ row }">')),
    )

    expect(actionsTemplate).toContain('account-card-text-action')
    expect(actionsTemplate).not.toContain('<svg')
    expect(actionsTemplate).not.toContain('<Icon name="chartBar"')
    expect(targetedRepairSource).toContain('[data-column-key="actions"] svg')
    expect(targetedRepairSource).toContain('display: none !important;')
    expect(targetedRepairSource).toContain('text-decoration-color: transparent !important;')
    expect(targetedRepairSource).toContain('text-decoration-color: currentColor !important;')
  })

  it('treats account-card More as a second-level highlighted dropdown with a caret', () => {
    const actionsTemplate = source.slice(
      source.indexOf('<template #cell-actions="{ row }">'),
      source.indexOf('</template>', source.indexOf('<template #cell-actions="{ row }">')),
    )

    expect(actionsTemplate).toContain('account-card-more-trigger')
    expect(actionsTemplate).toContain('aria-haspopup="menu"')
    expect(actionsTemplate).toContain('@mouseenter="openMenu(row, $event)"')
    expect(actionsTemplate).toContain('@pointerenter="openMenu(row, $event)"')
    expect(actionsTemplate).toContain('@mouseleave="scheduleMenuClose"')
    expect(actionsTemplate).toContain('@pointerleave="scheduleMenuClose"')
    expect(actionsTemplate).toContain('@focus="openMenu(row, $event)"')
    expect(actionsTemplate).toContain('@blur="scheduleMenuClose"')
    expect(actionsTemplate).toContain(':aria-expanded="menu.show && menu.acc?.id === row.id ?')
    expect(actionsTemplate).toContain('account-card-more-trigger-open')
    expect(actionsTemplate).toContain('account-card-text-caret')
    expect(source).toContain('const cancelMenuClose = () =>')
    expect(source).toContain('const scheduleMenuClose = () =>')
    expect(source).toContain('@menu-enter="cancelMenuClose"')
    expect(source).toContain('@menu-leave="scheduleMenuClose"')
    expect(accountActionMenuSource).toContain('action-menu-content dropdown-highlight-menu account-card-action-menu')
    expect(accountActionMenuSource).toContain("@mouseenter=\"emit('menu-enter')\"")
    expect(accountActionMenuSource).toContain("@mouseleave=\"emit('menu-leave')\"")
    expect(accountActionMenuSource).toContain('class="dropdown-highlight-item flex w-full items-center gap-2 text-sm"')
    expect(accountActionMenuSource).not.toContain('hover:bg-[var(--anthropic-raised)]')
    expect(targetedRepairSource).toContain('#app .app-layout-content .accounts-table-page .table-wrapper [data-column-key="actions"] .account-card-more-trigger')
    expect(targetedRepairSource).toContain('display: inline-flex !important;')
    expect(targetedRepairSource).toContain('height: 1rem !important;')
    expect(targetedRepairSource).toContain('.account-card-text-caret::before')
    expect(targetedRepairSource).toContain('.account-card-more-trigger-open .account-card-text-caret')
    expect(targetedRepairSource).toContain('[data-testid="admin-accounts-button-open-menu-row-event"]:focus-visible .account-card-text-caret')
  })

  it('keeps account-card usage stats and platform chips transparent while restoring progress width', () => {
    expect(targetedRepairSource).toContain('.usage-progress-stat')
    expect(targetedRepairSource).toContain('background: transparent !important;')
    expect(targetedRepairSource).toContain('width: clamp(6rem, 100%, 11rem) !important;')
    expect(targetedRepairSource).toContain('flex: 1 1 auto !important;')
    expect(targetedRepairSource).toContain('min-width: 6rem !important;')
    expect(targetedRepairSource).toContain('.platform-type-badge__platform')
    expect(targetedRepairSource).toContain('.group-token-label')
    expect(targetedRepairSource).toContain('margin-left: 0 !important;')
    expect(targetedRepairSource).toContain('tr.codex-account-card-calling [data-column-key="capacity"]')
    expect(targetedRepairSource).toContain('color: var(--anthropic-info) !important;')
  })

  it('keeps schedule-lock buttons transparent so only the lock glyph turns black', () => {
    expect(source).toContain('account-schedule-lock-action-locked border-transparent bg-transparent text-[var(--anthropic-fg)]')
    expect(source).not.toContain('account-schedule-lock-action-locked border-[var(--anthropic-fg)] bg-[var(--anthropic-fg)]')
    expect(source).not.toContain('account-schedule-lock-action-locked border-[var(--anthropic-fg)] bg-[var(--anthropic-fg)] text-[var(--anthropic-page)]')
    const lockedBlock = cssBlock(targetedRepairSource, '#app .app-layout-content .accounts-table-page .account-schedule-lock-action-locked')
    expect(lockedBlock).toContain('border-color: transparent !important;')
    expect(lockedBlock).toContain('background: transparent !important;')
    expect(lockedBlock).toContain('color: var(--anthropic-fg) !important;')
    const lockedSvgBlock = cssBlock(targetedRepairSource, '#app .app-layout-content .accounts-table-page .account-schedule-lock-action-locked svg')
    expect(lockedSvgBlock).toContain('color: var(--anthropic-fg) !important;')
    expect(lockedSvgBlock).toContain('stroke: currentColor !important;')
    const hoverBlock = cssBlock(targetedRepairSource, '#app .app-layout-content .accounts-table-page .account-schedule-lock-action:focus-visible')
    expect(hoverBlock).toContain('background: transparent !important;')
    expect(hoverBlock).toContain('color: var(--anthropic-fg) !important;')
  })

  it('marks active and paused account rows with theme card color classes instead of ElectricBorder', () => {
    expect(electricBorderSource).not.toBe('')
    expect(dataTableSource).toContain('name="row-overlay"')
    expect(source).not.toContain("import ElectricBorder from '@/components/common/ElectricBorder.vue'")
    expect(source).not.toContain('<template #row-overlay="{ row }">')
    expect(source).not.toContain('<ElectricBorder')
    expect(source).not.toContain('color="#c96442"')
    expect(source).toContain(':row-class="getAccountRowClass"')
    expect(source).toContain('getAccountRowClass')
    expect(source).toContain('isAccountCalling(row)')
    expect(source).toContain('current_concurrency')
    expect(source).toContain('active_sessions')
    expect(source).toContain('codex-account-card-calling')
    expect(source).toContain('codex-account-card-paused')
    expect(source).toContain("row.status === 'active' && !row.schedulable")
    expect(source).not.toContain('account-electric-border')
    expect(styleSource).not.toContain('account-electric-border-spin')
    expect(styleSource).not.toContain('conic-gradient(')
    expect(targetedRepairSource).toContain('.accounts-table-page .table-wrapper tbody tr.codex-account-card-calling')
    expect(targetedRepairSource).toContain('background: var(--account-card-bg) !important;')
    expect(targetedRepairSource).toContain('.accounts-table-page .account-electric-border-canvas')
    expect(targetedRepairSource).toContain('display: none !important;')
    expect(targetedRepairSource).not.toContain('background: var(--anthropic-learn-personal) !important;')
    expect(targetedRepairSource).not.toContain('background: var(--anthropic-learn-build) !important;')
  })

  it('keeps the active account border alive for one minute after a short activity gap', () => {
    expect(source).toContain('const ACCOUNT_CALLING_GRACE_MS = 60_000')
    expect(source).toContain('accountCallingGraceUntil')
    expect(source).toContain('accountCallingNow')
    expect(source).toContain('hasLiveAccountActivity(row)')
    expect(source).toContain('syncAccountCallingGrace')
    expect(source).toContain('startAccountCallingGraceTicker')
    expect(source).toContain('stopAccountCallingGraceTicker')
    expect(source).toContain('accountCallingGraceUntil.set(account.id, Date.now() + ACCOUNT_CALLING_GRACE_MS)')
    expect(source).toContain('return graceUntil > accountCallingNow.value')
    expect(source).toContain('watch(')
  })

  it('keeps admin account cards on the Anthropic domain-card hover taxonomy', () => {
    const accountRowHoverBlock = cssBlock(
      targetedRepairSource,
      '#app .app-layout-content .accounts-table-page .table-wrapper tbody tr:hover'
    )
    const themedGlobalHoverBlock = lastCssBlock(
      targetedRepairSource,
      ':root:is(.theme-cloudflare, .theme-anthropic, [data-theme="cloudflare"], [data-theme="anthropic"]) #app .app-layout-content .accounts-table-page .table-wrapper tbody tr:hover'
    )
    const finalAccountRowHover = lastCssBlock(
      targetedRepairSource,
      '#app .app-layout-content .accounts-table-page .table-wrapper tbody tr:hover'
    )

    expect(accountRowHoverBlock).toContain('border-color: var(--anthropic-cookbook-border-hover) !important;')
    expect(accountRowHoverBlock).toContain('background: var(--account-card-hover-bg) !important;')
    expect(accountRowHoverBlock).toContain('box-shadow: 0 8px 28px rgba(0, 0, 0, 0.08) !important;')
    expect(accountRowHoverBlock).toContain('transform: none')
    expect(targetedRepairSource).not.toContain('--account-card-resting-bg')
    expect(targetedRepairSource).not.toContain('tbody:has(tr:hover) tr:not(:hover)')
    expect(accountRowHoverBlock).not.toContain('translate3d')
    expect(accountRowHoverBlock).not.toContain('rgba(20, 20, 19, 0.035)')
    expect(accountRowHoverBlock).not.toContain('var(--atelier-ui-hover-surface)')
    expect(accountRowHoverBlock).not.toContain('var(--atelier-butter')
    expect(accountRowHoverBlock).not.toMatch(/(?:amber|yellow)/i)
    expect(accountRowHoverBlock).not.toMatch(/(?:^|\n)\s*(?:color|-webkit-text-fill-color)\s*:/)
    expect(themedGlobalHoverBlock.block).toContain('transform: none !important;')
    expect(themedGlobalHoverBlock.block).toContain('box-shadow: 0 8px 28px rgba(0, 0, 0, 0.08) !important;')
    expect(themedGlobalHoverBlock.block).toContain('background: var(--account-card-hover-bg) !important;')
    expect(themedGlobalHoverBlock.block).not.toContain('var(--atelier-material-shadow')
    expect(themedGlobalHoverBlock.block).not.toContain('rgba(20, 20, 19, 0.024)')
    expect(themedGlobalHoverBlock.block).not.toContain('translate')
    expect(themedGlobalHoverBlock.block).not.toMatch(/(?:^|\n)\s*(?:color|-webkit-text-fill-color)\s*:/)
    expect(finalAccountRowHover.start).toBeGreaterThan(
      targetedRepairSource.indexOf('#app .app-layout-content .accounts-table-page .table-wrapper tbody tr:hover')
    )
    expect(finalAccountRowHover.block).toContain('border-color: var(--anthropic-cookbook-border-hover) !important;')
    expect(finalAccountRowHover.block).toContain('background: var(--account-card-hover-bg) !important;')
    expect(finalAccountRowHover.block).toContain('transform: none !important;')
    expect(finalAccountRowHover.block).toContain('box-shadow: 0 8px 28px rgba(0, 0, 0, 0.08) !important;')
    expect(finalAccountRowHover.block).not.toContain('translate3d')
    expect(finalAccountRowHover.block).not.toContain('rgba(20, 20, 19, 0.035)')
    expect(finalAccountRowHover.block).not.toContain('var(--atelier-ui-hover-surface)')
    expect(finalAccountRowHover.block).not.toContain('var(--atelier-butter')
    expect(finalAccountRowHover.block).not.toMatch(/(?:amber|yellow)/i)
    expect(finalAccountRowHover.block).not.toMatch(/(?:^|\n)\s*(?:color|-webkit-text-fill-color)\s*:/)
  })

  it('keeps shared capacity cards on the linked Anthropic hover contract without lift', () => {
    const capacityHoverBlock = cssBlock(monitorCapacitySource, '.monitor-capacity-card:hover')

    expect(capacityHoverBlock).toContain('border-color: var(--anthropic-cookbook-border-hover, rgba(20, 19, 19, 0.16));')
    expect(capacityHoverBlock).toContain('background: var(--anthropic-cookbook-hover, #f5f4ed);')
    expect(capacityHoverBlock).toContain('box-shadow: 0 8px 28px rgba(0, 0, 0, 0.08);')
    expect(capacityHoverBlock).not.toContain('transform:')
    expect(capacityHoverBlock).not.toContain('var(--atelier-ui-hover-surface)')
    expect(capacityHoverBlock).not.toContain('color-mix(in srgb, var(--atelier-ink) 24%')
    expect(monitorCapacitySource).toContain('.monitor-capacity-card:hover .monitor-capacity-metric-tile')
    expect(monitorCapacitySource).toContain('background: var(--anthropic-cookbook-hover, #f5f4ed);')
    expect(monitorCapacitySource).toContain('.monitor-capacity-overview:has(.monitor-capacity-card:hover) .monitor-capacity-card:not(:hover) .monitor-capacity-metric-tile')
    expect(monitorCapacitySource).toContain('background: var(--anthropic-raised, #e8e6dc);')
  })

  it('keeps a single filtered bulk update entry and selected-row bulk edit entry', () => {
    expect(bulkActionsSource).not.toContain('data-testid="account-bulk-edit-filtered-empty"')
    expect((bulkActionsSource.match(/data-testid="account-bulk-edit-filtered"/g) || [])).toHaveLength(1)
    expect(bulkActionsSource).toContain('data-testid="account-bulk-edit-selected"')
    expect(bulkActionsSource).toContain("@click=\"$emit('edit-filtered')\"")
    expect(bulkActionsSource).toContain('class="btn btn-primary btn-sm account-bulk-primary-action"')
    expect(bulkActionsSource).toContain('class="btn btn-secondary btn-sm account-bulk-action"')
    expect(bulkActionsSource).not.toContain('btn btn-danger btn-sm')
    expect(bulkActionsSource).not.toContain('btn btn-success btn-sm')
    expect(bulkActionsSource).not.toContain('btn btn-warning btn-sm')
    expect(styleSource).toContain('.app-layout-content :where(.btn-primary')
    expect(targetedRepairSource).toContain('.app-layout-content :where(.btn-primary')
  })
})
