import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { describe, expect, it } from 'vitest'

const componentSource = readFileSync(resolve(__dirname, '../AISearchBox.vue'), 'utf8')
const panelPath = resolve(__dirname, '../AISearchPanel.vue')
const panelSource = existsSync(panelPath) ? readFileSync(panelPath, 'utf8') : ''
const appSource = readFileSync(resolve(__dirname, '../../../App.vue'), 'utf8')
const appStoreSource = readFileSync(resolve(__dirname, '../../../stores/app.ts'), 'utf8')
const styleSource = readFileSync(resolve(__dirname, '../../../style.css'), 'utf8')
const viteConfigSource = readFileSync(resolve(__dirname, '../../../../vite.config.ts'), 'utf8')
const vitestConfigSource = readFileSync(resolve(__dirname, '../../../../vitest.config.ts'), 'utf8')

const cssBlock = (source: string, selector: string) => {
  const blockStart = `${selector} {`
  let selectorIndex = source.startsWith(blockStart) ? 0 : source.indexOf(`\n${selector} {`)
  if (selectorIndex > 0) selectorIndex += 1
  expect(selectorIndex).toBeGreaterThan(-1)
  const openBraceIndex = source.indexOf('{', selectorIndex)
  let depth = 0
  for (let index = openBraceIndex; index < source.length; index += 1) {
    const char = source[index]
    if (char === '{') depth += 1
    if (char === '}') {
      depth -= 1
      if (depth === 0) return source.slice(openBraceIndex + 1, index)
    }
  }
  throw new Error(`CSS block not closed for ${selector}`)
}

describe('Creepee Obsidian bridge source contract', () => {
  it('keeps the resident Ask Creepee trigger and opens the global sidecar', () => {
    expect(componentSource).toContain('class="ai-search-trigger"')
    expect(componentSource).toContain('aria-label="Ask Creepee"')
    expect(componentSource).toContain('title="Ask Creepee"')
    expect(componentSource).toContain('class="ai-search-trigger-avatar"')
    expect(componentSource).toContain('src="https://www.svgrepo.com/show/306960/webpack.svg"')
    expect(componentSource).toContain('aria-hidden="true"')
    expect(componentSource).not.toContain("import CreepeeAvatar from '@/components/layout/CreepeeAvatar.vue'")
    expect(componentSource).not.toContain('<CreepeeAvatar')
    expect(componentSource).toContain('Ask Creepee')
    expect(componentSource).toContain('appStore.openAISearchPanel()')
    expect(componentSource).not.toContain('claudeCodeCrabAvatar')
    expect(componentSource).not.toContain('/brand/claudecode-color.png')
    expect(componentSource).not.toContain('Ask AI')
    expect(componentSource).not.toContain('Ask Creepee.ai')
  })

  it('uses the requested Webpack SVG for the trigger logo', () => {
    expect(componentSource).toContain('https://www.svgrepo.com/show/306960/webpack.svg')
    expect(componentSource).toContain('<img')
    expect(componentSource).toContain('alt=""')
    expect(componentSource).not.toContain('CREEPEE_SPRITE')
    expect(componentSource).not.toContain('data-testid="creepee-avatar-canvas"')
    expect(componentSource).not.toContain('requestAnimationFrame(drawCreepeeFrame)')
  })

  it('renders Obsidian Codex Bridge in the sidecar iframe instead of Cloudflare AI Search', () => {
    expect(panelSource).toContain('data-testid="obsidian-bridge-frame"')
    expect(panelSource).toContain('ref="bridgeFrameRef"')
    expect(panelSource).toContain(':src="bridgeUrl"')
    expect(panelSource).toContain('@load="handleBridgeFrameLoad"')
    expect(panelSource).toContain('VITE_OBSIDIAN_CODEX_BRIDGE_URL')
    expect(panelSource).toContain('https://obsi.creeperxco.cn/')
    expect(panelSource).not.toContain('http://127.0.0.1:43110/')
    expect(panelSource).not.toContain('http://localhost')
    expect(panelSource).toContain('Obsidian Codex Bridge')
    expect(panelSource).toContain("authAPI.issueCreepeeSSOTicket()")
    expect(panelSource).toContain("type: 'sub2api:creepee-sso'")
    expect(panelSource).toContain('bridgeFrameRef.value?.contentWindow?.postMessage')
    expect(panelSource).toContain('bridgeFrameReady')
    expect(panelSource).toContain('function handleBridgeFrameLoad')
    expect(panelSource).toContain('bridgeOrigin')
    expect(panelSource).toContain('ticketIssuedForOpen')
    expect(panelSource).not.toContain('class="ai-search-panel-head"')
    expect(panelSource).not.toContain('class="ai-search-panel-brand"')
    expect(panelSource).not.toContain('class="ai-search-panel-avatar"')
    expect(panelSource).not.toContain('class="ai-search-panel-title"')
    expect(panelSource).not.toContain('class="ai-search-panel-subtitle"')
    expect(panelSource).not.toContain('ticket=')
    expect(panelSource).not.toContain('auth_token')
    expect(panelSource).not.toContain("@cloudflare/ai-search-snippet")
    expect(panelSource).not.toContain('<chat-page-snippet')
    expect(panelSource).not.toContain('data-testid="ai-search-chat"')
    expect(panelSource).not.toContain('aiSearchAPI')
    expect(panelSource).not.toContain('snippetConfig')
    expect(panelSource).not.toContain('runSnippetEnhancement')
    expect(panelSource).not.toContain('MutationObserver')
    expect(panelSource).not.toContain('handleChatKeydownCapture')
    expect(panelSource).not.toContain('cf-ai-search-source')
    expect(viteConfigSource).not.toContain("tag.endsWith('-snippet')")
    expect(vitestConfigSource).not.toContain("tag.endsWith('-snippet')")
  })

  it('keeps the sidecar mounted outside route-keyed pages so internal navigation does not close it', () => {
    expect(panelSource).toContain('<Teleport to="body">')
    expect(panelSource).toContain('data-testid="ai-search-sidecar"')
    expect(panelSource).toContain(':class="sidecarClass"')
    expect(panelSource).toContain(':data-open="open ? \'true\' : \'false\'"')
    expect(panelSource).toContain(':aria-hidden="!open"')
    expect(panelSource).toContain('ai-search-sidecar-open')
    expect(panelSource).toContain('ai-search-sidecar-fullscreen')
    expect(panelSource).not.toContain('v-if="open"')
    expect(panelSource).toContain('role="complementary"')
    expect(panelSource).not.toContain('aria-modal="true"')
    expect(panelSource).not.toContain('class="ai-search-overlay"')
    expect(appStoreSource).toContain('const aiSearchPanelOpen = ref<boolean>(false)')
    expect(appStoreSource).toContain('function openAISearchPanel')
    expect(appStoreSource).toContain('function closeAISearchPanel')
    expect(appSource).toContain("import AISearchPanel from '@/components/layout/AISearchPanel.vue'")
    expect(appSource).toContain('<AISearchPanel v-if="authStore.isAuthenticated" />')
    expect(appSource.indexOf('<AISearchPanel')).toBeGreaterThan(appSource.indexOf('</RouterView>'))
  })

  it('closes the panel by the close button or Escape without touching iframe state', () => {
    expect(panelSource).toContain('data-testid="layout-ai-search-panel-button-toggle-fullscreen"')
    expect(panelSource).toContain('function toggleFullscreen')
    expect(panelSource).toContain(":aria-label=\"fullscreen ? 'Exit fullscreen' : 'Fullscreen'\"")
    expect(panelSource).toContain(":aria-pressed=\"fullscreen\"")
    expect(panelSource).toContain("<Icon :name=\"fullscreen ? 'minimize' : 'maximize'")
    expect(panelSource).toContain('<Icon name="x"')
    expect(panelSource).toContain('@click="closePanel"')
    expect(panelSource).toContain("event.key === 'Escape'")
    expect(panelSource).toContain("document.addEventListener('keydown', handleKeydown)")
    expect(panelSource).toContain("document.removeEventListener('keydown', handleKeydown)")
    expect(panelSource).toContain("document.body.classList.remove('ai-search-panel-fullscreen')")
    expect(panelSource).toContain('document.body.classList.toggle')
    expect(panelSource).not.toContain('setInterval')
    expect(panelSource).not.toContain('requestAnimationFrame')
  })

  it('styles a resident trigger plus a layout-pushing right sidecar and full-height bridge frame', () => {
    const boxBlock = cssBlock(styleSource, '.ai-search-box')
    const triggerBlock = cssBlock(styleSource, '.ai-search-trigger')
    const triggerAvatarBlock = cssBlock(styleSource, '.ai-search-trigger-avatar')
    const sidecarBlock = cssBlock(styleSource, '.ai-search-sidecar')
    const fullscreenSidecarBlock = cssBlock(styleSource, '.ai-search-sidecar.ai-search-sidecar-fullscreen')
    const panelBlock = cssBlock(styleSource, '.ai-search-panel')
    const actionsBlock = cssBlock(styleSource, '.ai-search-panel-actions')
    const actionBlock = cssBlock(styleSource, '.ai-search-panel-action')
    const frameBlock = cssBlock(styleSource, '.ai-search-bridge-frame')

    expect(boxBlock).toContain('display: flex;')
    expect(triggerBlock).toContain('cursor: pointer;')
    expect(triggerBlock).toContain('border: 0;')
    expect(triggerBlock).toContain('box-shadow: none;')
    expect(triggerBlock).not.toContain('border: 1px')
    expect(triggerAvatarBlock).toContain('--creepee-avatar-size: 1.55rem;')
    expect(triggerAvatarBlock).toContain('width: var(--creepee-avatar-size);')
    expect(triggerAvatarBlock).toContain('height: var(--creepee-avatar-size);')
    expect(triggerAvatarBlock).toContain('display: block;')
    expect(triggerAvatarBlock).toContain('object-fit: contain;')
    expect(sidecarBlock).toContain('position: fixed;')
    expect(sidecarBlock).toContain('right: 0;')
    expect(sidecarBlock).toContain('width: var(--ai-search-sidecar-width);')
    expect(sidecarBlock).toContain('min-width: 34.25rem;')
    expect(sidecarBlock).toContain('transform: translate3d(100%, 0, 0);')
    expect(sidecarBlock).toContain('contain: layout paint style;')
    expect(sidecarBlock).toContain('background: var(--atelier-paper);')
    expect(sidecarBlock).toContain('box-shadow: none;')
    expect(sidecarBlock).toContain('filter: none;')
    expect(sidecarBlock).toContain('outline: 0;')
    expect(sidecarBlock).toContain('overflow: hidden;')
    expect(sidecarBlock).not.toContain('border-left:')
    expect(styleSource).toContain('#creepee-ai-sidecar.ai-search-sidecar')
    expect(styleSource).toContain('#creepee-ai-sidecar.ai-search-sidecar,')
    expect(styleSource).toContain('#creepee-ai-sidecar.ai-search-sidecar .ai-search-panel,')
    expect(styleSource).toContain('#creepee-ai-sidecar.ai-search-sidecar .ai-search-bridge-frame')
    expect(styleSource).toContain('box-shadow: none !important;')
    expect(styleSource).toContain('filter: none !important;')
    expect(styleSource).toContain('drop-shadow: none !important;')
    expect(styleSource).toContain('border: 0 !important;')
    expect(styleSource).toContain('background: var(--atelier-paper) !important;')
    expect(styleSource).toContain('#creepee-ai-sidecar.ai-search-sidecar::before')
    expect(styleSource).toContain('#creepee-ai-sidecar.ai-search-sidecar::after')
    expect(styleSource).toContain('content: none !important;')
    expect(styleSource).toContain('#creepee-ai-sidecar.ai-search-sidecar :where(.ai-search-panel, .ai-search-panel-body, .ai-search-bridge-frame)')
    expect(styleSource).toContain('text-shadow: none !important;')
    expect(styleSource).toContain('#creepee-ai-sidecar.ai-search-sidecar *')
    expect(styleSource).toContain('#creepee-ai-sidecar.ai-search-sidecar :where(.shadow-card, .paper-surface, .card, .admin-material-surface)')
    expect(styleSource).toContain('.ai-search-sidecar.ai-search-sidecar-open')
    expect(styleSource).toContain('transform: translate3d(0, 0, 0);')
    expect(fullscreenSidecarBlock).toContain('left: 0;')
    expect(fullscreenSidecarBlock).toContain('width: 100vw;')
    expect(fullscreenSidecarBlock).not.toContain('border-left:')
    expect(styleSource).toContain('--ai-search-sidecar-width: clamp(34.25rem, 42vw, 40rem);')
    expect(styleSource).toContain('@media (max-width: 560px)')
    expect(styleSource).toContain('body.ai-search-panel-open:not(.ai-search-panel-fullscreen) .app-layout-content')
    expect(styleSource).toContain('margin-right: var(--ai-search-sidecar-width);')
    expect(panelBlock).toContain('flex-direction: column;')
    expect(panelBlock).toContain('height: 100%;')
    expect(panelBlock).toContain('background: var(--atelier-paper);')
    expect(panelBlock).toContain('box-shadow: none;')
    expect(panelBlock).toContain('filter: none;')
    expect(actionsBlock).toContain('position: absolute;')
    expect(actionsBlock).toContain('right: 0.625rem;')
    expect(actionBlock).toContain('border: 0;')
    expect(actionBlock).toContain('background: transparent;')
    expect(actionBlock).toContain('width: 2rem;')
    expect(frameBlock).toContain('width: 100%;')
    expect(frameBlock).toContain('height: 100%;')
    expect(frameBlock).toContain('border: 0;')
    expect(frameBlock).toContain('background: var(--atelier-paper);')
    expect(styleSource).not.toContain('.ai-search-chat')
    expect(styleSource).not.toContain('search-snippet')
  })

  it('allows the hosted Creepee bridge origin in CSP instead of only the retired local bridge', () => {
    const securityHeadersSource = readFileSync(
      resolve(__dirname, '../../../../../backend/internal/server/middleware/security_headers.go'),
      'utf8',
    )

    expect(securityHeadersSource).toContain('CreepeeHostedBridgeOrigin = "https://obsi.creeperxco.cn"')
    expect(securityHeadersSource).toContain('{"frame-src", CreepeeHostedBridgeOrigin}')
  })
})
