import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { describe, expect, it } from 'vitest'

const styleSource = readFileSync(resolve(__dirname, '../../../style.css'), 'utf8')
const dataTableSource = readFileSync(resolve(__dirname, '../../common/DataTable.vue'), 'utf8')
const materialSystemMarker = 'Anthropic design-system component material system'
const materialSystemIndex = styleSource.indexOf(materialSystemMarker)
const materialSystemBlock = styleSource.slice(
  materialSystemIndex,
  styleSource.length
)
const blockedBackdropFilter = ['backdrop', 'filter'].join('-')
const blockedWebkitBackdropFilter = ['-webkit', blockedBackdropFilter].join('-')
const blockedLargeBlur = ['blur', '(20px)'].join('')
const blockedTableBlur = ['blur', '(16px)'].join('')

describe('right-side material surfaces', () => {
  it('ships the Anthropic material pass for ordinary surfaces and floating overlays', () => {
    expect(materialSystemIndex).toBeGreaterThan(-1)
    expect(materialSystemBlock).toContain('--route-enter-duration: 0.28s;')
    expect(styleSource).toContain('--atelier-module-enter-duration: 0.9s;')
    expect(materialSystemBlock).toContain('--anthropic-page: #faf9f5;')
    expect(materialSystemBlock).toContain('--anthropic-section: #f0eee6;')
    expect(materialSystemBlock).toContain('--anthropic-raised: #e8e6dc;')
    expect(materialSystemBlock).toContain('--anthropic-cookbook-hover: #f5f4ed;')
    expect(materialSystemBlock).toContain('--anthropic-dropdown-shadow: 0 4px 24px rgba(0, 0, 0, 0.05);')
    expect(materialSystemBlock).toContain('--atelier-canvas: var(--anthropic-page);')
    expect(styleSource).toContain('body {\n    @apply bg-accent-50 text-gray-950 dark:bg-dark-950 dark:text-gray-100;\n    @apply min-h-screen;\n    overscroll-behavior-y: none;\n    color: var(--atelier-ink);\n    background: var(--atelier-canvas);')
    expect(styleSource).toContain('.app-layout-shell {\n  background: var(--atelier-canvas);')
    expect(styleSource).toContain('.app-layout-content {\n  background: transparent;')

    expect(materialSystemBlock).toContain('.app-layout-content :where(.card, .paper-card, .paper-surface')
    expect(materialSystemBlock).toContain('.table-wrapper, .table-scroll-container')
    expect(materialSystemBlock).toContain('.codex-panel, .codex-account-card')
    expect(materialSystemBlock).toContain('background: var(--anthropic-page);')
    expect(materialSystemBlock).toContain('box-shadow: none;')
    expect(materialSystemBlock).not.toContain('.table-scroll-container, .modal-content, .dialog-container, .toast')
    expect(materialSystemBlock).toContain(':where(.modal-content, .dialog-container)')
    expect(materialSystemBlock).toContain('border-radius: 16px !important;')
    expect(materialSystemBlock).toContain('box-shadow: var(--anthropic-dropdown-shadow) !important;')
    expect(materialSystemBlock).toContain(':where(.toast)')
    expect(materialSystemBlock).toContain(':where(.toast:not(.toast-themed))')
    expect(styleSource).not.toContain(blockedBackdropFilter)
    expect(styleSource).not.toContain(blockedWebkitBackdropFilter)
    expect(styleSource).not.toContain(blockedLargeBlur)
    expect(styleSource).not.toContain(blockedTableBlur)
    expect(styleSource).toContain('background: var(--sidebar-bg);')
    expect(materialSystemBlock).not.toContain('inset 0 -1px')
  })

  it('keeps the console paper palette even when the global dark class is present', () => {
    expect(styleSource).toContain('.dark body:has(.app-layout-shell)')
    expect(styleSource).toContain('.dark .app-layout-shell {')
    expect(styleSource).toContain('--atelier-material-1: var(--atelier-paper-2);')
    expect(materialSystemBlock).toContain('--atelier-material-shadow: none;')
    expect(materialSystemBlock).toContain('--atelier-material-shadow-hover: none;')
    expect(materialSystemBlock).toContain(':root.theme-anthropic,\n:root[data-theme="anthropic"] {\n  color-scheme: light;')
    expect(materialSystemBlock).toContain('background: var(--anthropic-page);')
    expect(materialSystemBlock).toContain('color: var(--anthropic-fg);')
    expect(styleSource).toContain('.dark .sidebar {\n    --sidebar-bg: var(--atelier-paper-2);')
    expect(styleSource).not.toContain('.dark .sidebar {\n    --sidebar-bg: #050505;')
    expect(styleSource).not.toContain('@media (prefers-reduced-transparency: reduce)')
    expect(dataTableSource).not.toContain('#11100d')
    expect(dataTableSource).not.toContain('background-color: #111827;')
    expect(dataTableSource).toContain('background-color: var(--anthropic-section, var(--atelier-paper-2));')
    expect(dataTableSource).toContain('background-color: var(--anthropic-page, var(--atelier-paper));')
    expect(dataTableSource).toContain('repeating-linear-gradient(to bottom, var(--atelier-line-strong)')
    expect(dataTableSource).toContain('scrollbar-color: var(--atelier-scrollbar) var(--atelier-scrollbar-track) !important;')
  })

  it('maps inherited utility internals to Anthropic palette tokens', () => {
    expect(styleSource).toContain('--atelier-component-muted: var(--atelier-dust);')
    expect(styleSource).toContain('--atelier-component-warning: var(--atelier-butter-dark);')
    expect(styleSource).toContain('--atelier-material-blue:')
    expect(styleSource).toContain('--atelier-material-dust:')
    expect(styleSource).toContain('--atelier-material-butter:')
    expect(styleSource).toContain('--atelier-material-edge:')
    expect(materialSystemBlock).toContain('.app-layout-content :where(.badge-primary')
    expect(materialSystemBlock).toContain('.bg-blue-100.text-blue-700')
    expect(materialSystemBlock).toContain('.app-layout-content :where(.badge-warning')
    expect(materialSystemBlock).toContain('.bg-amber-100.text-amber-700')
    expect(materialSystemBlock).toContain('.app-layout-content :where(.badge-success')
    expect(materialSystemBlock).toContain('.bg-emerald-100.text-emerald-700')
    expect(materialSystemBlock).toContain(':where(.table-wrapper, .table-scroll-container, .table-container)')
    expect(materialSystemBlock).toContain(':where(thead, th, .sticky-header-cell)')
    expect(materialSystemBlock).toContain(':where(.input, input[type="text"], input[type="search"], input[type="email"], input[type="password"], input[type="number"], input[type="date"], textarea, select, .select-trigger, .date-picker-trigger, .codex-input, .codex-select, .codex-textarea)')
    expect(materialSystemBlock).toContain('background: var(--anthropic-info-bg);')
    expect(materialSystemBlock).toContain('background: var(--anthropic-warning-bg);')
    expect(materialSystemBlock).toContain('background: var(--anthropic-success-bg);')
    expect(styleSource).not.toContain('background: var(--atelier-butter-soft);')
    expect(styleSource).not.toContain('color: var(--atelier-butter-dark);')
    expect(styleSource).not.toContain('color: var(--atelier-butter-dark) !important;')
    expect(materialSystemBlock).not.toContain('--atelier-card-accent: var(--atelier-butter);')
    expect(styleSource).toContain('.home-ascii-shell')
    expect(styleSource).toContain('.auth-ascii-shell')
    expect(styleSource).toContain('background: var(--atelier-canvas);')
    expect(styleSource).toContain('--atelier-canvas: var(--anthropic-page);')
    expect(styleSource).not.toContain('linear-gradient(180deg, var(--atelier-paper) 0%, var(--atelier-paper-2) 100%)')
  })

  it('applies the material system to teleported overlays and staggered app modules, not only home', () => {
    expect(materialSystemBlock).toContain('.floating-dropdown-portal')
    expect(materialSystemBlock).toContain('.select-dropdown-portal')
    expect(materialSystemBlock).toContain('.date-picker-dropdown-portal')
    expect(materialSystemBlock).toContain('[class*="dropdown"][class*="portal"]')
    expect(materialSystemBlock).toContain('z-index: 100000040;')
    expect(materialSystemBlock).not.toContain(':where(.card, .paper-card, .paper-surface, .stat-card, .summary-tile, .admin-material-surface, .codex-panel, .codex-account-card):nth-of-type')
    expect(materialSystemBlock).toContain('var(--anthropic-info)')
    expect(materialSystemBlock).toContain('var(--anthropic-muted)')
    expect(materialSystemBlock).not.toContain('--atelier-card-accent: var(--atelier-butter);')
    expect(materialSystemBlock).toContain('color: var(--anthropic-muted);')
    expect(materialSystemBlock).toContain('color: var(--anthropic-fg);')
    expect(materialSystemBlock).not.toContain('background: var(--atelier-material-butter) !important;')
    expect(materialSystemBlock).toContain('.app-route-page-entering')
    expect(materialSystemBlock).toContain('.app-layout-content :where(.badge')
    expect(materialSystemBlock).toContain('.app-layout-content :where(.state-card, .empty-state')
    expect(materialSystemBlock).toContain('animation: app-route-page-enter var(--route-enter-duration)')
  })
})
