import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { describe, expect, it } from 'vitest'

const styleSource = readFileSync(resolve(__dirname, '../../../style.css'), 'utf8')
const materialSystemBlock = styleSource.slice(
  styleSource.indexOf('Atelier component material system'),
  styleSource.length
)
const blockedBackdropFilter = ['backdrop', 'filter'].join('-')
const blockedWebkitBackdropFilter = ['-webkit', blockedBackdropFilter].join('-')
const blockedLargeBlur = ['blur', '(20px)'].join('')
const blockedTableBlur = ['blur', '(16px)'].join('')

describe('right-side material surfaces', () => {
  it('ships a single atelier component material pass for all maintained component families', () => {
    expect(materialSystemBlock).toContain('--route-enter-duration: 1.08s;')
    expect(styleSource).toContain('--atelier-module-enter-duration: 0.9s;')
    expect(styleSource).toContain('--atelier-canvas:')
    expect(styleSource).toContain('--atelier-surface-panel:')
    expect(styleSource).toContain('--atelier-surface-cool:')
    expect(styleSource).toContain('--atelier-canvas: #eef3ff;')
    expect(styleSource).toContain('body {\n    @apply bg-accent-50 text-gray-950 dark:bg-dark-950 dark:text-gray-100;\n    @apply min-h-screen;\n    overscroll-behavior-y: none;\n    color: var(--atelier-ink);\n    background: var(--atelier-canvas);')
    expect(styleSource).toContain('.app-layout-shell {\n  background: var(--atelier-canvas);')
    expect(styleSource).toContain('.app-layout-content {\n  background: var(--atelier-canvas);')
    expect(styleSource).toContain('--atelier-material-grid: none;')
    expect(styleSource).toContain('--atelier-material-grid-dark: none;')
    expect(styleSource).toContain('--atelier-material-blue-strong:')
    expect(styleSource).toContain('--atelier-material-dust-strong:')
    expect(styleSource).toContain('--atelier-material-butter: var(--atelier-surface-dust);')
    expect(styleSource).toContain('--atelier-material-butter-strong: var(--atelier-surface-dust);')

    expect(materialSystemBlock).toContain(':where(.card, .paper-card, .paper-surface, .stat-card, .summary-tile, .admin-material-surface, .table-container, .table-wrapper, .table-scroll-container, .modal-content, .dialog-container, .toast, .codex-panel, .codex-account-card, .codex-topbar, .codex-side, .layout-section-fixed, .settings-tabs-shell)')
    expect(materialSystemBlock).toContain('.app-layout-content :where(div, section, article):where(')
    expect(styleSource).toContain('[class~="rounded-lg"]')
    expect(styleSource).toContain('[class~="bg-white/95"]')
    expect(styleSource).toContain('[class~="bg-white/90"]')
    expect(styleSource).toContain('[class~="bg-gray-50"]')
    expect(styleSource).toContain('[class~="bg-gray-50/50"]')
    expect(styleSource).toContain(':not([class*="absolute"])')
    expect(styleSource).toContain(':not([class*="fixed"])')
    expect(styleSource).toContain(':not([class~="btn"])')
    expect(styleSource).toContain(':not([role="button"])')
    expect(materialSystemBlock).toContain('background: var(--atelier-card-surface, var(--atelier-material-2)) !important;')
    expect(materialSystemBlock).not.toContain('background-size: 28px 28px, 28px 28px, auto !important;')
    expect(materialSystemBlock).not.toContain('var(--atelier-material-grid),')
    expect(materialSystemBlock).toContain('box-shadow: var(--atelier-material-shadow) !important;')
    expect(styleSource).not.toContain(blockedBackdropFilter)
    expect(styleSource).not.toContain(blockedWebkitBackdropFilter)
    expect(styleSource).not.toContain(blockedLargeBlur)
    expect(styleSource).not.toContain(blockedTableBlur)
    expect(styleSource).not.toContain('background: var(--atelier-paper);')
    expect(styleSource).not.toContain('background: var(--atelier-paper-2);')
    expect(materialSystemBlock).not.toContain('mask-image')
    expect(materialSystemBlock).not.toContain('inset 0 -1px')
  })

  it('keeps deep mode dark using the same flat material layer', () => {
    expect(styleSource).toContain('--atelier-material-shadow: 0 16px 34px -28px rgba(5, 5, 5, 0.82);')
    expect(styleSource).toContain('[class~="bg-white"]')
    expect(styleSource).toContain('[class~="rounded-lg"]')
    expect(materialSystemBlock).toContain('.dark :where(.card, .paper-card, .paper-surface, .stat-card, .summary-tile, .admin-material-surface, .table-container, .table-wrapper, .table-scroll-container, .modal-content, .dialog-container, .toast, .dropdown, .select-dropdown-portal, .date-picker-dropdown-portal, .floating-dropdown-portal, .action-menu-content, .codex-panel, .codex-account-card, .codex-topbar, .codex-side, .layout-section-fixed, .settings-tabs-shell)')
    expect(materialSystemBlock).toContain('background: var(--atelier-card-surface, var(--atelier-material-2)) !important;')
    expect(materialSystemBlock).not.toContain('var(--atelier-material-grid-dark),')
    expect(materialSystemBlock).toContain('color: #f7f1e6 !important;')
    expect(styleSource).not.toContain('@media (prefers-reduced-transparency: reduce)')
  })

  it('themes old white and gray component internals with the full atelier palette', () => {
    expect(styleSource).toContain('--atelier-component-muted: var(--atelier-dust);')
    expect(styleSource).toContain('--atelier-component-warning: var(--atelier-dust);')
    expect(styleSource).toContain('--atelier-material-blue:')
    expect(styleSource).toContain('--atelier-material-dust:')
    expect(styleSource).toContain('--atelier-material-butter:')
    expect(styleSource).toContain('--atelier-material-ink:')
    expect(styleSource).toContain('.app-layout-content :where([class~="text-gray-950"], [class~="text-gray-900"], [class~="text-gray-800"])')
    expect(styleSource).toContain('.app-layout-content :where([class~="text-gray-700"], [class~="text-gray-600"], [class~="text-gray-500"], [class~="text-gray-400"])')
    expect(styleSource).toContain('.app-layout-content :where([class~="border-gray-300"], [class~="border-gray-200"], [class~="border-gray-100"]')
    expect(materialSystemBlock).toContain('.app-layout-content :where([class~="bg-primary-50"], [class~="bg-primary-100"], [class~="bg-blue-50"]')
    expect(materialSystemBlock).toContain('.app-layout-content :where([class~="bg-amber-50"], [class~="bg-amber-100"], [class~="bg-yellow-50"]')
    expect(materialSystemBlock).toContain('.app-layout-content :where([class~="bg-emerald-50"], [class~="bg-emerald-100"], [class~="bg-green-50"]')
    expect(materialSystemBlock).toContain(':where(.table-wrapper, .table-scroll-container, .table-container)')
    expect(materialSystemBlock).toContain(':where(.table-wrapper, .table-scroll-container) :where(.table-header, .sticky-header-cell)')
    expect(materialSystemBlock).toContain(':where(.input, input[type="text"], input[type="search"], input[type="email"], input[type="password"], input[type="number"], input[type="date"], textarea, select, .select-trigger, .date-picker-trigger, .codex-input, .codex-select, .codex-textarea)')
    expect(materialSystemBlock).toContain('background: var(--atelier-material-blue) !important;')
    expect(materialSystemBlock).toContain('background: var(--atelier-material-dust) !important;')
    expect(materialSystemBlock).not.toContain('background: var(--atelier-material-butter) !important;')
    expect(styleSource).not.toContain('background: var(--atelier-butter-soft);')
    expect(styleSource).not.toContain('color: var(--atelier-butter-dark);')
    expect(materialSystemBlock).not.toContain('var(--atelier-butter)')
    expect(materialSystemBlock).not.toContain('var(--atelier-butter-dark)')
    expect(styleSource).toContain('.home-ascii-shell')
    expect(styleSource).toContain('.auth-ascii-shell')
    expect(styleSource).toContain('background: var(--atelier-canvas);')
    expect(styleSource).not.toContain('linear-gradient(180deg, var(--atelier-paper) 0%, var(--atelier-paper-2) 100%)')
  })

  it('applies the material system to teleported overlays and staggered app modules, not only home', () => {
    expect(materialSystemBlock).toContain('.floating-dropdown-portal')
    expect(materialSystemBlock).toContain('.select-dropdown-portal')
    expect(materialSystemBlock).toContain('.date-picker-dropdown-portal')
    expect(materialSystemBlock).toContain('[class*="dropdown"][class*="portal"]')
    expect(materialSystemBlock).toContain('z-index: 100000040;')
    expect(materialSystemBlock).toContain(':nth-of-type(4n + 2)')
    expect(materialSystemBlock).toContain('var(--atelier-material-blue)')
    expect(materialSystemBlock).toContain(':nth-of-type(4n + 3)')
    expect(materialSystemBlock).toContain('var(--atelier-material-dust)')
    expect(materialSystemBlock).toContain(':nth-of-type(4n + 4)')
    expect(materialSystemBlock).not.toContain('--atelier-card-accent: var(--atelier-butter);')
    expect(materialSystemBlock).toContain('color: var(--atelier-dust) !important;')
    expect(materialSystemBlock).toContain('color: color-mix(in srgb, var(--atelier-dust) 78%, var(--atelier-white)) !important;')
    expect(materialSystemBlock).not.toContain('rgba(199, 154, 58')
    expect(materialSystemBlock).toContain('.app-route-page-entering :where(')
    expect(materialSystemBlock).toContain('.layout-section-scrollable')
    expect(materialSystemBlock).toContain('.codex-topbar')
    expect(materialSystemBlock).toContain(':where(.badge, [class*="badge"], [class*="pill"], [class*="chip"]):not(.home-provider-chip)')
    expect(materialSystemBlock).toContain('animation: app-route-page-child-enter var(--atelier-module-enter-duration)')
    expect(materialSystemBlock).toContain('animation-delay: 190ms;')
  })
})
