//go:build embed

package web

import (
	"bytes"
	"context"
	"embed"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"hash/fnv"
	htmlpkg "html"
	"image"
	"image/color"
	"image/png"
	"io"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/Wei-Shaw/sub2api/internal/server/routes"
	"github.com/gin-gonic/gin"
	"golang.org/x/image/draw"
)

const (
	// NonceHTMLPlaceholder is the placeholder for nonce in HTML script tags
	NonceHTMLPlaceholder = "__CSP_NONCE_VALUE__"
)

//go:embed all:dist
var frontendFS embed.FS

// PublicSettingsProvider is an interface to fetch public settings
type PublicSettingsProvider interface {
	GetPublicSettingsForInjection(ctx context.Context) (any, error)
	GetWebAppIconSettings(ctx context.Context) (siteName string, siteLogo string, err error)
}

type webAppIconVariant struct {
	Size        int
	ContentType string
}

var webAppIconPaths = map[string]webAppIconVariant{
	"logo.png":             {Size: 192, ContentType: "image/png"},
	"apple-touch-icon.png": {Size: 180, ContentType: "image/png"},
	"icon-192.png":         {Size: 192, ContentType: "image/png"},
	"icon-512.png":         {Size: 512, ContentType: "image/png"},
}

// FrontendServer serves the embedded frontend with settings injection
type FrontendServer struct {
	distFS      fs.FS
	fileServer  http.Handler
	baseHTML    []byte
	cache       *HTMLCache
	settings    PublicSettingsProvider
	overrideDir string // local file override directory
}

// NewFrontendServer creates a new frontend server with settings injection
func NewFrontendServer(settingsProvider PublicSettingsProvider) (*FrontendServer, error) {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		return nil, err
	}

	// Read base HTML once
	file, err := distFS.Open("index.html")
	if err != nil {
		return nil, err
	}
	defer func() { _ = file.Close() }()

	baseHTML, err := io.ReadAll(file)
	if err != nil {
		return nil, err
	}

	cache := NewHTMLCache()
	cache.SetBaseHTML(baseHTML)

	return &FrontendServer{
		distFS:      distFS,
		fileServer:  http.FileServer(http.FS(distFS)),
		baseHTML:    baseHTML,
		cache:       cache,
		settings:    settingsProvider,
		overrideDir: filepath.Join("data", "public"),
	}, nil
}

// InvalidateCache invalidates the HTML cache (call when settings change)
func (s *FrontendServer) InvalidateCache() {
	if s != nil && s.cache != nil {
		s.cache.Invalidate()
	}
}

// Middleware returns the Gin middleware handler
func (s *FrontendServer) Middleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		path := c.Request.URL.Path

		// Skip API routes
		if shouldBypassEmbeddedFrontend(path) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		if s.serveDynamicWebAppAsset(c, cleanPath) {
			return
		}

		// For index.html or SPA routes, serve with injected settings
		if cleanPath == "index.html" || !s.fileExists(cleanPath) {
			s.serveIndexHTML(c)
			return
		}

		// Try local override first
		if s.tryServeOverride(c, cleanPath) {
			return
		}

		// Serve static files normally
		s.fileServer.ServeHTTP(c.Writer, c.Request)
		c.Abort()
	}
}

func (s *FrontendServer) fileExists(path string) bool {
	file, err := s.distFS.Open(path)
	if err != nil {
		return false
	}
	_ = file.Close()
	return true
}

// tryServeOverride checks if a local override file exists and serves it.
// Files in overrideDir take precedence over embedded files.
func (s *FrontendServer) tryServeOverride(c *gin.Context, cleanPath string) bool {
	if s.overrideDir == "" {
		return false
	}
	filePath := filepath.Join(s.overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func (s *FrontendServer) serveIndexHTML(c *gin.Context) {
	// Get nonce from context (generated by SecurityHeaders middleware)
	nonce := middleware.GetNonceFromContext(c)

	// Check cache first
	cached := s.cache.Get()
	if cached != nil {
		// Replace nonce placeholder with actual nonce before serving
		content := replaceNoncePlaceholder(cached.Content, nonce)

		c.Header("ETag", cached.ETag)
		c.Header("Cache-Control", "no-store") // HTML contains a per-request CSP nonce.
		c.Data(http.StatusOK, "text/html; charset=utf-8", content)
		c.Abort()
		return
	}

	// Cache miss - fetch settings and render
	ctx, cancel := context.WithTimeout(c.Request.Context(), 2*time.Second)
	defer cancel()

	settings, err := s.settings.GetPublicSettingsForInjection(ctx)
	if err != nil {
		// Fallback: serve without injection
		c.Data(http.StatusOK, "text/html; charset=utf-8", s.baseHTML)
		c.Abort()
		return
	}

	settingsJSON, err := json.Marshal(settings)
	if err != nil {
		// Fallback: serve without injection
		c.Data(http.StatusOK, "text/html; charset=utf-8", s.baseHTML)
		c.Abort()
		return
	}

	rendered := s.injectSettings(settingsJSON)
	s.cache.Set(rendered, settingsJSON)

	// Replace nonce placeholder with actual nonce before serving
	content := replaceNoncePlaceholder(rendered, nonce)

	cached = s.cache.Get()
	if cached != nil {
		c.Header("ETag", cached.ETag)
	}
	c.Header("Cache-Control", "no-store")
	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func (s *FrontendServer) injectSettings(settingsJSON []byte) []byte {
	// Create the script tag to inject with nonce placeholder
	// The placeholder will be replaced with actual nonce at request time
	script := []byte(`<script nonce="` + NonceHTMLPlaceholder + `">window.__APP_CONFIG__=` + string(settingsJSON) + `;</script>`)

	// Inject before </head>
	headClose := []byte("</head>")
	result := bytes.Replace(s.baseHTML, headClose, append(script, headClose...), 1)

	// Replace <title> with custom site name so the browser tab shows it immediately
	result = injectSiteTitle(result, settingsJSON)
	result = injectAppleWebAppTitle(result, settingsJSON)
	result = injectWebAppIconVersion(result, settingsJSON)

	return result
}

// injectSiteTitle replaces the static <title> in HTML with the configured site name.
// This ensures the browser tab shows the correct title before JS executes.
func injectSiteTitle(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteName string `json:"site_name"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil || cfg.SiteName == "" {
		return html
	}

	// Find and replace the existing <title>...</title>
	titleStart := bytes.Index(html, []byte("<title>"))
	titleEnd := bytes.Index(html, []byte("</title>"))
	if titleStart == -1 || titleEnd == -1 || titleEnd <= titleStart {
		return html
	}

	newTitle := []byte("<title>" + htmlpkg.EscapeString(cfg.SiteName) + " - AI API Gateway</title>")
	var buf bytes.Buffer
	buf.Write(html[:titleStart])
	buf.Write(newTitle)
	buf.Write(html[titleEnd+len("</title>"):])
	return buf.Bytes()
}

func injectAppleWebAppTitle(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteName string `json:"site_name"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil {
		return html
	}
	siteName := strings.TrimSpace(cfg.SiteName)
	if siteName == "" {
		return html
	}

	meta := []byte(`<meta name="apple-mobile-web-app-title" content="Sub2API" />`)
	replacement := []byte(`<meta name="apple-mobile-web-app-title" content="` + htmlpkg.EscapeString(siteName) + `" />`)
	return bytes.Replace(html, meta, replacement, 1)
}

func injectWebAppIconVersion(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteLogo string `json:"site_logo"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil || strings.TrimSpace(cfg.SiteLogo) == "" {
		return html
	}

	version := webAppIconVersion(strings.TrimSpace(cfg.SiteLogo))
	replacements := map[string]string{
		`href="/logo.png"`:             `href="/logo.png?v=` + version + `"`,
		`href="/apple-touch-icon.png"`: `href="/apple-touch-icon.png?v=` + version + `"`,
		`href="/site.webmanifest"`:     `href="/site.webmanifest?v=` + version + `"`,
	}
	result := html
	for from, to := range replacements {
		result = bytes.ReplaceAll(result, []byte(from), []byte(to))
	}
	return result
}

func webAppIconVersion(value string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(value))
	return fmt.Sprintf("%08x", h.Sum32())
}

func (s *FrontendServer) serveDynamicWebAppAsset(c *gin.Context, cleanPath string) bool {
	if cleanPath == "site.webmanifest" {
		s.serveDynamicManifest(c)
		return true
	}
	if variant, ok := webAppIconPaths[cleanPath]; ok {
		s.serveDynamicIcon(c, cleanPath, variant)
		return true
	}
	return false
}

func (s *FrontendServer) getWebAppIconSettings(ctx context.Context) (string, string, error) {
	if s.settings == nil {
		return "", "", nil
	}
	ctx, cancel := context.WithTimeout(ctx, 2*time.Second)
	defer cancel()
	return s.settings.GetWebAppIconSettings(ctx)
}

func (s *FrontendServer) serveDynamicManifest(c *gin.Context) {
	siteName, siteLogo, err := s.getWebAppIconSettings(c.Request.Context())
	if err != nil {
		s.fileServer.ServeHTTP(c.Writer, c.Request)
		c.Abort()
		return
	}
	siteName = strings.TrimSpace(siteName)
	if siteName == "" {
		siteName = "Sub2API"
	}
	version := webAppIconVersion(siteLogo + siteName)
	if strings.TrimSpace(siteLogo) == "" {
		version = "static"
	}

	payload := map[string]any{
		"name":             siteName,
		"short_name":       siteName,
		"start_url":        "/",
		"display":          "standalone",
		"background_color": "#f5f4ed",
		"theme_color":      "#c96442",
		"icons": []map[string]string{
			{
				"src":     "/icon-192.png?v=" + version,
				"sizes":   "192x192",
				"type":    "image/png",
				"purpose": "any",
			},
			{
				"src":     "/icon-512.png?v=" + version,
				"sizes":   "512x512",
				"type":    "image/png",
				"purpose": "any",
			},
		},
	}
	data, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		c.String(http.StatusInternalServerError, "Failed to render manifest")
		c.Abort()
		return
	}
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "application/manifest+json; charset=utf-8", append(data, '\n'))
	c.Abort()
}

func (s *FrontendServer) serveDynamicIcon(c *gin.Context, cleanPath string, variant webAppIconVariant) {
	_, siteLogo, err := s.getWebAppIconSettings(c.Request.Context())
	if err != nil || strings.TrimSpace(siteLogo) == "" {
		s.fileServer.ServeHTTP(c.Writer, c.Request)
		c.Abort()
		return
	}
	icon, err := renderWebAppIcon(siteLogo, variant.Size)
	if err != nil {
		s.fileServer.ServeHTTP(c.Writer, c.Request)
		c.Abort()
		return
	}
	c.Header("Cache-Control", "no-cache")
	c.Header("Content-Disposition", `inline; filename="`+cleanPath+`"`)
	c.Data(http.StatusOK, variant.ContentType, icon)
	c.Abort()
}

func renderWebAppIcon(siteLogo string, size int) ([]byte, error) {
	source, err := decodeSiteLogo(siteLogo)
	if err != nil {
		return nil, err
	}
	dst := image.NewRGBA(image.Rect(0, 0, size, size))
	draw.Draw(dst, dst.Bounds(), image.NewUniform(color.White), image.Point{}, draw.Src)

	bounds := source.Bounds()
	side := bounds.Dx()
	if bounds.Dy() < side {
		side = bounds.Dy()
	}
	if side <= 0 {
		return nil, fmt.Errorf("invalid logo dimensions")
	}
	srcRect := image.Rect(
		bounds.Min.X+(bounds.Dx()-side)/2,
		bounds.Min.Y+(bounds.Dy()-side)/2,
		bounds.Min.X+(bounds.Dx()+side)/2,
		bounds.Min.Y+(bounds.Dy()+side)/2,
	)
	draw.BiLinear.Scale(dst, dst.Bounds(), source, srcRect, draw.Over, nil)

	var buf bytes.Buffer
	if err := png.Encode(&buf, dst); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func decodeSiteLogo(siteLogo string) (image.Image, error) {
	siteLogo = strings.TrimSpace(siteLogo)
	const prefix = "data:image/png;base64,"
	if !strings.HasPrefix(siteLogo, prefix) {
		return nil, fmt.Errorf("site logo is not a PNG data URL")
	}
	raw, err := base64.StdEncoding.DecodeString(strings.TrimPrefix(siteLogo, prefix))
	if err != nil {
		return nil, err
	}
	img, err := png.Decode(bytes.NewReader(raw))
	if err != nil {
		return nil, err
	}
	return img, nil
}

// replaceNoncePlaceholder replaces the nonce placeholder with actual nonce value
func replaceNoncePlaceholder(html []byte, nonce string) []byte {
	return bytes.ReplaceAll(html, []byte(NonceHTMLPlaceholder), []byte(nonce))
}

// ServeEmbeddedFrontend returns a middleware for serving embedded frontend
// This is the legacy function for backward compatibility when no settings provider is available
func ServeEmbeddedFrontend() gin.HandlerFunc {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		panic("failed to get dist subdirectory: " + err.Error())
	}
	fileServer := http.FileServer(http.FS(distFS))
	overrideDir := filepath.Join("data", "public")

	return func(c *gin.Context) {
		path := c.Request.URL.Path

		if shouldBypassEmbeddedFrontend(path) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		if file, err := distFS.Open(cleanPath); err == nil {
			_ = file.Close()
			// Try local override first
			if tryServeOverrideFile(c, overrideDir, cleanPath) {
				return
			}
			fileServer.ServeHTTP(c.Writer, c.Request)
			c.Abort()
			return
		}

		serveIndexHTML(c, distFS)
	}
}

// tryServeOverrideFile is a standalone version of tryServeOverride for legacy usage.
func tryServeOverrideFile(c *gin.Context, overrideDir, cleanPath string) bool {
	if overrideDir == "" {
		return false
	}
	filePath := filepath.Join(overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func shouldBypassEmbeddedFrontend(path string) bool {
	trimmed := strings.TrimSpace(path)
	return strings.HasPrefix(trimmed, "/api/") ||
		strings.HasPrefix(trimmed, "/v1/") ||
		strings.HasPrefix(trimmed, "/v1beta/") ||
		strings.HasPrefix(trimmed, "/backend-api/") ||
		strings.HasPrefix(trimmed, "/antigravity/") ||
		routes.IsCPAManagementProxyPath(trimmed) ||
		strings.HasPrefix(trimmed, "/setup/") ||
		trimmed == "/health" ||
		trimmed == "/responses" ||
		strings.HasPrefix(trimmed, "/responses/") ||
		strings.HasPrefix(trimmed, "/images/")
}

func serveIndexHTML(c *gin.Context, fsys fs.FS) {
	file, err := fsys.Open("index.html")
	if err != nil {
		c.String(http.StatusNotFound, "Frontend not found")
		c.Abort()
		return
	}
	defer func() { _ = file.Close() }()

	content, err := io.ReadAll(file)
	if err != nil {
		c.String(http.StatusInternalServerError, "Failed to read index.html")
		c.Abort()
		return
	}

	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func HasEmbeddedFrontend() bool {
	_, err := frontendFS.ReadFile("dist/index.html")
	return err == nil
}
